'use client';

import { useState } from 'react';
import Script from 'next/script';
import Link from 'next/link';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Heart, Zap, Target, Activity, Shield } from 'lucide-react';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { Input } from '@/components/ui/input';

const formSchema = z.object({
  annualCostSynergies: z.number({ invalid_type_error: 'Enter annual cost synergies' }).min(0).optional(),
  annualRevenueSynergies: z.number({ invalid_type_error: 'Enter annual revenue synergies' }).min(0).optional(),
  combinedGrossMargin: z.number({ invalid_type_error: 'Enter combined gross margin' }).min(0).max(100).optional(),
  synergyDurationYears: z.number({ invalid_type_error: 'Enter synergy duration years' }).min(1).max(20).optional(),
  wacc: z.number({ invalid_type_error: 'Enter WACC' }).min(0).max(100),
  oneTimeIntegrationCosts: z.number({ invalid_type_error: 'Enter one-time integration costs' }).min(0).optional(),
});

type FormValues = z.infer<typeof formSchema>;

type ResultPayload = {
  annualCostSynergies?: number;
  annualRevenueSynergies?: number;
  combinedGrossMargin?: number;
  synergyDurationYears: number;
  wacc: number;
  oneTimeIntegrationCosts?: number;
  annualCostSynergyAfterTax: number;
  annualRevenueSynergyAfterTax: number;
  totalAnnualSynergies: number;
  npvOfSynergies: number;
  netSynergyValue: number;
  interpretation: string;
  status: 'optimal' | 'good' | 'moderate' | 'low';
  recommendations: string[];
  plan: { label: string; detail: string }[];
};

const steps = [
  'Enter annual cost synergies and/or revenue synergies.',
  'Enter combined gross margin (for revenue synergies).',
  'Enter synergy duration years and WACC.',
  'Optionally enter one-time integration costs.',
  'Review synergy value and NPV calculations.',
];

const faqs = [
  {
    question: 'What is synergy value in M&A?',
    answer:
      'Synergy value is the additional value created by combining two companies, typically through cost savings (cost synergies) or increased revenue (revenue synergies). Synergies justify acquisition premiums and represent the additional value beyond the sum of the two companies\' standalone values.',
  },
  {
    question: 'What are cost synergies?',
    answer:
      'Cost synergies are cost savings achieved by eliminating redundant expenses, streamlining operations, or achieving economies of scale. Common sources include: eliminating duplicate functions (overhead, sales, R&D), consolidating facilities, reducing headcount, leveraging purchasing power, and optimizing supply chains. Cost synergies directly increase operating income.',
  },
  {
    question: 'What are revenue synergies?',
    answer:
      'Revenue synergies are additional revenue generated by the combined entity, typically through: cross-selling products to each company\'s customers, accessing new markets or channels, combining complementary product portfolios, leveraging combined brand strength, and enhancing product offerings. Revenue synergies must be adjusted for associated costs using gross margin.',
  },
  {
    question: 'How is synergy value calculated?',
    answer:
      'Synergy Value = NPV of Annual Synergies - One-Time Integration Costs. Annual Synergies = Cost Synergies (after-tax) + Revenue Synergies * Gross Margin (after-tax). NPV is calculated by discounting annual synergies over the synergy duration period using WACC. Integration costs reduce the net synergy value.',
  },
  {
    question: 'How do I estimate cost synergies?',
    answer:
      'Estimate cost synergies by: identifying overlapping functions and estimating elimination savings, analyzing facilities and operations for consolidation opportunities, assessing headcount reduction potential, evaluating purchasing and supply chain consolidation benefits, and benchmarking against similar transactions. Be realistic - not all identified synergies are achievable.',
  },
  {
    question: 'How do I estimate revenue synergies?',
    answer:
      'Estimate revenue synergies by: assessing cross-selling opportunities between customer bases, evaluating market access and channel expansion potential, analyzing product portfolio complementarity, considering brand and marketing synergies, and reviewing customer overlap and expansion opportunities. Apply gross margin to get operating income impact.',
  },
  {
    question: 'What is synergy duration?',
    answer:
      'Synergy duration is the period over which synergies are expected to be realized, typically 3-10 years. Most synergies are realized within 3-5 years, with cost synergies typically faster than revenue synergies. The duration reflects how long it takes to fully integrate operations and realize benefits, after which synergies are considered part of normal operations.',
  },
  {
    question: 'How do integration costs affect synergy value?',
    answer:
      'One-time integration costs reduce net synergy value. These costs include: severance and restructuring costs, system integration and IT costs, facility consolidation expenses, legal and regulatory costs, and management time. Integration costs are typically incurred in the first 1-2 years and should be deducted from the NPV of synergies to get net synergy value.',
  },
  {
    question: 'What is a reasonable synergy estimate?',
    answer:
      'Reasonable synergy estimates vary by deal type. Cost synergies typically range from 5-15% of combined operating expenses for horizontal mergers, and may be lower for unrelated acquisitions. Revenue synergies are more variable and harder to predict. Historical M&A data shows many deals fail to achieve projected synergies, so conservative estimates are prudent.',
  },
  {
    question: 'How do I validate synergy estimates?',
    answer:
      'Validate synergy estimates by: comparing to similar transactions and industry benchmarks, reviewing detailed synergy plans and management estimates, assessing achievability of specific synergy sources, checking if synergies are already included in projections, performing sensitivity analysis on key assumptions, and ensuring synergies are incremental (not double-counted with standalone improvements).',
  },
];

const relatedCalculators = [
  {
    name: 'Accretion/Dilution (EPS Impact) Calculator',
    slug: 'accretion-dilution-eps-impact-calculator',
    description: 'Calculate EPS accretion/dilution from M&A.',
  },
  {
    name: 'Deal Value vs Enterprise Value Bridge Calculator',
    slug: 'deal-value-vs-enterprise-value-bridge-calculator',
    description: 'Calculate deal value bridge.',
  },
  {
    name: 'Precedent Transaction Valuation Calculator',
    slug: 'precedent-transaction-valuation-calculator',
    description: 'Calculate precedent transaction valuation.',
  },
  {
    name: 'DCF Calculator',
    slug: 'dcf-calculator',
    description: 'Calculate discounted cash flow.',
  },
];

const baseUrl = 'https://mycalculating.com/finance/synergy-value-calculator-ma-synergy-estimator';

const schemaMarkup = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://mycalculating.com' },
        { '@type': 'ListItem', position: 2, name: 'Finance', item: 'https://mycalculating.com/finance' },
        { '@type': 'ListItem', position: 3, name: 'Synergy Value Calculator (M&A Synergy Estimator)', item: baseUrl },
      ],
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Synergy Value Calculator (M&A Synergy Estimator)',
      applicationCategory: 'Calculator',
      operatingSystem: 'Web Browser',
      description: 'Estimate synergy value in M&A transactions by calculating NPV of cost and revenue synergies minus integration costs.',
      url: baseUrl,
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    },
  ],
};

const calculateResult = (values: FormValues): ResultPayload => {
  const annualCostSynergies = values.annualCostSynergies ?? 0;
  const annualRevenueSynergies = values.annualRevenueSynergies ?? 0;
  const combinedGrossMargin = values.combinedGrossMargin ? values.combinedGrossMargin / 100 : 0.3; // Default 30%
  const synergyDurationYears = values.synergyDurationYears ?? 5;
  const waccPct = values.wacc / 100;
  const oneTimeIntegrationCosts = values.oneTimeIntegrationCosts ?? 0;
  
  // Assume 25% tax rate for after-tax calculations
  const taxRate = 0.25;
  
  // Cost synergies are direct cost savings, after-tax
  const annualCostSynergyAfterTax = annualCostSynergies * (1 - taxRate);
  
  // Revenue synergies: apply gross margin to get operating income, then after-tax
  const revenueSynergyOperatingIncome = annualRevenueSynergies * combinedGrossMargin;
  const annualRevenueSynergyAfterTax = revenueSynergyOperatingIncome * (1 - taxRate);
  
  // Total annual synergies (after-tax)
  const totalAnnualSynergies = annualCostSynergyAfterTax + annualRevenueSynergyAfterTax;
  
  // Calculate NPV of synergies over duration period
  let npvOfSynergies = 0;
  if (waccPct > 0 && synergyDurationYears > 0) {
    if (waccPct > 0) {
      const annuityFactor = (1 - Math.pow(1 + waccPct, -synergyDurationYears)) / waccPct;
      npvOfSynergies = totalAnnualSynergies * annuityFactor;
    } else {
      npvOfSynergies = totalAnnualSynergies * synergyDurationYears;
    }
  }
  
  // Net Synergy Value = NPV of Synergies - Integration Costs
  const netSynergyValue = npvOfSynergies - oneTimeIntegrationCosts;
  
  let status: ResultPayload['status'] = 'optimal';
  let interpretation = '';
  
  if (totalAnnualSynergies === 0 && oneTimeIntegrationCosts === 0) {
    status = 'low';
    interpretation = 'No synergies or integration costs entered.';
  } else if (totalAnnualSynergies === 0) {
    status = 'low';
    interpretation = `Only integration costs entered (${oneTimeIntegrationCosts.toLocaleString()}) - no synergies to offset.`;
  } else {
    interpretation = `Net synergy value: ${netSynergyValue.toLocaleString()}. NPV of synergies: ${npvOfSynergies.toLocaleString()}, Integration costs: ${oneTimeIntegrationCosts.toLocaleString()}.`;
    
    if (netSynergyValue < 0) {
      status = 'low';
      interpretation += ' Negative net synergy value - integration costs exceed synergy benefits.';
    } else if (netSynergyValue > npvOfSynergies * 0.5) {
      status = 'optimal';
      interpretation += ' Strong positive synergy value.';
    } else if (netSynergyValue > 0) {
      status = 'good';
      interpretation += ' Positive synergy value with significant integration costs.';
    }
  }

  const recommendations: string[] = [];
  
  if (totalAnnualSynergies === 0 && oneTimeIntegrationCosts === 0) {
    recommendations.push('CRITICAL: No synergies or integration costs entered. Enter annual cost synergies, revenue synergies (with gross margin), synergy duration, and WACC to calculate synergy value. Optionally enter one-time integration costs to calculate net synergy value.');
  } else {
    if (annualCostSynergies > 0) {
      recommendations.push(`Cost synergies: Annual cost synergies of ${annualCostSynergies.toLocaleString()} result in after-tax synergies of ${annualCostSynergyAfterTax.toLocaleString()} (assuming 25% tax rate). Cost synergies typically include elimination of duplicate functions, facility consolidation, headcount reduction, and operational efficiencies.`);
    }
    
    if (annualRevenueSynergies > 0) {
      recommendations.push(`Revenue synergies: Annual revenue synergies of ${annualRevenueSynergies.toLocaleString()} with ${values.combinedGrossMargin ? values.combinedGrossMargin : 30}% gross margin result in after-tax synergies of ${annualRevenueSynergyAfterTax.toLocaleString()}. Revenue synergies typically include cross-selling opportunities, market access, and product portfolio enhancement.`);
    }
    
    recommendations.push(`NPV of synergies: ${npvOfSynergies.toLocaleString()} calculated as the present value of ${synergyDurationYears} years of annual synergies (${totalAnnualSynergies.toLocaleString()} per year) discounted at ${values.wacc}% WACC. This represents the value today of all future synergy benefits.`);
    
    if (oneTimeIntegrationCosts > 0) {
      recommendations.push(`Integration costs: One-time integration costs of ${oneTimeIntegrationCosts.toLocaleString()} reduce net synergy value. Integration costs typically include severance, system integration, facility consolidation, and other one-time expenses. Net synergy value: ${netSynergyValue.toLocaleString()}.`);
      
      if (netSynergyValue < 0) {
        recommendations.push('WARNING: Negative net synergy value indicates integration costs exceed the NPV of synergies. This suggests the deal may not create value from a synergy perspective. Review synergy estimates and integration cost assumptions. Consider if synergies are realistic and achievable.');
      }
    } else {
      recommendations.push(`Net synergy value: ${netSynergyValue.toLocaleString()} (no integration costs deducted). Integration costs are typically 10-30% of annual synergies and should be factored into the analysis for a complete picture.`);
    }
  }
  
  recommendations.push('Validation: Validate synergy estimates by comparing to similar transactions, reviewing detailed synergy plans, assessing achievability, and ensuring synergies are incremental (not double-counted). Many deals fail to achieve projected synergies, so conservative estimates are prudent.');

  const plan = [
    { label: 'This Week', detail: `Calculate synergy value: Net synergy value ${netSynergyValue.toLocaleString()} (NPV ${npvOfSynergies.toLocaleString()} minus integration costs ${oneTimeIntegrationCosts.toLocaleString()}). Document synergy sources, assumptions, and integration cost estimates.` },
    { label: 'This Month', detail: 'Validate synergy estimates against similar transactions and industry benchmarks. Review detailed synergy plans with management. Assess achievability of specific synergy sources. Perform sensitivity analysis on key assumptions (duration, WACC, gross margin).' },
    { label: 'Ongoing', detail: 'Monitor synergy realization against projections. Update estimates as integration progresses. Track actual integration costs versus estimates. Adjust synergy assumptions based on actual performance and market feedback. Use actual results to improve future synergy estimation accuracy.' },
  ];

  return { annualCostSynergies: annualCostSynergies > 0 ? annualCostSynergies : undefined, annualRevenueSynergies: annualRevenueSynergies > 0 ? annualRevenueSynergies : undefined, combinedGrossMargin: values.combinedGrossMargin, synergyDurationYears, wacc: values.wacc, oneTimeIntegrationCosts: oneTimeIntegrationCosts > 0 ? oneTimeIntegrationCosts : undefined, annualCostSynergyAfterTax, annualRevenueSynergyAfterTax, totalAnnualSynergies, npvOfSynergies, netSynergyValue, interpretation, status, recommendations, plan };
};

export default function SynergyValueCalculatorMaSynergyEstimator() {
  const [result, setResult] = useState<ResultPayload | null>(null);

  const form = useForm<FormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      annualCostSynergies: undefined,
      annualRevenueSynergies: undefined,
      combinedGrossMargin: undefined,
      synergyDurationYears: undefined,
      wacc: undefined,
      oneTimeIntegrationCosts: undefined,
    },
  });

  return (
    <div className="space-y-8">
      <Script id="synergy-value-schema" type="application/ld+json" strategy="afterInteractive" dangerouslySetInnerHTML={{ __html: JSON.stringify(schemaMarkup) }} />

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Heart className="h-5 w-5" />
            Synergy Value Calculator (M&A Synergy Estimator)
          </CardTitle>
          <CardDescription>Estimate synergy value in M&A transactions by calculating NPV of cost and revenue synergies minus integration costs.</CardDescription>
        </CardHeader>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Input your synergy estimation parameters</CardTitle>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit((values) => setResult(calculateResult(values)))} className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <FormField
                  control={form.control}
                  name="annualCostSynergies"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Annual Cost Synergies (Optional)</FormLabel>
                      <FormControl>
                        <Input type="number" step="0.01" placeholder="e.g., 50000000" value={field.value ?? ''} onChange={(e) => field.onChange(e.target.value === '' ? undefined : Number(e.target.value))} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="annualRevenueSynergies"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Annual Revenue Synergies (Optional)</FormLabel>
                      <FormControl>
                        <Input type="number" step="0.01" placeholder="e.g., 30000000" value={field.value ?? ''} onChange={(e) => field.onChange(e.target.value === '' ? undefined : Number(e.target.value))} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="combinedGrossMargin"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Combined Gross Margin (%) - Optional</FormLabel>
                      <FormControl>
                        <Input type="number" step="0.1" placeholder="e.g., 30" value={field.value ?? ''} onChange={(e) => field.onChange(e.target.value === '' ? undefined : Number(e.target.value))} />
                      </FormControl>
                      <FormMessage />
                      <p className="text-xs text-muted-foreground">For revenue synergies (default: 30%)</p>
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="synergyDurationYears"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Synergy Duration (Years) - Optional</FormLabel>
                      <FormControl>
                        <Input type="number" step="1" placeholder="e.g., 5" value={field.value ?? ''} onChange={(e) => field.onChange(e.target.value === '' ? undefined : Number(e.target.value))} />
                      </FormControl>
                      <FormMessage />
                      <p className="text-xs text-muted-foreground">Default: 5 years</p>
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="wacc"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>WACC (%)</FormLabel>
                      <FormControl>
                        <Input type="number" step="0.1" placeholder="e.g., 10" value={field.value ?? ''} onChange={(e) => field.onChange(e.target.value === '' ? undefined : Number(e.target.value))} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="oneTimeIntegrationCosts"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>One-Time Integration Costs (Optional)</FormLabel>
                      <FormControl>
                        <Input type="number" step="0.01" placeholder="e.g., 25000000" value={field.value ?? ''} onChange={(e) => field.onChange(e.target.value === '' ? undefined : Number(e.target.value))} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>
              <Button type="submit" className="w-full md:w-auto">
                Calculate Synergy Value
              </Button>
            </form>
          </Form>
        </CardContent>
      </Card>

      {result && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Zap className="h-5 w-5 text-primary" />
              Interactive results
            </CardTitle>
            <CardDescription>See synergy value calculation and NPV.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div className="p-4 border rounded">
                <p className="text-sm text-muted-foreground">Total Annual Synergies</p>
                <p className="text-2xl font-semibold text-primary">{result.totalAnnualSynergies.toLocaleString()}</p>
                <p className="text-xs text-muted-foreground">After-tax</p>
              </div>
              <div className="p-4 border rounded">
                <p className="text-sm text-muted-foreground">NPV of Synergies</p>
                <p className="text-2xl font-semibold text-primary">{result.npvOfSynergies.toLocaleString()}</p>
                <p className="text-xs text-muted-foreground">Present value</p>
              </div>
              <div className="p-4 border rounded">
                <p className="text-sm text-muted-foreground">Net Synergy Value</p>
                <p className="text-2xl font-semibold text-primary">{result.netSynergyValue.toLocaleString()}</p>
                <p className="text-xs text-muted-foreground">After integration costs</p>
              </div>
              <div className="p-4 border rounded">
                <p className="text-sm text-muted-foreground">Status</p>
                <p className="text-2xl font-semibold text-primary capitalize">{result.status}</p>
                <p className="text-xs text-muted-foreground">{result.interpretation}</p>
              </div>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <Card>
                <CardHeader>
                  <CardTitle className="text-base flex items-center gap-2">
                    <Target className="h-4 w-4" />
                    Recommendations
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <ul className="list-disc pl-4 space-y-1 text-sm text-muted-foreground">
                    {result.recommendations.map((rec, idx) => (
                      <li key={idx}>{rec}</li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle className="text-base flex items-center gap-2">
                    <Activity className="h-4 w-4" />
                    Action plan
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-1 text-sm text-muted-foreground">
                    {result.plan.map((step) => (
                      <li key={step.label}>
                        <span className="font-semibold">{step.label}:</span> {step.detail}
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            </div>
          </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Shield className="h-5 w-5" />
            Formula
          </CardTitle>
        </CardHeader>
        <CardContent className="text-sm text-muted-foreground space-y-2">
          <p>
            <strong>Annual Cost Synergy (After-Tax)</strong> = Annual Cost Synergies * (1 - Tax Rate)
          </p>
          <p>
            <strong>Annual Revenue Synergy (After-Tax)</strong> = Annual Revenue Synergies * Gross Margin * (1 - Tax Rate)
          </p>
          <p>
            <strong>Total Annual Synergies</strong> = Cost Synergy (After-Tax) + Revenue Synergy (After-Tax)
          </p>
          <p>
            <strong>NPV of Synergies</strong> = Total Annual Synergies * [(1 - (1 + WACC)^(-n)) / WACC]
          </p>
          <p>Where n = synergy duration years</p>
          <p>
            <strong>Net Synergy Value</strong> = NPV of Synergies - One-Time Integration Costs
          </p>
          <p>Synergy value represents the additional value created by combining two companies through cost savings and revenue enhancements. Cost synergies directly reduce costs, while revenue synergies must be adjusted for associated costs using gross margin. The NPV of synergies discounts future benefits to present value, and integration costs reduce the net value realized.</p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Steps</CardTitle>
        </CardHeader>
        <CardContent>
          <ul className="list-disc pl-5 space-y-2 text-sm text-muted-foreground">
            {steps.map((step) => (
              <li key={step}>{step}</li>
            ))}
          </ul>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Additional calculations</CardTitle>
        </CardHeader>
        <CardContent>
          {result ? (
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div className="p-4 border rounded">
                <p className="text-sm text-muted-foreground">Cost Synergies (After-Tax)</p>
                <p className="text-xl font-semibold text-primary">{result.annualCostSynergyAfterTax.toLocaleString()}</p>
                <p className="text-xs text-muted-foreground">Annual</p>
              </div>
              <div className="p-4 border rounded">
                <p className="text-sm text-muted-foreground">Revenue Synergies (After-Tax)</p>
                <p className="text-xl font-semibold text-primary">{result.annualRevenueSynergyAfterTax.toLocaleString()}</p>
                <p className="text-xs text-muted-foreground">Annual</p>
              </div>
              <div className="p-4 border rounded">
                <p className="text-sm text-muted-foreground">Integration Costs</p>
                <p className="text-xl font-semibold text-primary">{result.oneTimeIntegrationCosts?.toLocaleString() ?? 0}</p>
                <p className="text-xs text-muted-foreground">One-time</p>
              </div>
              <div className="p-4 border rounded">
                <p className="text-sm text-muted-foreground">Synergy Duration</p>
                <p className="text-xl font-semibold text-primary">{result.synergyDurationYears} years</p>
                <p className="text-xs text-muted-foreground">Period</p>
              </div>
            </div>
          ) : (
            <p className="text-sm text-muted-foreground">Enter your synergy estimation parameters to see additional insights.</p>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Related calculators</CardTitle>
        </CardHeader>
        <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {relatedCalculators.map((calc) => (
            <div key={calc.slug} className="p-4 border rounded">
              <h4 className="font-semibold mb-1">
                <Link href={`/${calc.slug}`} className="text-primary hover:underline">
                  {calc.name}
                </Link>
              </h4>
              <p className="text-sm text-muted-foreground">{calc.description}</p>
            </div>
          ))}
        </CardContent>
      </Card>

      <section
        className="space-y-6 text-muted-foreground leading-relaxed bg-white dark:bg-gray-900 p-6 md:p-10 rounded-lg shadow-lg"
        itemScope
        itemType="https://schema.org/Article"
      >
        <meta itemProp="name" content="The Complete Guide to M&A Synergy Value: Cost and Revenue Synergy Estimation" />
        <meta itemProp="description" content="An in-depth guide on estimating synergy value in M&A transactions by calculating NPV of cost and revenue synergies minus integration costs." />
        <meta itemProp="keywords" content="synergy value, M&A synergies, cost synergies, revenue synergies, merger synergies, acquisition synergies" />
        <meta itemProp="author" content="[Your Site's Finance Team]" />
        <meta itemProp="datePublished" content="2025-12-02" />
        <meta itemProp="url" content="/synergy-value-calculator-ma-synergy-estimator" />

        <h1 className="text-3xl md:text-4xl font-extrabold text-foreground mb-4" itemProp="headline">The Complete Guide to M&A Synergy Value: Cost and Revenue Synergy Estimation</h1>
        <p className="text-lg italic text-gray-700 dark:text-gray-300">A comprehensive look at estimating synergy value in M&A transactions by calculating NPV of cost and revenue synergies minus integration costs.</p>

        <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">Table of Contents: Jump to a Section</h2>
        <ul className="list-disc ml-6 space-y-2 text-blue-600 dark:text-blue-400">
          <li><a href="#basics" className="hover:underline">Understanding M&A Synergies</a></li>
          <li><a href="#cost" className="hover:underline">Cost Synergies</a></li>
          <li><a href="#revenue" className="hover:underline">Revenue Synergies</a></li>
          <li><a href="#calculation" className="hover:underline">Synergy Value Calculation</a></li>
          <li><a href="#validation" className="hover:underline">Validation and Best Practices</a></li>
        </ul>
        <hr className="my-6" />

        <h2 id="basics" className="text-2xl font-bold text-foreground pt-8" itemProp="articleSection">Understanding M&A Synergies</h2>
        <p>Synergies represent additional value created by combining two companies through cost savings or revenue enhancements.</p>

        <hr className="my-6" />

        <h2 id="cost" className="text-2xl font-bold text-foreground pt-8" itemProp="articleSection">Cost Synergies</h2>
        <p>Cost synergies are savings from eliminating redundant expenses, consolidating operations, and achieving economies of scale.</p>

        <hr className="my-6" />

        <h2 id="revenue" className="text-2xl font-bold text-foreground pt-8" itemProp="articleSection">Revenue Synergies</h2>
        <p>Revenue synergies are additional revenue from cross-selling, market access, and product portfolio enhancement.</p>

        <hr className="my-6" />

        <h2 id="calculation" className="text-2xl font-bold text-foreground pt-8" itemProp="articleSection">Synergy Value Calculation</h2>
        <div className="bg-gray-100 dark:bg-gray-800 p-4 rounded-lg my-4">
          <p className="font-mono text-lg"><strong>Net Synergy Value = NPV of Synergies - Integration Costs</strong></p>
        </div>

        <hr className="my-6" />

        <h2 id="validation" className="text-2xl font-bold text-foreground pt-8" itemProp="articleSection">Validation and Best Practices</h2>
        <p>Validate synergies by comparing to similar transactions, reviewing detailed plans, and ensuring realistic estimates.</p>

        <hr className="my-6" />

        <h2 className="text-2xl font-bold text-foreground pt-8" itemProp="articleSection">Conclusion</h2>
        <p>Synergy value estimation is critical in M&A transactions as it justifies acquisition premiums and represents additional value beyond standalone values. Proper estimation requires realistic assessment of both cost and revenue synergies, appropriate consideration of integration costs, and careful validation against benchmarks. Conservative estimates and sensitivity analysis help ensure realistic synergy projections.</p>
      </section>

      <Card>
        <CardHeader>
          <CardTitle>FAQs</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          {faqs.map((faq) => (
            <div key={faq.question}>
              <h4 className="font-semibold">{faq.question}</h4>
              <p className="text-sm text-muted-foreground">{faq.answer}</p>
            </div>
          ))}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Shield className="h-5 w-5" />
            Summary
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-2 text-sm text-muted-foreground">
          <p>This tool estimates synergy value in M&A transactions by calculating NPV of cost and revenue synergies minus integration costs.</p>
          <p>Outputs include annual synergies (after-tax), NPV of synergies, net synergy value, interpretation, recommendations, an action plan, and supporting metrics.</p>
          <p>Formula, steps, guide content, related tools, and FAQs ensure humans or AI assistants can interpret the methodology instantly.</p>
        </CardContent>
      </Card>
    </div>
  );
}



