
export interface Calculator {
  id: number;
  name: string;
  description: string;
  slug: string;
  category: string;
}

export const calculators: Calculator[] = [
  // Finance
  {
    id: 95,
    name: 'SIP Returns Calculator',
    description: 'Project the future value of your Systematic Investment Plan (SIP). See how regular, disciplined investing and the power of compounding can help you reach your financial goals.',
    slug: 'sip-calculator',
    category: 'finance',
  },
  {
    id: 96,
    name: 'Loan/EMI Calculator',
    description: 'Calculate your monthly payment (EMI) for any loan, including mortgages, auto loans, or personal loans. Understand your repayment schedule with a detailed amortization graph.',
    slug: 'loan-emi-calculator',
    category: 'finance',
  },
  {
    id: 97,
    name: 'Retirement Savings Calculator',
    description: 'Plan for your future by estimating your retirement corpus based on current savings, contributions, and expected returns. Find out if you are on track to meet your retirement goals.',
    slug: 'retirement-savings-calculator',
    category: 'finance',
  },
  {
    id: 98,
    name: 'Compound Interest Calculator',
    description: 'Calculate the future value of an investment using the power of compound interest. Visualize how your savings can grow over time with different compounding frequencies.',
    slug: 'compound-interest-calculator',
    category: 'finance'
  },
  {
    id: 99,
    name: '401(k) Contribution Calculator',
    description: 'Estimate your 401(k) growth by retirement, including your contributions, employer match, and investment returns. Visualize your path to a secure retirement.',
    slug: '401k-contribution-calculator',
    category: 'finance',
  },
  {
    id: 100,
    name: 'Net Worth Calculator',
    description: 'Get a clear picture of your financial health by calculating your net worth. Track your assets and liabilities to understand your overall wealth and financial progress.',
    slug: 'net-worth-calculator',
    category: 'finance',
  },
  {
    id: 101,
    name: 'Credit Card Payoff Calculator',
    description: 'Find out how long it will take to pay off your credit card balance based on your monthly payment. See the total interest you\'ll pay and get a plan to become debt-free.',
    slug: 'credit-card-payoff-calculator',
    category: 'finance',
  },
  {
    id: 102,
    name: 'Mortgage Payment Calculator',
    description: 'Estimate your monthly mortgage payment. See how principal, interest, and loan term affect your payment and view a detailed amortization schedule.',
    slug: 'mortgage-payment-calculator',
    category: 'finance',
  },
  {
    id: 103,
    name: 'Student Loan Repayment Calculator',
    description: 'Understand your student loan repayment options. Calculate your monthly payment and the total interest you\'ll pay over the life of the loan.',
    slug: 'student-loan-repayment-calculator',
    category: 'finance',
  },
  {
    id: 104,
    name: 'Inflation Calculator',
    description: 'See how the value of your money may decrease over time due to inflation. Understand the future purchasing power of your savings.',
    slug: 'inflation-calculator',
    category: 'finance',
  },
  {
    id: 105,
    name: 'Roth IRA Contribution Limit Calculator',
    description: 'Determine your maximum allowed Roth IRA contribution for the current tax year based on your income, filing status, and age.',
    slug: 'roth-ira-contribution-limit-calculator',
    category: 'finance',
  },
  {
    id: 159,
    name: 'Present Value (PV) Calculator',
    description: 'Calculate the current worth of a future sum of money. This is a fundamental concept in finance that allows you to evaluate whether an investment is worth making today by understanding what a future cash flow is worth in today\'s dollars.',
    slug: 'present-value-calculator',
    category: 'finance',
  },
  {
    id: 160,
    name: 'Future Value (FV) Calculator',
    description: 'Project the future worth of a current investment given a specific rate of return. This tool helps you visualize how your money can grow over time, demonstrating the power of compounding interest on your initial savings.',
    slug: 'future-value-calculator',
    category: 'finance',
  },
  {
    id: 161,
    name: 'Annuity Payment Calculator',
    description: 'Determine the fixed periodic payment required for a loan or to reach a specified future savings goal. This is useful for understanding mortgage payments, car loans, or planning contributions for a retirement fund.',
    slug: 'annuity-payment-calculator',
    category: 'finance',
  },
  {
    id: 162,
    name: 'Perpetuity Calculator',
    description: 'Calculate the present value of an infinite series of equal payments. While a theoretical concept, it is crucial in finance for valuing assets with indefinite cash flows, such as preferred stocks or certain types of real estate.',
    slug: 'perpetuity-calculator',
    category: 'finance',
  },
  {
    id: 163,
    name: 'Growing Annuity/Perpetuity Calculator',
    description: 'Value a stream of cash flows that is expected to grow at a constant rate, either for a finite number of periods (annuity) or indefinitely (perpetuity). This is useful for valuing dividend-paying stocks or rental income that is projected to increase over time.',
    slug: 'growing-annuity-calculator',
    category: 'finance',
  },
  {
    id: 164,
    name: 'Internal Rate of Return (IRR) Calculator',
    description: 'Find the discount rate that makes the Net Present Value (NPV) of all cash flows from a particular project equal to zero. IRR is a key metric for capital budgeting to determine the profitability of potential investments.',
    slug: 'irr-calculator',
    category: 'finance',
  },
  {
    id: 165,
    name: 'Net Present Value (NPV) Calculator',
    description: 'Determine the difference between the present value of cash inflows and the present value of cash outflows over a period of time. A positive NPV indicates a profitable investment, making it a critical tool for capital budgeting.',
    slug: 'npv-calculator',
    category: 'finance',
  },
  {
    id: 166,
    name: 'Discount Rate Calculator',
    description: 'Estimate the required rate of return for an investment using the Capital Asset Pricing Model (CAPM). This helps in assessing the risk and potential return of an asset compared to the overall market.',
    slug: 'discount-rate-calculator',
    category: 'finance'
  },
  {
    id: 167,
    name: 'Discounted Cash Flow (DCF) Calculator',
    description: 'Estimate the intrinsic value of an investment or a company based on its expected future cash flows. DCF analysis helps you determine if an asset is undervalued or overvalued in the current market.',
    slug: 'dcf-calculator',
    category: 'finance',
  },
  {
    id: 168,
    name: 'Payback Period Calculator',
    description: 'Determine the length of time required for an investment to generate cash flows sufficient to recover its initial cost. This is a simple way to assess the risk and liquidity of a project.',
    slug: 'payback-period-calculator',
    category: 'finance',
  },
  {
    id: 169,
    name: 'Price-to-Earnings (P/E) Ratio Calculator',
    description: 'Calculate the P/E ratio to gauge a company\'s valuation, indicating how much investors are willing to pay per dollar of earnings. A key metric for value investing.',
    slug: 'price-to-earnings-ratio-calculator',
    category: 'finance'
  },
  {
    id: 170,
    name: 'Earnings per Share (EPS) Calculator',
    description: 'Determine a company\'s profitability on a per-share basis. EPS is a fundamental metric used in calculating the P/E ratio and assessing a company\'s financial health.',
    slug: 'earnings-per-share-calculator',
    category: 'finance'
  },
  {
    id: 171,
    name: 'Return on Equity (ROE) Calculator',
    description: 'Measure how effectively a company is using its shareholders\' equity to generate profits. A high ROE can indicate strong management efficiency and profitability.',
    slug: 'return-on-equity-calculator',
    category: 'finance'
  },
  {
    id: 172,
    name: 'Return on Assets (ROA) Calculator',
    description: 'Evaluate how efficiently a company is using its total assets to generate earnings. ROA provides insight into a company\'s operational performance and asset management.',
    slug: 'return-on-assets-calculator',
    category: 'finance'
  },
  {
    id: 173,
    name: 'Return on Investment (ROI) Calculator',
    description: 'Calculate the percentage return on an investment relative to its cost. ROI is a universal metric for evaluating the profitability of any investment.',
    slug: 'return-on-investment-calculator',
    category: 'finance'
  },
  {
    id: 174,
    name: 'Debt-to-Equity Ratio Calculator',
    description: 'Measures a company’s financial leverage by comparing its total liabilities to its shareholders\' equity. A higher ratio indicates more debt financing, which can mean higher risk but also potentially higher returns.',
    slug: 'debt-to-equity-ratio-calculator',
    category: 'finance'
  },
  {
    id: 175,
    name: 'Interest Coverage Ratio Calculator',
    description: 'Shows how easily a company can pay the interest on its outstanding debt. A higher ratio indicates a better ability to meet its interest obligations, signaling lower risk to creditors and investors.',
    slug: 'interest-coverage-ratio-calculator',
    category: 'finance'
  },
  {
    id: 176,
    name: 'Current Ratio Calculator',
    description: 'Evaluates a company’s short-term liquidity by comparing all of its current assets to its current liabilities. It indicates a company\'s ability to pay back its short-term obligations.',
    slug: 'current-ratio-calculator',
    category: 'finance'
  },
  {
    id: 177,
    name: 'Quick Ratio (Acid-Test) Calculator',
    description: 'Measures a company’s ability to meet its short-term obligations with its most liquid assets, excluding less liquid inventory. It provides a more conservative measure of liquidity than the current ratio.',
    slug: 'quick-ratio-calculator',
    category: 'finance'
  },
  {
    id: 178,
    name: 'Working Capital Calculator',
    description: 'Indicates the liquidity available to a business to meet its short-term obligations. Positive working capital means you have enough assets to cover liabilities, while negative working capital can be a sign of financial trouble.',
    slug: 'working-capital-calculator',
    category: 'finance'
  },
  {
    id: 179,
    name: 'Cash Conversion Cycle (CCC) Calculator',
    description: 'Measures the time it takes for a company to convert its investments in inventory and other resources into cash from sales, indicating working capital efficiency.',
    slug: 'cash-conversion-cycle-calculator',
    category: 'finance',
  },
  {
    id: 180,
    name: 'Free Cash Flow (FCF) Calculator',
    description: 'Calculates the cash a company generates after accounting for capital expenditures, showing the cash available for distribution to investors or to reinvest.',
    slug: 'free-cash-flow-calculator',
    category: 'finance',
  },
  {
    id: 181,
    name: 'Operating Margin Calculator',
    description: 'Determines the profitability of a company\'s core business operations before deducting interest and taxes, expressed as a percentage of revenue.',
    slug: 'operating-margin-calculator',
    category: 'finance',
  },
  {
    id: 182,
    name: 'Gross Margin Calculator',
    description: 'Calculates the percentage of revenue that exceeds the cost of goods sold (COGS), providing insight into a company\'s production efficiency.',
    slug: 'gross-margin-calculator',
    category: 'finance',
  },
  {
    id: 183,
    name: 'Net Profit Margin Calculator',
    description: 'Measures how much net income is generated as a percentage of revenue. It is the ratio of net profits to revenues for a company or business segment.',
    slug: 'net-profit-margin-calculator',
    category: 'finance',
  },
  {
    id: 184,
    name: 'EBITDA / EBIT Calculator',
    description: 'Measure a company’s earnings before interest, taxes, depreciation, and amortization (EBITDA) or before only interest and taxes (EBIT).',
    slug: 'ebitda-ebit-calculator',
    category: 'finance',
  },
  {
    id: 185,
    name: 'Enterprise Value (EV) Calculator',
    description: 'Represents the total value of a company, including debt and cash, often used in valuation.',
    slug: 'enterprise-value-calculator',
    category: 'finance',
  },
  {
    id: 186,
    name: 'EV / EBIT and EV / EBITDA Multiple Calculator',
    description: 'Key valuation multiples comparing Enterprise Value (EV) to EBIT or EBITDA.',
    slug: 'ev-ebit-ebitda-multiple-calculator',
    category: 'finance',
  },
  {
    id: 188,
    name: 'Sharpe Ratio Calculator',
    description: 'Evaluates risk-adjusted return of an investment.',
    slug: 'sharpe-ratio-calculator',
    category: 'finance',
  },
  {
    id: 189,
    name: 'Sortino Ratio Calculator',
    description: 'Similar to Sharpe ratio but penalizes only downside risk.',
    slug: 'sortino-ratio-calculator',
    category: 'finance',
  },
  {
    id: 190,
    name: 'Treynor Ratio Calculator',
    description: 'Measures risk-adjusted return based on systematic risk (beta).',
    slug: 'treynor-ratio-calculator',
    category: 'finance',
  },
  {
    id: 191,
    name: 'Alpha (Investment) Calculator',
    description: 'Indicates the excess return of an investment relative to its expected performance based on market risk.',
    slug: 'alpha-investment-calculator',
    category: 'finance',
  },
  {
    id: 192,
    name: 'Volatility / Standard Deviation Calculator',
    description: 'Measures the dispersion of returns around the mean.',
    slug: 'volatility-standard-deviation-calculator',
    category: 'finance',
  },
  {
    id: 193,
    name: 'Correlation Coefficient Calculator',
    description: 'Measures the strength and direction of relationship between two assets’ returns.',
    slug: 'correlation-coefficient-calculator',
    category: 'finance',
  },
  {
    id: 194,
    name: 'Beta (Asset) Calculator',
    description: 'Measures an asset’s volatility relative to the market (systematic risk).',
    slug: 'beta-asset-calculator',
    category: 'finance',
  },
  {
    id: 195,
    name: 'Portfolio Variance / Risk Calculator',
    description: 'Measures the overall risk (variance) of a multi-asset portfolio.',
    slug: 'portfolio-variance-calculator',
    category: 'finance',
  },
  {
    id: 196,
    name: 'Portfolio Expected Return Calculator',
    description: 'Estimates the weighted average expected return of a portfolio.',
    slug: 'portfolio-expected-return-calculator',
    category: 'finance',
  },
  {
    id: 197,
    name: 'Capital Asset Pricing Model (CAPM) Calculator',
    description: 'Calculates the expected return of an asset using market risk.',
    slug: 'capm-calculator',
    category: 'finance',
  },
  {
    id: 198,
    name: 'WACC Calculator',
    description: 'Computes a firm’s average cost of capital from equity and debt.',
    slug: 'wacc-calculator',
    category: 'finance',
  },
  {
    id: 199,
    name: 'Leverage / Debt Ratio Impact Calculator',
    description: 'Examines how changing debt levels affect a company’s return on equity or earnings per share.',
    slug: 'leverage-debt-ratio-calculator',
    category: 'finance',
  },
  {
    id: 200,
    name: 'Option Pricing – Black-Scholes Calculator',
    description: 'Determines the theoretical value of a European call or put option.',
    slug: 'black-scholes-calculator',
    category: 'finance',
  },
  {
    id: 202,
    name: 'Put / Call Option Payoff Calculator',
    description: 'Shows the profit or loss of a call or put at different underlying prices at expiration.',
    slug: 'option-payoff-calculator',
    category: 'finance',
  },
  {
    id: 203,
    name: 'Binomial Option Pricing Model Calculator',
    description: 'Prices options using a multi-period binomial tree.',
    slug: 'binomial-option-pricing-calculator',
    category: 'finance',
  },
  {
    id: 204,
    name: 'Monte Carlo Simulation for Portfolio Value Calculator',
    description: 'Uses random sampling to estimate the probability distribution of future portfolio values.',
    slug: 'monte-carlo-portfolio-calculator',
    category: 'finance',
  },
  {
    id: 205,
    name: 'Value at Risk (VaR) Calculator',
    description: 'Estimate the maximum potential loss a portfolio could experience over a specific time period.',
    slug: 'value-at-risk-calculator',
    category: 'finance',
  },
  {
    id: 206,
    name: 'Conditional VaR (CVaR) / Expected Shortfall Calculator',
    description: 'Measure the average loss that can be expected if the VaR threshold is breached.',
    slug: 'conditional-value-at-risk-calculator',
    category: 'finance',
  },
  {
    id: 207,
    name: 'Bond Yield to Maturity (YTM) Calculator',
    description: 'Calculate the total annualized rate of return an investor will earn if they hold a bond to maturity.',
    slug: 'bond-yield-to-maturity-calculator',
    category: 'finance',
  },
  {
    id: 208,
    name: 'Bond Price Calculator',
    description: 'Calculate the fair market price of a bond based on its characteristics and current market yield.',
    slug: 'bond-price-calculator',
    category: 'finance',
  },
  {
    id: 209,
    name: 'Bond Duration Calculator',
    description: 'Measure a bond\'s price sensitivity to changes in interest rates.',
    slug: 'bond-duration-calculator',
    category: 'finance',
  },
  {
    id: 210,
    name: 'Bond Convexity Calculator',
    description: 'Measure the curvature in the relationship between a bond\'s price and its yield for a more accurate risk estimate.',
    slug: 'bond-convexity-calculator',
    category: 'finance',
  },
  {
    id: 211,
    name: 'Bond Yield Spread Calculator',
    description: 'Measure the difference in yield between two bonds, often to quantify credit risk.',
    slug: 'bond-yield-spread-calculator',
    category: 'finance',
  },
  {
    id: 212,
    name: 'Yield to Call (YTC) / Yield to Worst (YTW) Calculator',
    description: 'Calculate the yield of a callable bond assuming it is redeemed early.',
    slug: 'yield-to-call-calculator',
    category: 'finance',
  },
  {
    id: 213,
    name: 'Zero-Coupon Bond Valuation Calculator',
    description: 'Determine the fair price of a bond that does not pay periodic interest.',
    slug: 'zero-coupon-bond-valuation-calculator',
    category: 'finance',
  },
  {
    id: 214,
    name: 'Simple Inflation-Adjusted Return Calculator',
    description: 'Quickly estimate an investment\'s return after accounting for inflation.',
    slug: 'simple-inflation-adjusted-return-calculator',
    category: 'finance',
  },
  {
    id: 215,
    name: 'Real Rate of Return Calculator',
    description: 'Precisely calculate an investment\'s return after accounting for inflation using the Fisher Equation.',
    slug: 'real-rate-of-return-calculator',
    category: 'finance',
  },
  {
    id: 220,
    name: 'Margin of Safety Calculator',
    description: 'Determine the cushion between a company\'s current sales and its break-even point.',
    slug: 'margin-of-safety-calculator',
    category: 'finance',
  },
  {
    id: 221,
    name: 'Overhead Rate Allocation Calculator',
    description: 'Establish a rate to apply indirect manufacturing costs to products.',
    slug: 'overhead-rate-allocation-calculator',
    category: 'finance',
  },
  {
    id: 222,
    name: 'Activity-Based Costing (ABC) Calculator',
    description: 'Allocate overhead costs more accurately based on specific activities.',
    slug: 'activity-based-costing-calculator',
    category: 'finance',
  },
  {
    id: 223,
    name: 'Depreciation (Straight-Line) Calculator',
    description: 'Calculate asset depreciation evenly over its useful life.',
    slug: 'depreciation-straight-line-calculator',
    category: 'finance',
  },
  {
    id: 224,
    name: 'Depreciation (Double Declining) Calculator',
    description: 'Calculate accelerated depreciation for an asset.',
    slug: 'depreciation-double-declining-calculator',
    category: 'finance',
  },
  {
    id: 225,
    name: 'Depreciation (Sum-of-Years) Calculator',
    description: 'Calculate accelerated depreciation using the Sum-of-the-Years-Digits method.',
    slug: 'depreciation-sum-of-years-digits-calculator',
    category: 'finance',
  },
  {
    id: 226,
    name: 'MACRS Depreciation Calculator',
    description: 'Calculate tax-deductible depreciation for US tax purposes.',
    slug: 'macrs-depreciation-calculator',
    category: 'finance',
  },
  {
    id: 227,
    name: 'Amortization Schedule Generator',
    description: 'Create a detailed payment schedule for any loan.',
    slug: 'amortization-schedule-generator',
    category: 'finance',
  },
  {
    id: 228,
    name: 'Capital Expenditure (CapEx) Payback Calculator',
    description: 'Calculate the time required to recover the initial cost of a project.',
    slug: 'capex-payback-calculator',
    category: 'finance',
  },
  {
    id: 229,
    name: 'Sensitivity Analysis / "What-If" Calculator',
    description: 'Analyze how changing one variable impacts a financial model\'s outcome.',
    slug: 'sensitivity-analysis-what-if-calculator',
    category: 'finance',
  },
  {
    id: 230,
    name: 'Scenario Analysis Calculator',
    description: 'Evaluate a project\'s financial outcome under different scenarios (pessimistic, optimistic, and base case).',
    slug: 'scenario-analysis-calculator',
    category: 'finance',
  },
  {
    id: 231,
    name: 'Currency Exchange Calculator',
    description: 'Convert a monetary amount from one currency to another based on a given exchange rate.',
    slug: 'currency-exchange-calculator',
    category: 'finance',
  },
  {
    id: 232,
    name: 'Currency Volatility Impact Calculator',
    description: 'Quantify the potential gain or loss on a foreign currency holding due to exchange rate fluctuations.',
    slug: 'currency-volatility-calculator',
    category: 'finance',
  },
  {
    id: 233,
    name: 'Fixed vs. Floating Rate Comparison Calculator',
    description: 'Compare the total interest cost of a loan under a fixed rate versus a projected floating rate.',
    slug: 'fixed-vs-floating-rate-calculator',
    category: 'finance',
  },
  {
    id: 235,
    name: 'Swap Spread Calculator',
    description: 'Calculate the difference between a swap rate and a benchmark government bond yield.',
    slug: 'swap-spread-calculator',
    category: 'finance',
  },
  {
    id: 236,
    name: 'Forward Rate Agreement (FRA) Calculator',
    description: 'Calculate the settlement payment for a Forward Rate Agreement.',
    slug: 'forward-rate-agreement-calculator',
    category: 'finance',
  },
  {
    id: 237,
    name: 'Breakeven Inflation Rate Calculator',
    description: 'Derive the market\'s inflation expectation from bond yields.',
    slug: 'breakeven-inflation-rate-calculator',
    category: 'finance',
  },
  {
    id: 238,
    name: 'Credit Default Swap (CDS) Premium Calculator',
    description: 'Conceptually illustrate how a CDS premium is determined.',
    slug: 'credit-default-swap-calculator',
    category: 'finance',
  },
  {
    id: 239,
    name: 'Synthetic Position / Arbitrage Calculator',
    description: 'Check for arbitrage opportunities using Put-Call Parity.',
    slug: 'put-call-parity-calculator',
    category: 'finance',
  },
  // Business & Startup
  {
    id: 216,
    name: 'Debt Service Coverage Ratio (DSCR) Calculator',
    description: 'Measure a firm\'s available cash flow to pay its current debt obligations.',
    slug: 'dscr-calculator',
    category: 'business-startup',
  },
  {
    id: 217,
    name: 'Break-Even Sales Dollar Amount Calculator',
    description: 'Calculate the sales revenue needed to cover all fixed and variable costs.',
    slug: 'break-even-sales-dollar-calculator',
    category: 'business-startup',
  },
  {
    id: 218,
    name: 'Contribution Margin per Unit Calculator',
    description: 'Determine the revenue from one unit sold that is left over after covering the variable costs associated with that unit.',
    slug: 'contribution-margin-calculator',
    category: 'business-startup',
  },
  {
    id: 219,
    name: 'Operating Leverage Calculator',
    description: 'Measure how a company\'s operating income changes in response to a change in sales.',
    slug: 'operating-leverage-calculator',
    category: 'business-startup',
  },
  {
    id: 126,
    name: 'Break-Even Point Calculator',
    description: 'Find the sales volume required to cover all fixed and variable costs.',
    slug: 'break-even-point-calculator',
    category: 'business-startup',
  },
  {
    id: 127,
    name: 'Customer Acquisition Cost (CAC) Calculator',
    description: 'Measure the cost of acquiring one paying customer.',
    slug: 'customer-acquisition-cost-calculator',
    category: 'business-startup',
  },
  {
    id: 128,
    name: 'Lifetime Value (LTV) Calculator',
    description: 'Estimate the total revenue a single customer generates for your business.',
    slug: 'lifetime-value-calculator',
    category: 'business-startup',
  },
  {
    id: 129,
    name: 'Burn Rate Calculator',
    description: 'Track how quickly a startup is using its available cash.',
    slug: 'burn-rate-calculator',
    category: 'business-startup',
  },
  {
    id: 130,
    name: 'ROI Calculator',
    description: 'Measure profitability of a business investment.',
    slug: 'roi-calculator',
    category: 'business-startup',
  },
  // Health & Fitness
  {
    id: 107,
    name: 'Water Footprint of Food Calculator',
    description: 'Estimate the total volume of water required to produce different food items. Understand the hidden water usage in your diet.',
    slug: 'water-footprint-of-food-calculator',
    category: 'health-fitness'
  },
   {
    id: 108,
    name: 'Body Mass Index (BMI) Calculator',
    description: 'Quickly assess whether you are underweight, healthy, overweight, or obese using this standard health indicator.',
    slug: 'bmi-calculator',
    category: 'health-fitness'
  },
  {
    id: 109,
    name: 'Basal Metabolic Rate (BMR) Calculator',
    description: 'Estimate the number of calories your body burns at rest per day. A crucial metric for creating a weight management plan.',
    slug: 'bmr-calculator',
    category: 'health-fitness'
  },
  {
    id: 110,
    name: 'Target Heart Rate Calculator',
    description: 'Determine your optimal heart rate zone for moderate and vigorous exercise to maximize the effectiveness of your workouts.',
    slug: 'target-heart-rate-calculator',
    category: 'health-fitness'
  },
  { id: 250, name: 'Body Fat Percentage Calculator', description: 'Estimate your body fat percentage using the U.S. Navy method.', slug: 'body-fat-percentage-calculator', category: 'health-fitness' },
  { id: 251, name: 'Lean Body Mass Calculator', description: 'Calculate the weight of your body minus all fat mass.', slug: 'lean-body-mass-calculator', category: 'health-fitness' },
  { id: 252, name: 'Ideal Body Weight (IBW) Calculator', description: 'Estimate a healthy weight range based on your height and sex.', slug: 'ideal-body-weight-calculator', category: 'health-fitness' },
  { id: 253, name: 'Waist-to-Hip Ratio Calculator', description: 'Assess health risks associated with abdominal fat.', slug: 'waist-to-hip-ratio-calculator', category: 'health-fitness' },
  { id: 254, name: 'Waist-to-Height Ratio Calculator', description: 'A simple indicator of central obesity and health risk.', slug: 'waist-to-height-ratio-calculator', category: 'health-fitness' },
  { id: 255, name: 'Body Adiposity Index (BAI) Calculator', description: 'Estimate body fat using hip circumference and height.', slug: 'body-adiposity-index-calculator', category: 'health-fitness' },
  { id: 256, name: 'Ponderal Index Calculator', description: 'A measure of leanness, similar to BMI, for very tall or short individuals.', slug: 'ponderal-index-calculator', category: 'health-fitness' },
  { id: 257, name: 'Relative Fat Mass (RFM) Calculator', description: 'Estimate body fat percentage using only height and waist circumference.', slug: 'relative-fat-mass-calculator', category: 'health-fitness' },
  { id: 258, name: 'Calorie Deficit Calculator', description: 'Calculate daily calorie intake for sustainable weight loss.', slug: 'calorie-deficit-calculator', category: 'health-fitness' },
  { id: 259, name: 'Calorie Surplus Calculator', description: 'Calculate daily calorie intake for muscle and weight gain.', slug: 'calorie-surplus-calculator', category: 'health-fitness' },
  // Home Improvement
  {
    id: 1,
    name: 'Paint Coverage Calculator',
    description: 'Calculates amount of paint needed for a project.',
    slug: 'paint-coverage-calculator',
    category: 'home-improvement',
  },
  {
    id: 2,
    name: 'Tile & Flooring Calculator',
    description: 'Number of tiles or square metres/feet of flooring material needed, including a % for wastage.',
    slug: 'tile-flooring-calculator',
    category: 'home-improvement',
  },
  {
    id: 3,
    name: 'Wallpaper Roll Calculator',
    description: 'Rolls of wallpaper required based on wall area and pattern repeat.',
    slug: 'wallpaper-roll-calculator',
    category: 'home-improvement',
  },
  {
    id: 4,
    name: 'Drywall/Plasterboard Calculator',
    description: 'Number of drywall sheets and joint compound needed for a room.',
    slug: 'drywall-plasterboard-calculator',
    category: 'home-improvement',
  },
  {
    id: 5,
    name: 'Insulation R-Value Calculator',
    description: 'Recommended insulation thickness and material type for a target R-value.',
    slug: 'insulation-r-value-calculator',
    category: 'home-improvement',
  },
  {
    id: 6,
    name: 'Decking Materials Calculator',
    description: 'Boards, fasteners, and joists needed for a deck of specific size.',
    slug: 'decking-materials-calculator',
    category: 'home-improvement',
  },
  {
    id: 7,
    name: 'Roofing Shingle Calculator',
    description: 'Bundles of shingles and underlayment required for a roof area with pitch adjustment.',
    slug: 'roofing-shingle-calculator',
    category: 'home-improvement',
  },
  {
    id: 8,
    name: 'Concrete Volume Calculator',
    description: 'Cubic metres/feet of concrete required for a slab, footing, or driveway.',
    slug: 'concrete-volume-calculator',
    category: 'home-improvement',
  },
  {
    id: 10,
    name: 'Lighting Layout Calculator',
    description: 'Number and placement of light fixtures needed to achieve a target lux/foot-candle level.',
    slug: 'lighting-layout-calculator',
    category: 'home-improvement',
  },
  {
    id: 11,
    name: 'HVAC Sizing Calculator',
    description: 'Approximate BTU or tonnage of heating/cooling system needed for a room/house size.',
    slug: 'hvac-sizing-calculator',
    category: 'home-improvement',
  },
  {
    id: 12,
    name: 'Staircase Rise & Run Calculator',
    description: 'Number of steps, tread depth, and riser height for a given total height.',
    slug: 'staircase-rise-run-calculator',
    category: 'home-improvement',
  },
  {
    id: 13,
    name: 'Cost Estimator for Renovation',
    description: 'Rough cost breakdown based on square footage and type of work (kitchen, bathroom, etc.).',
    slug: 'cost-estimator-renovation-calculator',
    category: 'home-improvement',
  },
  {
    id: 14,
    name: 'Water Usage / Plumbing Flow Calculator',
    description: 'Expected water flow and pipe size requirements for new fixtures.',
    slug: 'water-usage-plumbing-flow-calculator',
    category: 'home-improvement',
  },
  {
    id: 15,
    name: 'Garden/Landscape Soil & Mulch Calculator',
    description: 'Volume of soil or mulch needed for beds or planters.',
    slug: 'garden-landscape-soil-mulch-calculator',
    category: 'home-improvement',
  },
  // Engineering
  {
    id: 16,
    name: 'Beam Bending Calculator',
    description: 'Calculate bending stress and deflection for beams under load.',
    slug: 'beam-bending-calculator',
    category: 'engineering',
  },
  {
    id: 17,
    name: 'Hydraulic Pipe Flow Calculator',
    description: 'Compute head loss due to friction in a pipe using the Darcy-Weisbach equation.',
    slug: 'hydraulic-pipe-flow-calculator',
    category: 'engineering',
  },
  {
    id: 18,
    name: 'Heat Transfer Calculator',
    description: 'Find steady-state heat transfer rate through a flat wall by conduction.',
    slug: 'heat-transfer-calculator',
    category: 'engineering',
  },
  {
    id: 19,
    name: 'Electrical Power Calculator (3-Phase)',
    description: 'Calculate total real power in a balanced 3-phase electrical system.',
    slug: 'electrical-power-calculator',
    category: 'engineering',
  },
  {
    id: 20,
    name: 'Compressive Stress Calculator',
    description: 'Calculate stress when a compressive load is applied to a material.',
    slug: 'compressive-stress-calculator',
    category: 'engineering',
  },
  {
    id: 21,
    name: 'Cantilever Beam Deflection Calculator',
    description: 'Determine the vertical deflection at the free end of a cantilever beam.',
    slug: 'cantilever-beam-deflection-calculator',
    category: 'engineering',
  },
  {
    id: 22,
    name: 'Natural Frequency Calculator',
    description: 'Calculate the natural frequency of a simple spring-mass system.',
    slug: 'natural-frequency-calculator',
    category: 'engineering',
  },
  {
    id: 23,
    name: 'Reynolds Number Calculator',
    description: 'Determine whether a fluid flow is laminar, transitional, or turbulent.',
    slug: 'reynolds-number-calculator',
    category: 'engineering',
  },
  {
    id: 24,
    name: 'Thermal Expansion Calculator',
    description: 'Compute the change in length of a material due to temperature change.',
    slug: 'thermal-expansion-calculator',
    category: 'engineering',
  },
  {
    id: 25,
    name: 'Shear Stress in a Shaft Calculator',
    description: 'Calculate maximum shear stress in a circular shaft subjected to torsion.',
    slug: 'shear-stress-calculator',
    category: 'engineering',
  },
   // Biology
  { id: 151, name: 'Annealing Temperature (Tm) Calculator', description: 'Estimate the optimal annealing temperature for PCR primers.', slug: 'annealing-temperature-calculator', category: 'biology' },
  { id: 152, name: 'Generation Time Calculator', description: 'Calculate the time required for a cell population to double.', slug: 'generation-time-calculator', category: 'biology' },
  { id: 153, name: 'Cell Dilution Calculator', description: 'Determine the volume needed to dilute a cell culture to a desired concentration.', slug: 'cell-dilution-calculator', category: 'biology' },
  { id: 154, name: 'Cell Doubling Time Calculator', description: 'Calculate the time it takes for a cell population to double in number.', slug: 'cell-doubling-time-calculator', category: 'biology' },
  { id: 155, name: 'DNA Concentration Calculator', description: 'Estimate DNA concentration from spectrophotometer (A260) readings.', slug: 'dna-concentration-calculator', category: 'biology' },
  { id: 156, name: 'Ligation Calculator', description: 'Calculate the required amount of insert for a vector ligation.', slug: 'ligation-calculator', category: 'biology' },
  { id: 157, name: 'Log Reduction Calculator', description: 'Determine the magnitude of microbial reduction after a disinfectant process.', slug: 'log-reduction-calculator', category: 'biology' },
  { id: 158, name: 'Protein Concentration (A280) Calculator', description: 'Estimate protein concentration using absorbance at 280nm.', slug: 'protein-concentration-calculator', category: 'biology' },
  // Cognitive & Psychology
  {
    id: 31,
    name: 'IQ Score Estimator',
    description: 'Estimate IQ based on standardized test scores.',
    slug: 'iq-score-estimator',
    category: 'cognitive-psychology',
  },
  {
    id: 32,
    name: 'Memory Span Calculator',
    description: 'Measure short-term memory capacity.',
    slug: 'memory-span-calculator',
    category: 'cognitive-psychology',
  },
  {
    id: 33,
    name: 'Cognitive Load Calculator',
    description: 'Estimate mental effort for a task.',
    slug: 'cognitive-load-calculator',
    category: 'cognitive-psychology',
  },
  {
    id: 34,
    name: 'Personality Trait Calculator (Big 5)',
    description: 'Estimate 5 personality traits based on a simple self-report scale.',
    slug: 'personality-trait-calculator',
    category: 'cognitive-psychology',
  },
  {
    id: 111,
    name: 'Stroop Effect Reaction-Time Calculator',
    description: 'Measure cognitive interference and selective attention by comparing reaction times.',
    slug: 'stroop-effect-reaction-time-calculator',
    category: 'cognitive-psychology',
  },
  {
    id: 112,
    name: 'Mental Fatigue Index Calculator',
    description: 'Estimate the rate of mental fatigue after performing a cognitive task.',
    slug: 'mental-fatigue-index-calculator',
    category: 'cognitive-psychology',
  },
  {
    id: 115,
    name: 'Sleep Debt Calculator',
    description: 'Determine your weekly sleep debt and its potential impact on cognitive performance.',
    slug: 'sleep-debt-calculator',
    category: 'cognitive-psychology',
  },
  {
    id: 116,
    name: 'Stress Level Index (PSS) Calculator',
    description: 'Score your perceived stress level over the past month using the Perceived Stress Scale.',
    slug: 'stress-level-index-calculator',
    category: 'cognitive-psychology',
  },
  // Genetic & Ancestry
  {
    id: 35,
    name: 'Ancestry Composition Estimator',
    description: 'A simplified tool to estimate ethnic background percentages for entertainment.',
    slug: 'ancestry-composition-estimator',
    category: 'genetic-ancestry',
  },
  {
    id: 36,
    name: 'Genetic Trait Probability Calculator',
    description: 'Predict likelihood of inheriting specific traits using Punnett squares.',
    slug: 'genetic-trait-probability-calculator',
    category: 'genetic-ancestry',
  },
  {
    id: 37,
    name: 'Pedigree Analysis Calculator',
    description: 'Assess simple genetic relationships and inheritance patterns within family trees.',
    slug: 'pedigree-analysis-calculator',
    category: 'genetic-ancestry',
  },
  {
    id: 38,
    name: 'Genealogy Timeline Generator',
    description: 'Visualize an estimated ancestral lineage and key dates over time.',
    slug: 'genealogy-timeline-generator',
    category: 'genetic-ancestry',
  },
  // Environment
  {
    id: 39,
    name: 'Carbon Footprint Calculator',
    description: 'Estimate your annual carbon footprint based on your lifestyle.',
    slug: 'carbon-footprint-reduction-calculator',
    category: 'environment',
  },
  {
    id: 40,
    name: 'Water Usage Efficiency Calculator',
    description: 'Estimates water consumption and potential savings in your household.',
    slug: 'water-usage-efficiency-calculator',
    category: 'environment',
  },
  {
    id: 41,
    name: 'Recycling Impact Calculator',
    description: 'Quantify the environmental benefits of your recycling efforts.',
    slug: 'recycling-impact-calculator',
    category: 'environment',
  },
  {
    id: 42,
    name: 'Sustainable Diet Impact Calculator',
    description: 'Analyzes the water footprint of different dietary choices.',
    slug: 'sustainable-diet-impact-calculator',
    category: 'environment',
  },
  // Travel & Adventure
  {
    id: 51,
    name: 'Backpacking Load Weight Calculator',
    description: 'Assesses optimal backpack weight for treks.',
    slug: 'backpacking-load-weight-calculator',
    category: 'travel-adventure',
  },
  {
    id: 52,
    name: 'Hiking Elevation Gain Calculator',
    description: 'Estimates elevation changes during hikes.',
    slug: 'hiking-elevation-gain-calculator',
    category: 'travel-adventure',
  },
  {
    id: 53,
    name: 'Travel Budget Estimator',
    description: 'Calculates expected expenses for trips.',
    slug: 'travel-budget-estimator',
    category: 'travel-adventure',
  },
  {
    id: 54,
    name: 'Adventure Activity Risk Calculator',
    description: 'Assesses risk levels of various adventure sports.',
    slug: 'adventure-activity-risk-calculator',
    category: 'travel-adventure',
  },
  // Technology
  {
    id: 55,
    name: 'Battery Life Estimator',
    description: 'Predict device runtime from mAh capacity and average power draw.',
    slug: 'battery-life-estimator',
    category: 'technology',
  },
  {
    id: 56,
    name: 'Power Supply Wattage Calculator',
    description: 'Suggest PSU size based on PC components.',
    slug: 'power-supply-wattage-calculator',
    category: 'technology',
  },
  {
    id: 57,
    name: 'Overclocking Thermal Calculator',
    description: 'Estimate CPU/GPU temps from voltage & frequency changes.',
    slug: 'overclocking-thermal-calculator',
    category: 'technology',
  },
  {
    id: 58,
    name: 'Network Bandwidth Calculator',
    description: 'Work out required bandwidth for a given number of users or video streams.',
    slug: 'network-bandwidth-calculator',
    category: 'technology',
  },
  {
    id: 59,
    name: 'Ping / Latency Distance Calculator',
    description: 'Approximate physical distance from ping time.',
    slug: 'ping-latency-distance-calculator',
    category: 'technology',
  },
  {
    id: 60,
    name: 'UPS Runtime Calculator',
    description: 'Estimate backup time for servers or home setups.',
    slug: 'ups-runtime-calculator',
    category: 'technology',
  },
  {
    id: 61,
    name: 'Internet Data Usage Estimator',
    description: 'Predict monthly usage from hours of streaming/gaming.',
    slug: 'internet-data-usage-estimator',
    category: 'technology',
  },
  {
    id: 62,
    name: 'Disk RAID Capacity Calculator',
    description: 'Calculate usable storage and redundancy for RAID levels.',
    slug: 'disk-raid-capacity-calculator',
    category: 'technology',
  },
  {
    id: 64,
    name: 'API Rate Limit Planner',
    description: 'Calculate calls per second/minute based on quota.',
    slug: 'api-rate-limit-planner',
    category: 'technology',
  },
  {
    id: 65,
    name: 'Regex Performance Checker',
    description: 'Estimate time complexity for given regex patterns.',
    slug: 'regex-performance-checker',
    category: 'technology',
  },
  {
    id: 66,
    name: 'Image Compression Size Calculator',
    description: 'Predict final file size for given compression ratio & resolution.',
    slug: 'image-compression-size-calculator',
    category: 'technology',
  },
  {
    id: 67,
    name: 'Password Entropy Calculator',
    description: 'Measure strength of a password by bits of entropy.',
    slug: 'password-entropy-calculator',
    category: 'technology',
  },
  {
    id: 68,
    name: 'Hash Collision Probability Calculator',
    description: 'Estimate chance of collisions for given hash length & number of items.',
    slug: 'hash-collision-probability-calculator',
    category: 'technology',
  },
  {
    id: 69,
    name: 'Cloud Cost Estimator',
    description: 'Rough monthly spend for compute/storage/bandwidth.',
    slug: 'cloud-cost-estimator',
    category: 'technology',
  },
  {
    id: 70,
    name: 'Subnet Mask / CIDR Calculator',
    description: 'Find IP ranges, hosts, and broadcast addresses.',
    slug: 'subnet-mask-cidr-calculator',
    category: 'technology',
  },
  {
    id: 71,
    name: 'Download Time Calculator',
    description: 'Time to download a file based on size and speed.',
    slug: 'download-time-calculator',
    category: 'technology',
  },
  {
    id: 72,
    name: 'Latency-to-Throughput Calculator',
    description: 'Compute max throughput for a given latency (TCP window).',
    slug: 'latency-to-throughput-calculator',
    category: 'technology',
  },
  {
    id: 73,
    name: '3D Print Time & Material Calculator',
    description: 'Estimate filament usage and print time.',
    slug: '3d-print-time-material-calculator',
    category: 'technology',
  },
  {
    id: 74,
    name: 'Solar Panel Output Calculator for Gadgets',
    description: 'Predict daily energy generation for portable solar setups.',
    slug: 'solar-panel-output-calculator',
    category: 'technology',
  },
  // Fun & Games
  {
    id: 75,
    name: 'Dice Roll Probability',
    description: 'Odds of rolling a certain number or combination.',
    slug: 'dice-roll-probability',
    category: 'fun-games',
  },
  {
    id: 76,
    name: 'Board Game Scoring',
    description: 'Track and tally scores for popular games (e.g., Settlers of Catan, Scrabble).',
    slug: 'board-game-scoring',
    category: 'fun-games',
  },
  {
    id: 77,
    name: 'RPG Character Stat',
    description: 'Auto-generate or balance D&D style character stats.',
    slug: 'rpg-character-stat',
    category: 'fun-games',
  },
  {
    id: 78,
    name: 'Esports K/D Ratio',
    description: 'Compute kill/death ratio and needed kills to hit a target K/D.',
    slug: 'esports-kd-ratio',
    category: 'fun-games',
  },
  {
    id: 79,
    name: 'Video Game XP Level-Up',
    description: 'Time or XP needed to reach the next level.',
    slug: 'video-game-xp-level-up',
    category: 'fun-games',
  },
  {
    id: 80,
    name: 'Movie Marathon Time',
    description: 'Total watch time for a list of movies or TV episodes.',
    slug: 'movie-marathon-time',
    category: 'fun-games',
  },
  {
    id: 81,
    name: 'Book Series Reading Time',
    description: 'How many hours to finish a series at your reading speed.',
    slug: 'book-series-reading-time',
    category: 'fun-games',
  },
  {
    id: 82,
    name: 'Song Playlist Duration',
    description: 'Add up total minutes for a playlist.',
    slug: 'song-playlist-duration',
    category: 'fun-games',
  },
  {
    id: 83,
    name: 'Pop Culture Age',
    description: 'How old a celebrity/character would be today.',
    slug: 'pop-culture-age',
    category: 'fun-games',
  },
  {
    id: 86,
    name: 'Emoji Compatibility',
    description: 'Enter two names, see a playful “compatibility score” with emojis.',
    slug: 'emoji-compatibility',
    category: 'fun-games',
  },
  {
    id: 87,
    name: 'Random Nickname Generator',
    description: 'Rate the “coolness” of a generated nickname.',
    slug: 'random-nickname-generator',
    category: 'fun-games',
  },
  {
    id: 88,
    name: 'Friendship Anniversary',
    description: 'Days since you first met.',
    slug: 'friendship-anniversary',
    category: 'fun-games',
  },
  {
    id: 89,
    name: 'Bowling Score',
    description: 'Tally frames and strikes automatically.',
    slug: 'bowling-score',
    category: 'fun-games',
  },
  {
    id: 90,
    name: 'Golf Handicap',
    description: 'Quick estimate of a player’s handicap.',
    slug: 'golf-handicap',
    category: 'fun-games',
  },
  {
    id: 91,
    name: 'Fantasy League Points',
    description: 'Predict weekly fantasy team points.',
    slug: 'fantasy-league-points',
    category: 'fun-games',
  },
  {
    id: 92,
    name: 'Party Budget Per Person',
    description: 'Split cost of food, drinks, decorations.',
    slug: 'party-budget-per-person',
    category: 'fun-games',
  },
  {
    id: 93,
    name: 'BBQ Food & Drink Quantity',
    description: 'Estimate servings needed for a given crowd.',
    slug: 'bbq-food-drink-quantity',
    category: 'fun-games',
  },
  {
    id: 94,
    name: 'Karaoke Queue Time',
    description: 'How long until it’s your turn based on song lengths.',
    slug: 'karaoke-queue-time',
    category: 'fun-games',
  },
  // Cooking & Food
  {
    id: 117,
    name: 'Recipe Ingredient Converter',
    description: 'Scale recipe ingredient quantities up or down for different serving sizes.',
    slug: 'recipe-ingredient-converter',
    category: 'cooking-food',
  },
  {
    id: 118,
    name: 'Cooking Time Adjuster',
    description: 'Estimate new cooking time when you change the oven temperature.',
    slug: 'cooking-time-adjuster',
    category: 'cooking-food',
  },
  {
    id: 120,
    name: 'Brining Solution Calculator',
    description: 'Calculate correct salt and sugar ratio for brines to ensure perfect flavor and texture.',
    slug: 'brining-solution-calculator',
    category: 'cooking-food',
  },
  {
    id: 121,
    name: 'Meat Thawing Time Calculator',
    description: 'Estimate safe refrigerator thawing time for frozen meat based on weight.',
    slug: 'meat-thawing-time-calculator',
    category: 'cooking-food',
  },
  // Personal Budgeting
  {
    id: 122,
    name: '50/30/20 Budget Calculator',
    description: 'Split income into needs, wants, and savings using the popular 50/30/20 rule.',
    slug: '50-30-20-budget-calculator',
    category: 'personal-budgeting',
  },
  {
    id: 123,
    name: 'Monthly Budget Surplus/Deficit Calculator',
    description: 'Determine if you are living within your means by comparing income and expenses.',
    slug: 'monthly-budget-surplus-deficit-calculator',
    category: 'personal-budgeting',
  },
  {
    id: 124,
    name: 'Debt-to-Income (DTI) Ratio Calculator',
    description: 'Measure how much of your income goes toward debt payments (important for loan approvals).',
    slug: 'dti-ratio-calculator',
    category: 'personal-budgeting',
  },
  {
    id: 106,
    name: 'Emergency Fund Goal Calculator',
    description: 'Calculate how much cash you should set aside for unexpected expenses.',
    slug: 'emergency-fund-goal-calculator',
    category: 'personal-budgeting',
  },
  {
    id: 125,
    name: 'Savings Rate Calculator',
    description: 'Track the percentage of income you are saving each month.',
    slug: 'savings-rate-calculator',
    category: 'personal-budgeting',
  },
  // Crypto & Web3
  {
    id: 131,
    name: 'Crypto Mining Profitability Calculator',
    description: 'Estimate daily/monthly profit from crypto mining.',
    slug: 'crypto-mining-profitability-calculator',
    category: 'crypto-web3',
  },
  {
    id: 132,
    name: 'Crypto Tax Liability Calculator',
    description: 'Estimate tax owed on crypto capital gains.',
    slug: 'crypto-tax-liability-calculator',
    category: 'crypto-web3',
  },
  {
    id: 133,
    name: 'Crypto Staking Reward Calculator',
    description: 'Calculate total coins earned from staking.',
    slug: 'crypto-staking-reward-calculator',
    category: 'crypto-web3',
  },
  {
    id: 134,
    name: 'NFT Minting Cost Calculator',
    description: 'Estimate total cost to mint an NFT in USD.',
    slug: 'nft-minting-cost-calculator',
    category: 'crypto-web3',
  },
  {
    id: 135,
    name: 'Crypto APY (Yield Farming) Calculator',
    description: 'Calculate final amount after yield farming.',
    slug: 'crypto-apy-calculator',
    category: 'crypto-web3',
  },
  // Parenting
  {
    id: 137,
    name: 'Pregnancy Due Date Calculator',
    description: 'Estimate your baby\'s due date based on your last menstrual period.',
    slug: 'due-date-calculator',
    category: 'parenting',
  },
  {
    id: 138,
    name: 'Baby Feeding Amount Calculator',
    description: 'Calculate the recommended daily milk/formula intake for your baby.',
    slug: 'baby-feeding-amount-calculator',
    category: 'parenting',
  },
  {
    id: 139,
    name: 'College Savings Goal Calculator',
    description: 'Estimate the monthly savings needed to meet future college tuition costs.',
    slug: 'college-savings-goal-calculator',
    category: 'parenting',
  },
  {
    id: 140,
    name: 'Childcare Cost Affordability Calculator',
    description: 'Assess what percentage of your income is spent on childcare.',
    slug: 'childcare-cost-affordability-calculator',
    category: 'parenting',
  },
  // Sports & Training
  {
    id: 141,
    name: 'BMI (Body Mass Index) Calculator',
    description: 'Assess your weight status category (underweight, normal, overweight, obese).',
    slug: 'sports-training-bmi-calculator',
    category: 'sports-training',
  },
  {
    id: 142,
    name: 'Basal Metabolic Rate (BMR) Calculator',
    description: 'Calculate your daily calorie needs for weight management.',
    slug: 'sports-training-bmr-calculator',
    category: 'sports-training',
  },
  {
    id: 143,
    name: 'Target Heart Rate Zone Calculator',
    description: 'Find your ideal heart rate range for fat burn or cardio fitness.',
    slug: 'sports-training-target-heart-rate-calculator',
    category: 'sports-training',
  },
  {
    id: 144,
    name: 'VO₂ Max Estimation Calculator',
    description: 'Estimate your maximal oxygen uptake from a 1.5-mile run time.',
    slug: 'vo2-max-estimation-calculator',
    category: 'sports-training',
  },
  {
    id: 145,
    name: 'One-Rep Max (1RM) Calculator',
    description: 'Estimate the maximum weight you can lift for one repetition.',
    slug: 'one-rep-max-calculator',
    category: 'sports-training',
  },
  // Time & Date
  {
    id: 146,
    name: 'Date Difference Calculator',
    description: 'Find the duration in days, weeks, and months between two dates.',
    slug: 'date-difference-calculator',
    category: 'time-date',
  },
  {
    id: 147,
    name: 'Age Calculator',
    description: 'Calculate a person\'s exact age in years, months, and days from their date of birth.',
    slug: 'age-calculator',
    category: 'time-date',
  },
  {
    id: 148,
    name: 'World Time Zone Converter',
    description: 'Convert the time and date from one city or timezone to another.',
    slug: 'world-time-zone-converter',
    category: 'time-date',
  },
  {
    id: 149,
    name: 'Day of the Week Calculator',
    description: 'Find out the day of the week for any given date in history or the future.',
    slug: 'day-of-the-week-calculator',
    category: 'time-date',
  },
  {
    id: 150,
    name: 'Working Days / Business Days Calculator',
    description: 'Calculate the number of business days between two dates, excluding weekends and public holidays.',
    slug: 'working-days-business-days-calculator',
    category: 'time-date',
  },
];

    