export interface Calculator {
  id: number;
  name: string;
  description: string;
  slug: string;
  category: string;
}

export const calculators: Calculator[] = [
  // Home Improvement
  {
    id: 1,
    name: 'Paint Coverage Calculator',
    description: 'How many litres/gallons of paint are needed for a given room size and number of coats.',
    slug: 'paint-coverage',
    category: 'home-improvement',
  },
  {
    id: 2,
    name: 'Tile & Flooring Calculator',
    description: 'Number of tiles or square metres/feet of flooring material needed, including a % for wastage.',
    slug: 'tile-flooring',
    category: 'home-improvement',
  },
  {
    id: 3,
    name: 'Wallpaper Roll Calculator',
    description: 'Rolls of wallpaper required based on wall area and pattern repeat.',
    slug: 'wallpaper-roll',
    category: 'home-improvement',
  },
  {
    id: 4,
    name: 'Drywall/Plasterboard Calculator',
    description: 'Number of drywall sheets and joint compound needed for a room.',
    slug: 'drywall-plasterboard',
    category: 'home-improvement',
  },
  {
    id: 5,
    name: 'Insulation R-Value Calculator',
    description: 'Recommended insulation thickness and material type for a target R-value.',
    slug: 'insulation-r-value',
    category: 'home-improvement',
  },
  {
    id: 6,
    name: 'Decking Materials Calculator',
    description: 'Boards, fasteners, and joists needed for a deck of specific size.',
    slug: 'decking-materials',
    category: 'home-improvement',
  },
  {
    id: 7,
    name: 'Roofing Shingle Calculator',
    description: 'Bundles of shingles and underlayment required for a roof area with pitch adjustment.',
    slug: 'roofing-shingle',
    category: 'home-improvement',
  },
  {
    id: 8,
    name: 'Concrete Volume Calculator',
    description: 'Cubic metres/feet of concrete required for a slab, footing, or driveway.',
    slug: 'concrete-volume',
    category: 'home-improvement',
  },
  {
    id: 9,
    name: 'Lumber/Framing Calculator',
    description: 'Quantity of studs, plates, and beams for building or remodeling walls.',
    slug: 'lumber-framing',
    category: 'home-improvement',
  },
  {
    id: 10,
    name: 'Lighting Layout Calculator',
    description: 'Number and placement of light fixtures needed to achieve a target lux/foot-candle level.',
    slug: 'lighting-layout',
    category: 'home-improvement',
  },
  {
    id: 11,
    name: 'HVAC Sizing Calculator',
    description: 'Approximate BTU or tonnage of heating/cooling system needed for a room/house size.',
    slug: 'hvac-sizing',
    category: 'home-improvement',
  },
  {
    id: 12,
    name: 'Staircase Rise & Run Calculator',
    description: 'Number of steps, tread depth, and riser height for a given total height.',
    slug: 'staircase-rise-run',
    category: 'home-improvement',
  },
  {
    id: 13,
    name: 'Cost Estimator for Renovation',
    description: 'Rough cost breakdown based on square footage and type of work (kitchen, bathroom, etc.).',
    slug: 'cost-estimator-renovation',
    category: 'home-improvement',
  },
  {
    id: 14,
    name: 'Water Usage / Plumbing Flow Calculator',
    description: 'Expected water flow and pipe size requirements for new fixtures.',
    slug: 'water-usage-plumbing-flow',
    category: 'home-improvement',
  },
  {
    id: 15,
    name: 'Garden/Landscape Soil & Mulch Calculator',
    description: 'Volume of soil or mulch needed for beds or planters.',
    slug: 'garden-landscape-soil-mulch',
    category: 'home-improvement',
  },
  // Engineering
  {
    id: 16,
    name: 'Beam Bending Calculator',
    description: 'Calculate bending stress and deflection for beams under load.',
    slug: 'beam-bending',
    category: 'engineering',
  },
  {
    id: 17,
    name: 'Truss Analysis Calculator',
    description: 'Compute forces in truss members for a given load.',
    slug: 'truss-analysis',
    category: 'engineering',
  },
  {
    id: 18,
    name: 'Pipe Flow Calculator',
    description: 'Flow rate, velocity, and pressure drop in pipes (using Darcy-Weisbach).',
    slug: 'pipe-flow',
    category: 'engineering',
  },
  {
    id: 19,
    name: 'Hydraulic Head Loss Calculator',
    description: 'Determine head loss in pipelines due to friction.',
    slug: 'hydraulic-head-loss',
    category: 'engineering',
  },
  {
    id: 20,
    name: 'Concrete Mix Calculator',
    description: 'Material quantities for specific concrete strength and volume.',
    slug: 'concrete-mix',
    category: 'engineering',
  },
  {
    id: 21,
    name: 'Steel Weight Calculator',
    description: 'Calculate weight of steel bars (rods, beams, sheets) based on dimensions.',
    slug: 'steel-weight',
    category: 'engineering',
  },
  {
    id: 22,
    name: 'Column Buckling Calculator',
    description: 'Predict critical load causing column buckling.',
    slug: 'column-buckling',
    category: 'engineering',
  },
  {
    id: 23,
    name: 'Pump Power Calculator',
    description: 'Determine required pump power based on flow and head.',
    slug: 'pump-power',
    category: 'engineering',
  },
  {
    id: 24,
    name: 'Hydraulic Cylinder Force Calculator',
    description: 'Calculate force output of hydraulic cylinders.',
    slug: 'hydraulic-cylinder-force',
    category: 'engineering',
  },
  {
    id: 25,
    name: 'Pressure Vessel Thickness Calculator',
    description: 'Wall thickness for cylindrical or spherical vessels under pressure.',
    slug: 'pressure-vessel-thickness',
    category: 'engineering',
  },
  {
    id: 26,
    name: 'Slope Stability Calculator',
    description: 'Factor of safety for embankments or slopes.',
    slug: 'slope-stability',
    category: 'engineering',
  },
  {
    id: 27,
    name: 'Moment of Inertia Calculator',
    description: 'Cross-sectional moment of inertia for beams/columns.',
    slug: 'moment-of-inertia',
    category: 'engineering',
  },
  {
    id: 28,
    name: 'Electrical Circuit Calculator',
    description: 'Ohm’s law, voltage, current, resistance, and power for simple circuits.',
    slug: 'electrical-circuit',
    category: 'engineering',
  },
  {
    id: 29,
    name: 'Thermal Expansion Calculator',
    description: 'Expansion/contraction of materials due to temperature change.',
    slug: 'thermal-expansion',
    category: 'engineering',
  },
  {
    id: 30,
    name: 'Gear Ratio & Torque Calculator',
    description: 'Compute gear ratios, output speed, and torque in mechanical systems.',
    slug: 'gear-ratio-torque',
    category: 'engineering',
  },
];
