
export interface Calculator {
  id: number;
  name: string;
  description: string;
  slug: string;
  category: string;
}

export const calculators: Calculator[] = [
  // Finance
  {
    id: 95,
    name: 'SIP Returns Calculator',
    description: 'Project the future value of your Systematic Investment Plan (SIP). See how regular, disciplined investing and the power of compounding can help you reach your financial goals.',
    slug: 'sip-calculator',
    category: 'finance',
  },
  {
    id: 96,
    name: 'Loan/EMI Calculator',
    description: 'Calculate your monthly payment (EMI) for any loan, including mortgages, auto loans, or personal loans. Understand your repayment schedule with a detailed amortization graph.',
    slug: 'loan-emi-calculator',
    category: 'finance',
  },
  {
    id: 97,
    name: 'Retirement Savings Calculator',
    description: 'Plan for your future by estimating your retirement corpus based on current savings, contributions, and expected returns. Find out if you are on track to meet your retirement goals.',
    slug: 'retirement-savings-calculator',
    category: 'finance',
  },
  {
    id: 98,
    name: 'Compound Interest Calculator',
    description: 'Calculate the future value of an investment using the power of compound interest. Visualize how your savings can grow over time with different compounding frequencies.',
    slug: 'compound-interest-calculator',
    category: 'finance'
  },
  {
    id: 99,
    name: '401(k) Contribution Calculator',
    description: 'Estimate your 401(k) growth by retirement, including your contributions, employer match, and investment returns. Visualize your path to a secure retirement.',
    slug: '401k-contribution-calculator',
    category: 'finance',
  },
  {
    id: 100,
    name: 'Net Worth Calculator',
    description: 'Get a clear picture of your financial health by calculating your net worth. Track your assets and liabilities to understand your overall wealth and financial progress.',
    slug: 'net-worth-calculator',
    category: 'finance',
  },
  {
    id: 101,
    name: 'Credit Card Payoff Calculator',
    description: 'Find out how long it will take to pay off your credit card balance based on your monthly payment. See the total interest you\'ll pay and get a plan to become debt-free.',
    slug: 'credit-card-payoff-calculator',
    category: 'finance',
  },
  {
    id: 102,
    name: 'Mortgage Payment Calculator',
    description: 'Estimate your monthly mortgage payment. See how principal, interest, and loan term affect your payment and view a detailed amortization schedule.',
    slug: 'mortgage-payment-calculator',
    category: 'finance',
  },
  {
    id: 103,
    name: 'Student Loan Repayment Calculator',
    description: 'Understand your student loan repayment options. Calculate your monthly payment and the total interest you\'ll pay over the life of the loan.',
    slug: 'student-loan-repayment-calculator',
    category: 'finance',
  },
  {
    id: 104,
    name: 'Inflation Calculator',
    description: 'See how the value of your money may decrease over time due to inflation. Understand the future purchasing power of your savings.',
    slug: 'inflation-calculator',
    category: 'finance',
  },
  {
    id: 105,
    name: 'Roth IRA Contribution Limit Calculator',
    description: 'Determine your maximum allowed Roth IRA contribution for the current tax year based on your income, filing status, and age.',
    slug: 'roth-ira-contribution-limit-calculator',
    category: 'finance',
  },
  {
    id: 106,
    name: 'Emergency Fund Calculator',
    description: 'Calculate how much cash you should set aside for unexpected expenses. Determine your ideal safety net based on your monthly costs.',
    slug: 'emergency-fund-calculator',
    category: 'finance',
  },
  // Health & Fitness
  {
    id: 107,
    name: 'Water Footprint of Food Calculator',
    description: 'Estimate the total volume of water required to produce different food items. Understand the hidden water usage in your diet.',
    slug: 'water-footprint-of-food-calculator',
    category: 'health-fitness'
  },
   {
    id: 108,
    name: 'Body Mass Index (BMI) Calculator',
    description: 'Quickly assess whether you are underweight, healthy, overweight, or obese using this standard health indicator.',
    slug: 'bmi-calculator',
    category: 'health-fitness'
  },
  {
    id: 109,
    name: 'Basal Metabolic Rate (BMR) Calculator',
    description: 'Estimate the number of calories your body burns at rest per day. A crucial metric for creating a weight management plan.',
    slug: 'bmr-calculator',
    category: 'health-fitness'
  },
  {
    id: 110,
    name: 'Target Heart Rate Calculator',
    description: 'Determine your optimal heart rate zone for moderate and vigorous exercise to maximize the effectiveness of your workouts.',
    slug: 'target-heart-rate-calculator',
    category: 'health-fitness'
  },
  // Home Improvement
  {
    id: 1,
    name: 'Paint Coverage Calculator',
    description: 'Calculates amount of paint needed for a project.',
    slug: 'paint-coverage-calculator',
    category: 'home-improvement',
  },
  {
    id: 2,
    name: 'Tile & Flooring Calculator',
    description: 'Number of tiles or square metres/feet of flooring material needed, including a % for wastage.',
    slug: 'tile-flooring-calculator',
    category: 'home-improvement',
  },
  {
    id: 3,
    name: 'Wallpaper Roll Calculator',
    description: 'Rolls of wallpaper required based on wall area and pattern repeat.',
    slug: 'wallpaper-roll-calculator',
    category: 'home-improvement',
  },
  {
    id: 4,
    name: 'Drywall/Plasterboard Calculator',
    description: 'Number of drywall sheets and joint compound needed for a room.',
    slug: 'drywall-plasterboard-calculator',
    category: 'home-improvement',
  },
  {
    id: 5,
    name: 'Insulation R-Value Calculator',
    description: 'Recommended insulation thickness and material type for a target R-value.',
    slug: 'insulation-r-value-calculator',
    category: 'home-improvement',
  },
  {
    id: 6,
    name: 'Decking Materials Calculator',
    description: 'Boards, fasteners, and joists needed for a deck of specific size.',
    slug: 'decking-materials-calculator',
    category: 'home-improvement',
  },
  {
    id: 7,
    name: 'Roofing Shingle Calculator',
    description: 'Bundles of shingles and underlayment required for a roof area with pitch adjustment.',
    slug: 'roofing-shingle-calculator',
    category: 'home-improvement',
  },
  {
    id: 8,
    name: 'Concrete Volume Calculator',
    description: 'Cubic metres/feet of concrete required for a slab, footing, or driveway.',
    slug: 'concrete-volume-calculator',
    category: 'home-improvement',
  },
  {
    id: 10,
    name: 'Lighting Layout Calculator',
    description: 'Number and placement of light fixtures needed to achieve a target lux/foot-candle level.',
    slug: 'lighting-layout-calculator',
    category: 'home-improvement',
  },
  {
    id: 11,
    name: 'HVAC Sizing Calculator',
    description: 'Approximate BTU or tonnage of heating/cooling system needed for a room/house size.',
    slug: 'hvac-sizing-calculator',
    category: 'home-improvement',
  },
  {
    id: 12,
    name: 'Staircase Rise & Run Calculator',
    description: 'Number of steps, tread depth, and riser height for a given total height.',
    slug: 'staircase-rise-run-calculator',
    category: 'home-improvement',
  },
  {
    id: 13,
    name: 'Cost Estimator for Renovation',
    description: 'Rough cost breakdown based on square footage and type of work (kitchen, bathroom, etc.).',
    slug: 'cost-estimator-renovation-calculator',
    category: 'home-improvement',
  },
  {
    id: 14,
    name: 'Water Usage / Plumbing Flow Calculator',
    description: 'Expected water flow and pipe size requirements for new fixtures.',
    slug: 'water-usage-plumbing-flow-calculator',
    category: 'home-improvement',
  },
  {
    id: 15,
    name: 'Garden/Landscape Soil & Mulch Calculator',
    description: 'Volume of soil or mulch needed for beds or planters.',
    slug: 'garden-landscape-soil-mulch-calculator',
    category: 'home-improvement',
  },
  // Engineering
  {
    id: 16,
    name: 'Beam Bending Calculator',
    description: 'Calculate bending stress and deflection for beams under load.',
    slug: 'beam-bending-calculator',
    category: 'engineering',
  },
  {
    id: 17,
    name: 'Hydraulic Pipe Flow Calculator',
    description: 'Compute head loss due to friction in a pipe using the Darcy-Weisbach equation.',
    slug: 'hydraulic-pipe-flow-calculator',
    category: 'engineering',
  },
  {
    id: 18,
    name: 'Heat Transfer Calculator',
    description: 'Find steady-state heat transfer rate through a flat wall by conduction.',
    slug: 'heat-transfer-calculator',
    category: 'engineering',
  },
  {
    id: 19,
    name: 'Electrical Power Calculator (3-Phase)',
    description: 'Calculate total real power in a balanced 3-phase electrical system.',
    slug: 'electrical-power-calculator',
    category: 'engineering',
  },
  {
    id: 20,
    name: 'Compressive Stress Calculator',
    description: 'Calculate stress when a compressive load is applied to a material.',
    slug: 'compressive-stress-calculator',
    category: 'engineering',
  },
  {
    id: 21,
    name: 'Cantilever Beam Deflection Calculator',
    description: 'Determine the vertical deflection at the free end of a cantilever beam.',
    slug: 'cantilever-beam-deflection-calculator',
    category: 'engineering',
  },
  {
    id: 22,
    name: 'Natural Frequency Calculator',
    description: 'Calculate the natural frequency of a simple spring-mass system.',
    slug: 'natural-frequency-calculator',
    category: 'engineering',
  },
  {
    id: 23,
    name: 'Reynolds Number Calculator',
    description: 'Determine whether a fluid flow is laminar, transitional, or turbulent.',
    slug: 'reynolds-number-calculator',
    category: 'engineering',
  },
  {
    id: 24,
    name: 'Thermal Expansion Calculator',
    description: 'Compute the change in length of a material due to temperature change.',
    slug: 'thermal-expansion-calculator',
    category: 'engineering',
  },
  {
    id: 25,
    name: 'Shear Stress in a Shaft Calculator',
    description: 'Calculate maximum shear stress in a circular shaft subjected to torsion.',
    slug: 'shear-stress-calculator',
    category: 'engineering',
  },
  // Cognitive & Psychology
  {
    id: 31,
    name: 'IQ Score Estimator',
    description: 'Estimate IQ based on standardized test scores.',
    slug: 'iq-score-estimator',
    category: 'cognitive-psychology',
  },
  {
    id: 32,
    name: 'Memory Span Calculator',
    description: 'Measure short-term memory capacity.',
    slug: 'memory-span-calculator',
    category: 'cognitive-psychology',
  },
  {
    id: 33,
    name: 'Cognitive Load Calculator',
    description: 'Estimate mental effort for a task.',
    slug: 'cognitive-load-calculator',
    category: 'cognitive-psychology',
  },
  {
    id: 34,
    name: 'Personality Trait Calculator (Big 5)',
    description: 'Estimate 5 personality traits based on a simple self-report scale.',
    slug: 'personality-trait-calculator',
    category: 'cognitive-psychology',
  },
  {
    id: 111,
    name: 'Stroop Effect Reaction-Time Calculator',
    description: 'Measure cognitive interference and selective attention by comparing reaction times.',
    slug: 'stroop-effect-reaction-time-calculator',
    category: 'cognitive-psychology',
  },
  {
    id: 112,
    name: 'Mental Fatigue Index Calculator',
    description: 'Estimate the rate of mental fatigue after performing a cognitive task.',
    slug: 'mental-fatigue-index-calculator',
    category: 'cognitive-psychology',
  },
  {
    id: 113,
    name: 'Emotional Valence Scoring Calculator',
    description: 'Quantify the positive vs. negative emotional tone of a short text passage.',
    slug: 'emotional-valence-scoring-calculator',
    category: 'cognitive-psychology',
  },
  {
    id: 114,
    name: 'Attention Span Estimator',
    description: 'Estimate sustained attention capacity using a simplified performance test metric.',
    slug: 'attention-span-estimator',
    category: 'cognitive-psychology',
  },
  {
    id: 115,
    name: 'Sleep Debt Calculator',
    description: 'Determine your weekly sleep debt and its potential impact on cognitive performance.',
    slug: 'sleep-debt-calculator',
    category: 'cognitive-psychology',
  },
  {
    id: 116,
    name: 'Stress Level Index (PSS) Calculator',
    description: 'Score your perceived stress level over the past month using the Perceived Stress Scale.',
    slug: 'stress-level-index-calculator',
    category: 'cognitive-psychology',
  },
  // Genetic & Ancestry
  {
    id: 35,
    name: 'Ancestry Composition Estimator',
    description: 'A simplified tool to estimate ethnic background percentages for entertainment.',
    slug: 'ancestry-composition-estimator',
    category: 'genetic-ancestry',
  },
  {
    id: 36,
    name: 'Genetic Trait Probability Calculator',
    description: 'Predict likelihood of inheriting specific traits using Punnett squares.',
    slug: 'genetic-trait-probability-calculator',
    category: 'genetic-ancestry',
  },
  {
    id: 37,
    name: 'Pedigree Analysis Calculator',
    description: 'Assess simple genetic relationships and inheritance patterns within family trees.',
    slug: 'pedigree-analysis-calculator',
    category: 'genetic-ancestry',
  },
  {
    id: 38,
    name: 'Genealogy Timeline Generator',
    description: 'Visualize an estimated ancestral lineage and key dates over time.',
    slug: 'genealogy-timeline-generator',
    category: 'genetic-ancestry',
  },
  // Environment
  {
    id: 39,
    name: 'Carbon Footprint Reduction Calculator',
    description: 'Suggests actions to reduce personal carbon emissions.',
    slug: 'carbon-footprint-reduction-calculator',
    category: 'environment',
  },
  {
    id: 40,
    name: 'Water Usage Efficiency Calculator',
    description: 'Estimates water conservation potential in households.',
    slug: 'water-usage-efficiency-calculator',
    category: 'environment',
  },
  {
    id: 41,
    name: 'Recycling Impact Calculator',
    description: 'Quantifies environmental benefits of recycling efforts.',
    slug: 'recycling-impact-calculator',
    category: 'environment',
  },
  {
    id: 42,
    name: 'Sustainable Diet Impact Calculator',
    description: 'Analyzes environmental impact of dietary choices.',
    slug: 'sustainable-diet-impact-calculator',
    category: 'environment',
  },
  // DIY & Crafts
  {
    id: 43,
    name: 'Paint Coverage Estimator',
    description: 'Calculates amount of paint needed for a project.',
    slug: 'paint-coverage-estimator',
    category: 'diy-crafts',
  },
  {
    id: 44,
    name: 'Knitting Pattern Calculator',
    description: 'Determines yarn requirements for custom patterns.',
    slug: 'knitting-pattern-calculator',
    category: 'diy-crafts',
  },
  {
    id: 45,
    name: 'Sewing Fabric Yardage Calculator',
    description: 'Estimates fabric needed based on garment size and style.',
    slug: 'sewing-fabric-yardage-calculator',
    category: 'diy-crafts',
  },
  {
    id: 46,
    name: 'Woodworking Material Calculator',
    description: 'Assesses wood requirements for furniture projects.',
    slug: 'woodworking-material-calculator',
    category: 'diy-crafts',
  },
  // Historical & Archaeological
  {
    id: 47,
    name: 'Artifact Dating Calculator',
    description: 'Estimates age of artifacts based on decay rates.',
    slug: 'artifact-dating-calculator',
    category: 'historical-archaeological',
  },
  {
    id: 48,
    name: 'Historical Population Density Calculator',
    description: 'Analyzes population trends over time.',
    slug: 'historical-population-density-calculator',
    category: 'historical-archaeological',
  },
  {
    id: 49,
    name: 'Archaeological Site Excavation Calculator',
    description: 'Predicts excavation timelines and costs.',
    slug: 'archaeological-site-excavation-calculator',
    category: 'historical-archaeological',
  },
  {
    id: 50,
    name: 'Ancient Civilization Timeline Generator',
    description: 'Visualizes historical events and timelines.',
    slug: 'ancient-civilization-timeline-generator',
    category: 'historical-archaeological',
  },
  // Travel & Adventure
  {
    id: 51,
    name: 'Backpacking Load Weight Calculator',
    description: 'Assesses optimal backpack weight for treks.',
    slug: 'backpacking-load-weight-calculator',
    category: 'travel-adventure',
  },
  {
    id: 52,
    name: 'Hiking Elevation Gain Calculator',
    description: 'Estimates elevation changes during hikes.',
    slug: 'hiking-elevation-gain-calculator',
    category: 'travel-adventure',
  },
  {
    id: 53,
    name: 'Travel Budget Estimator',
    description: 'Calculates expected expenses for trips.',
    slug: 'travel-budget-estimator',
    category: 'travel-adventure',
  },
  {
    id: 54,
    name: 'Adventure Activity Risk Calculator',
    description: 'Assesses risk levels of various adventure sports.',
    slug: 'adventure-activity-risk-calculator',
    category: 'travel-adventure',
  },
  // Technology
  {
    id: 55,
    name: 'Battery Life Estimator',
    description: 'Predict device runtime from mAh capacity and average power draw.',
    slug: 'battery-life-estimator',
    category: 'technology',
  },
  {
    id: 56,
    name: 'Power Supply Wattage Calculator',
    description: 'Suggest PSU size based on PC components.',
    slug: 'power-supply-wattage-calculator',
    category: 'technology',
  },
  {
    id: 57,
    name: 'Overclocking Thermal Calculator',
    description: 'Estimate CPU/GPU temps from voltage &amp; frequency changes.',
    slug: 'overclocking-thermal-calculator',
    category: 'technology',
  },
  {
    id: 58,
    name: 'Network Bandwidth Calculator',
    description: 'Work out required bandwidth for a given number of users or video streams.',
    slug: 'network-bandwidth-calculator',
    category: 'technology',
  },
  {
    id: 59,
    name: 'Ping / Latency Distance Calculator',
    description: 'Approximate physical distance from ping time.',
    slug: 'ping-latency-distance-calculator',
    category: 'technology',
  },
  {
    id: 60,
    name: 'UPS Runtime Calculator',
    description: 'Estimate backup time for servers or home setups.',
    slug: 'ups-runtime-calculator',
    category: 'technology',
  },
  {
    id: 61,
    name: 'Internet Data Usage Estimator',
    description: 'Predict monthly usage from hours of streaming/gaming.',
    slug: 'internet-data-usage-estimator',
    category: 'technology',
  },
  {
    id: 62,
    name: 'Disk RAID Capacity Calculator',
    description: 'Calculate usable storage and redundancy for RAID levels.',
    slug: 'disk-raid-capacity-calculator',
    category: 'technology',
  },
  {
    id: 63,
    name: 'Code Time Complexity Estimator',
    description: 'Quick reference for big-O growth when scaling input size.',
    slug: 'code-time-complexity-estimator',
    category: 'technology',
  },
  {
    id: 64,
    name: 'API Rate Limit Planner',
    description: 'Calculate calls per second/minute based on quota.',
    slug: 'api-rate-limit-planner',
    category: 'technology',
  },
  {
    id: 65,
    name: 'Regex Performance Checker',
    description: 'Estimate time complexity for given regex patterns.',
    slug: 'regex-performance-checker',
    category: 'technology',
  },
  {
    id: 66,
    name: 'Image Compression Size Calculator',
    description: 'Predict final file size for given compression ratio &amp; resolution.',
    slug: 'image-compression-size-calculator',
    category: 'technology',
  },
  {
    id: 67,
    name: 'Password Entropy Calculator',
    description: 'Measure strength of a password by bits of entropy.',
    slug: 'password-entropy-calculator',
    category: 'technology',
  },
  {
    id: 68,
    name: 'Hash Collision Probability Calculator',
    description: 'Estimate chance of collisions for given hash length &amp; number of items.',
    slug: 'hash-collision-probability-calculator',
    category: 'technology',
  },
  {
    id: 69,
    name: 'Cloud Cost Estimator',
    description: 'Rough monthly spend for compute/storage/bandwidth.',
    slug: 'cloud-cost-estimator',
    category: 'technology',
  },
  {
    id: 70,
    name: 'Subnet Mask / CIDR Calculator',
    description: 'Find IP ranges, hosts, and broadcast addresses.',
    slug: 'subnet-mask-cidr-calculator',
    category: 'technology',
  },
  {
    id: 71,
    name: 'Download Time Calculator',
    description: 'Time to download a file based on size and speed.',
    slug: 'download-time-calculator',
    category: 'technology',
  },
  {
    id: 72,
    name: 'Latency-to-Throughput Calculator',
    description: 'Compute max throughput for a given latency (TCP window).',
    slug: 'latency-to-throughput-calculator',
    category: 'technology',
  },
  {
    id: 73,
    name: '3D Print Time & Material Calculator',
    description: 'Estimate filament usage and print time.',
    slug: '3d-print-time-material-calculator',
    category: 'technology',
  },
  {
    id: 74,
    name: 'Solar Panel Output Calculator for Gadgets',
    description: 'Predict daily energy generation for portable solar setups.',
    slug: 'solar-panel-output-calculator',
    category: 'technology',
  },
  // Fun & Games
  {
    id: 75,
    name: 'Dice Roll Probability',
    description: 'Odds of rolling a certain number or combination.',
    slug: 'dice-roll-probability',
    category: 'fun-games',
  },
  {
    id: 76,
    name: 'Board Game Scoring',
    description: 'Track and tally scores for popular games (e.g., Settlers of Catan, Scrabble).',
    slug: 'board-game-scoring',
    category: 'fun-games',
  },
  {
    id: 77,
    name: 'RPG Character Stat',
    description: 'Auto-generate or balance D&D style character stats.',
    slug: 'rpg-character-stat',
    category: 'fun-games',
  },
  {
    id: 78,
    name: 'Esports K/D Ratio',
    description: 'Compute kill/death ratio and needed kills to hit a target K/D.',
    slug: 'esports-kd-ratio',
    category: 'fun-games',
  },
  {
    id: 79,
    name: 'Video Game XP Level-Up',
    description: 'Time or XP needed to reach the next level.',
    slug: 'video-game-xp-level-up',
    category: 'fun-games',
  },
  {
    id: 80,
    name: 'Movie Marathon Time',
    description: 'Total watch time for a list of movies or TV episodes.',
    slug: 'movie-marathon-time',
    category: 'fun-games',
  },
  {
    id: 81,
    name: 'Book Series Reading Time',
    description: 'How many hours to finish a series at your reading speed.',
    slug: 'book-series-reading-time',
    category: 'fun-games',
  },
  {
    id: 82,
    name: 'Song Playlist Duration',
    description: 'Add up total minutes for a playlist.',
    slug: 'song-playlist-duration',
    category: 'fun-games',
  },
  {
    id: 83,
    name: 'Pop Culture Age',
    description: 'How old a celebrity/character would be today.',
    slug: 'pop-culture-age',
    category: 'fun-games',
  },
  {
    id: 84,
    name: 'Pet Name Popularity',
    description: 'Rank a name’s popularity over time (using open datasets).',
    slug: 'pet-name-popularity',
    category: 'fun-games',
  },
  {
    id: 85,
    name: 'Meme Lifespan',
    description: 'Estimate how long a meme will stay trendy based on shares &amp; likes.',
    slug: 'meme-lifespan',
    category: 'fun-games',
  },
  {
    id: 86,
    name: 'Emoji Compatibility',
    description: 'Enter two names, see a playful “compatibility score” with emojis.',
    slug: 'emoji-compatibility',
    category: 'fun-games',
  },
  {
    id: 87,
    name: 'Random Nickname Generator',
    description: 'Rate the “coolness” of a generated nickname.',
    slug: 'random-nickname-generator',
    category: 'fun-games',
  },
  {
    id: 88,
    name: 'Friendship Anniversary',
    description: 'Days since you first met.',
    slug: 'friendship-anniversary',
    category: 'fun-games',
  },
  {
    id: 89,
    name: 'Bowling Score',
    description: 'Tally frames and strikes automatically.',
    slug: 'bowling-score',
    category: 'fun-games',
  },
  {
    id: 90,
    name: 'Golf Handicap',
    description: 'Quick estimate of a player’s handicap.',
    slug: 'golf-handicap',
    category: 'fun-games',
  },
  {
    id: 91,
    name: 'Fantasy League Points',
    description: 'Predict weekly fantasy team points.',
    slug: 'fantasy-league-points',
    category: 'fun-games',
  },
  {
    id: 92,
    name: 'Party Budget Per Person',
    description: 'Split cost of food, drinks, decorations.',
    slug: 'party-budget-per-person',
    category: 'fun-games',
  },
  {
    id: 93,
    name: 'BBQ Food & Drink Quantity',
    description: 'Estimate servings needed for a given crowd.',
    slug: 'bbq-food-drink-quantity',
    category: 'fun-games',
  },
  {
    id: 94,
    name: 'Karaoke Queue Time',
    description: 'How long until it’s your turn based on song lengths.',
    slug: 'karaoke-queue-time',
    category: 'fun-games',
  },
];

    