
import type { LucideIcon } from 'lucide-react';
import {
  Landmark,
  HeartPulse,
  Home,
  Construction,
  BookOpen,
  Laptop,
  Plane,
  ChefHat,
  Leaf,
  PiggyBank,
  Briefcase,
  Bitcoin,
  Baby,
  Dumbbell,
  Calendar,
  Gamepad2,
  BrainCircuit,
  GitBranch,
  Beaker,
  IceCream2,
  Utensils,
  Clock,
  FlaskConical,
  Droplets,
  Cookie,
  Coffee,
  GlassWater,
  Zap,
  Ship,
  Waves,
  Scale,
  Shirt,
  ArrowRightLeft,
  Percent,
  Bone,
  User,
  Target,
  Circle,
  Square,
  Triangle,
  Hexagon,
  Octagon,
  Trophy,
  FileText,
  CreditCard,
  Shield,
  Handshake,
  TrendingUp,
  PieChart,
  BarChart,
  Wallet,
  Apple,
  Activity,
  Moon,
} from 'lucide-react';

export interface SubCategory {
  name: string;
  slug: string;
  description: string;
}

export interface Category {
  name: string;
  slug: string;
  description: string;
  Icon: string;
  subcategories?: SubCategory[];
}

export const icons: { [key: string]: LucideIcon } = {
  Landmark,
  HeartPulse,
  Home,
  Construction,
  BookOpen,
  Laptop,
  Plane,
  ChefHat,
  Leaf,
  PiggyBank,
  Briefcase,
  Bitcoin,
  Baby,
  Dumbbell,
  Calendar,
  Gamepad2,
  BrainCircuit,
  GitBranch,
  Beaker,
  IceCream2,
  Utensils,
  Clock,
  FlaskConical,
  Droplets,
  Cookie,
  Coffee,
  GlassWater,
  Zap,
  Ship,
  Waves,
  Scale,
  Shirt,
  ArrowRightLeft,
  Percent,
  Bone,
  User,
  Target,
  Circle,
  Square,
  Triangle,
  Hexagon,
  Octagon,
  Trophy,
  FileText,
  CreditCard,
  Shield,
  Handshake,
  TrendingUp,
  PieChart,
  BarChart,
  Wallet,
  Apple,
  Activity,
  Moon,
};

export const categories: Category[] = [
  {
    name: 'Finance',
    slug: 'finance',
    description: 'Calculators for investments, loans, and financial planning.',
    Icon: 'Landmark',
  },
  {
    name: 'Health & Fitness',
    slug: 'health-fitness',
    description: 'Track your fitness goals, BMI, and calorie intake.',
    Icon: 'HeartPulse',
  },

  {
    name: 'Conversions',
    slug: 'conversions',
    description: 'Tools for converting between different units of measurement.',
    Icon: 'ArrowRightLeft',
  },
  {
    name: 'Home Improvement',
    slug: 'home-improvement',
    description: 'Plan your next project, from paint to mortgage.',
    Icon: 'Home',
  },
  {
    name: 'Engineering',
    slug: 'engineering',
    description: 'Solve complex engineering problems and conversions.',
    Icon: 'Construction',
  },

  {
    name: 'Technology',
    slug: 'technology',
    description: 'Calculators for data storage, bandwidth, and more.',
    Icon: 'Laptop',
  },
  {
    name: 'Travel & Adventure',
    slug: 'travel-adventure',
    description: 'Plan your trips, hikes, and adventures.',
    Icon: 'Plane',
  },
  {
    name: 'Cooking & Food',
    slug: 'cooking-food',
    description: 'Convert recipes and manage your culinary creations.',
    Icon: 'ChefHat',
  },
  {
    name: 'Environment',
    slug: 'environment',
    description: 'Calculate your carbon footprint and environmental impact.',
    Icon: 'Leaf',
  },
  {
    name: 'Personal Budgeting',
    slug: 'personal-budgeting',
    description: 'Manage your personal finances and savings goals.',
    Icon: 'PiggyBank',
  },
  {
    name: 'Education',
    slug: 'education',
    description: 'Calculators for students, teachers, and lifelong learners.',
    Icon: 'BookOpen',
    subcategories: [
      {
        name: 'Maths',
        slug: 'maths',
        description: 'Solve mathematical problems, from basic arithmetic to complex formulas.',
      },
    ],
  },
  {
    name: 'Business & Startup',
    slug: 'business-startup',
    description: 'Calculators for profit margin, breakeven, and more.',
    Icon: 'Briefcase',
  },
  {
    name: 'Time & Date',
    slug: 'time-date',
    description: 'Calculate durations, time zones, and important dates.',
    Icon: 'Calendar',
  },
];
