
import type { LucideIcon } from 'lucide-react';
import {
  Landmark,
  HeartPulse,
  Home,
  Construction,
  BookOpen,
  Laptop,
  Plane,
  ChefHat,
  Leaf,
  PiggyBank,
  Briefcase,
  Bitcoin,
  Baby,
  Dumbbell,
  Calendar,
  Gamepad2,
  BrainCircuit,
  GitBranch,
  Beaker,
  IceCream2,
  Utensils,
  Clock,
  FlaskConical,
  Droplets,
  Cookie,
  Coffee,
  GlassWater,
  Zap,
  Ship,
  Waves,
  Scale,
  Shirt,
  ArrowRightLeft,
} from 'lucide-react';

export interface Category {
  name: string;
  slug: string;
  description: string;
  Icon: string;
}

export const icons: {[key: string]: LucideIcon} = {
  Landmark,
  HeartPulse,
  Home,
  Construction,
  BookOpen,
  Laptop,
  Plane,
  ChefHat,
  Leaf,
  PiggyBank,
  Briefcase,
  Bitcoin,
  Baby,
  Dumbbell,
  Calendar,
  Gamepad2,
  BrainCircuit,
  GitBranch,
  Beaker,
  IceCream2,
  Utensils,
  Clock,
  FlaskConical,
  Droplets,
  Cookie,
  Coffee,
  GlassWater,
  Zap,
  Ship,
  Waves,
  Scale,
  Shirt,
  ArrowRightLeft,
};

export const categories: Category[] = [
  {
    name: 'Finance',
    slug: 'finance',
    description: 'Calculators for investments, loans, and financial planning.',
    Icon: 'Landmark',
  },
  {
    name: 'Health & Fitness',
    slug: 'health-fitness',
    description: 'Track your fitness goals, BMI, and calorie intake.',
    Icon: 'HeartPulse',
  },
  {
    name: 'Length Conversions',
    slug: 'length-conversions',
    description: 'A collection of calculators for converting between different units of length.',
    Icon: 'ArrowRightLeft',
  },
  {
    name: 'Home Improvement',
    slug: 'home-improvement',
    description: 'Plan your next project, from paint to mortgage.',
    Icon: 'Home',
  },
  {
    name: 'Engineering',
    slug: 'engineering',
    description: 'Solve complex engineering problems and conversions.',
    Icon: 'Construction',
  },
  {
    name: 'Biology',
    slug: 'biology',
    description: 'Calculators for common molecular biology lab tasks.',
    Icon: 'FlaskConical',
  },
  {
    name: 'Cognitive & Psychology',
    slug: 'cognitive-psychology',
    description: 'Explore aspects of cognition and personality.',
    Icon: 'BrainCircuit',
  },
  {
    name: 'Genetic & Ancestry',
    slug: 'genetic-ancestry',
    description: 'Explore your heritage and genetic traits with these tools.',
    Icon: 'GitBranch',
  },
  {
    name: 'Education',
    slug: 'education',
    description: 'Tools for students and teachers, from grades to study time.',
    Icon: 'BookOpen',
  },
  {
    name: 'Technology',
    slug: 'technology',
    description: 'Calculators for data storage, bandwidth, and more.',
    Icon: 'Laptop',
  },
  {
    name: 'Travel & Adventure',
    slug: 'travel-adventure',
    description: 'Plan your trips, hikes, and adventures.',
    Icon: 'Plane',
  },
  {
    name: 'Cooking & Food',
    slug: 'cooking-food',
    description: 'Convert recipes and manage your culinary creations.',
    Icon: 'ChefHat',
  },
  {
    name: 'Environment',
    slug: 'environment',
    description: 'Calculate your carbon footprint and environmental impact.',
    Icon: 'Leaf',
  },
  {
    name: 'Personal Budgeting',
    slug: 'personal-budgeting',
    description: 'Manage your personal finances and savings goals.',
    Icon: 'PiggyBank',
  },
  {
    name: 'Business & Startup',
    slug: 'business-startup',
    description: 'Calculators for profit margin, breakeven, and more.',
    Icon: 'Briefcase',
  },
  {
    name: 'Crypto & Web3',
    slug: 'crypto-web3',
    description: 'Track your crypto assets and blockchain metrics.',
    Icon: 'Bitcoin',
  },
  {
    name: 'Parenting',
    slug: 'parenting',
    description: 'Calculators for pregnancy, child growth, and costs.',
    Icon: 'Baby',
  },
  {
    name: 'Sports & Training',
    slug: 'sports-training',
    description: 'Optimize your training with pace and performance calculators.',
    Icon: 'Dumbbell',
  },
  {
    name: 'Time & Date',
    slug: 'time-date',
    description: 'Calculate durations, time zones, and important dates.',
    Icon: 'Calendar',
  },
  {
    name: 'Fun & Games',
    slug: 'fun-games',
    description: 'Calculators for gaming, hobbies, and entertainment.',
    Icon: 'Gamepad2',
  },
];
