'use client';

import React, { lazy, useState, useEffect } from 'react';

// Static map of calculators to avoid dynamic import context creation
const components: Record<string, React.LazyExoticComponent<React.ComponentType<any>>> = {
  'fortnite-build-material-cost-calculator-interactive': lazy(() => import('./fortnite-build-material-cost-calculator-interactive')),
  'fortnite-build-material-cost-calculator': lazy(() => import('./fortnite-build-material-cost-calculator')),
  'fortnite-dps-calculator-interactive': lazy(() => import('./fortnite-dps-calculator-interactive')),
  'fortnite-dps-calculator': lazy(() => import('./fortnite-dps-calculator')),
  'fortnite-loot-drop-odds-estimator-interactive': lazy(() => import('./fortnite-loot-drop-odds-estimator-interactive')),
  'fortnite-loot-drop-odds-estimator': lazy(() => import('./fortnite-loot-drop-odds-estimator')),
  'fortnite-reload-time-reducer-calculator-interactive': lazy(() => import('./fortnite-reload-time-reducer-calculator-interactive')),
  'fortnite-reload-time-reducer-calculator': lazy(() => import('./fortnite-reload-time-reducer-calculator')),
  'fortnite-shield-potency-calculator-interactive': lazy(() => import('./fortnite-shield-potency-calculator-interactive')),
  'fortnite-shield-potency-calculator': lazy(() => import('./fortnite-shield-potency-calculator')),
  'fortnite-storm-surge-timer-interactive': lazy(() => import('./fortnite-storm-surge-timer-interactive')),
  'fortnite-storm-surge-timer': lazy(() => import('./fortnite-storm-surge-timer')),
  'fortnite-victory-royale-probability-estimator-interactive': lazy(() => import('./fortnite-victory-royale-probability-estimator-interactive')),
  'fortnite-victory-royale-probability-estimator': lazy(() => import('./fortnite-victory-royale-probability-estimator')),
  'fortnite-xp-per-match-optimizer-interactive': lazy(() => import('./fortnite-xp-per-match-optimizer-interactive')),
  'fortnite-xp-per-match-optimizer': lazy(() => import('./fortnite-xp-per-match-optimizer')),
  'minecraft-beacon-range-optimizer-interactive': lazy(() => import('./minecraft-beacon-range-optimizer-interactive')),
  'minecraft-beacon-range-optimizer': lazy(() => import('./minecraft-beacon-range-optimizer')),
  'minecraft-enchanting-odds-predictor-interactive': lazy(() => import('./minecraft-enchanting-odds-predictor-interactive')),
  'minecraft-enchanting-odds-predictor': lazy(() => import('./minecraft-enchanting-odds-predictor')),
  'minecraft-farm-yield-calculator-interactive': lazy(() => import('./minecraft-farm-yield-calculator-interactive')),
  'minecraft-farm-yield-calculator': lazy(() => import('./minecraft-farm-yield-calculator')),
  'minecraft-mob-farm-xp-rate-calculator-interactive': lazy(() => import('./minecraft-mob-farm-xp-rate-calculator-interactive')),
  'minecraft-mob-farm-xp-rate-calculator': lazy(() => import('./minecraft-mob-farm-xp-rate-calculator')),
  'minecraft-nether-portal-linkage-estimator-interactive': lazy(() => import('./minecraft-nether-portal-linkage-estimator-interactive')),
  'minecraft-nether-portal-linkage-estimator': lazy(() => import('./minecraft-nether-portal-linkage-estimator')),
  'minecraft-redstone-signal-delay-calculator-interactive': lazy(() => import('./minecraft-redstone-signal-delay-calculator-interactive')),
  'minecraft-redstone-signal-delay-calculator': lazy(() => import('./minecraft-redstone-signal-delay-calculator')),
  'minecraft-smelter-fuel-efficiency-interactive': lazy(() => import('./minecraft-smelter-fuel-efficiency-interactive')),
  'minecraft-smelter-fuel-efficiency': lazy(() => import('./minecraft-smelter-fuel-efficiency')),
  'minecraft-tree-farm-output-calculator-interactive': lazy(() => import('./minecraft-tree-farm-output-calculator-interactive')),
  'minecraft-tree-farm-output-calculator': lazy(() => import('./minecraft-tree-farm-output-calculator')),
  'minecraft-villager-trade-tracker-interactive': lazy(() => import('./minecraft-villager-trade-tracker-interactive')),
  'minecraft-villager-trade-tracker': lazy(() => import('./minecraft-villager-trade-tracker')),
  'roblox-adopt-me-age-up-time-calculator-interactive': lazy(() => import('./roblox-adopt-me-age-up-time-calculator-interactive')),
  'roblox-adopt-me-age-up-time-calculator': lazy(() => import('./roblox-adopt-me-age-up-time-calculator')),
  'roblox-adopt-me-bucks-to-robux-converter-interactive': lazy(() => import('./roblox-adopt-me-bucks-to-robux-converter-interactive')),
  'roblox-adopt-me-bucks-to-robux-converter': lazy(() => import('./roblox-adopt-me-bucks-to-robux-converter')),
  'roblox-adopt-me-collection-value-estimator-interactive': lazy(() => import('./roblox-adopt-me-collection-value-estimator-interactive')),
  'roblox-adopt-me-collection-value-estimator': lazy(() => import('./roblox-adopt-me-collection-value-estimator')),
  'roblox-adopt-me-egg-hatch-value-calculator-interactive': lazy(() => import('./roblox-adopt-me-egg-hatch-value-calculator-interactive')),
  'roblox-adopt-me-egg-hatch-value-calculator': lazy(() => import('./roblox-adopt-me-egg-hatch-value-calculator')),
  'roblox-adopt-me-legendary-pet-probability-calculator-interactive': lazy(() => import('./roblox-adopt-me-legendary-pet-probability-calculator-interactive')),
  'roblox-adopt-me-legendary-pet-probability-calculator': lazy(() => import('./roblox-adopt-me-legendary-pet-probability-calculator')),
  'roblox-adopt-me-mega-neon-value-calculator-interactive': lazy(() => import('./roblox-adopt-me-mega-neon-value-calculator-interactive')),
  'roblox-adopt-me-mega-neon-value-calculator': lazy(() => import('./roblox-adopt-me-mega-neon-value-calculator')),
  'roblox-adopt-me-neon-pet-value-calculator-interactive': lazy(() => import('./roblox-adopt-me-neon-pet-value-calculator-interactive')),
  'roblox-adopt-me-neon-pet-value-calculator': lazy(() => import('./roblox-adopt-me-neon-pet-value-calculator')),
  'roblox-adopt-me-pet-aging-speed-calculator-interactive': lazy(() => import('./roblox-adopt-me-pet-aging-speed-calculator-interactive')),
  'roblox-adopt-me-pet-aging-speed-calculator': lazy(() => import('./roblox-adopt-me-pet-aging-speed-calculator')),
  'roblox-adopt-me-trade-win-loss-calculator-interactive': lazy(() => import('./roblox-adopt-me-trade-win-loss-calculator-interactive')),
  'roblox-adopt-me-trade-win-loss-calculator': lazy(() => import('./roblox-adopt-me-trade-win-loss-calculator')),
  'roblox-adopt-me-trust-trade-safety-calculator-interactive': lazy(() => import('./roblox-adopt-me-trust-trade-safety-calculator-interactive')),
  'roblox-adopt-me-trust-trade-safety-calculator': lazy(() => import('./roblox-adopt-me-trust-trade-safety-calculator')),
  'roblox-egg-hatch-odds-simulator-interactive': lazy(() => import('./roblox-egg-hatch-odds-simulator-interactive')),
  'roblox-egg-hatch-odds-simulator': lazy(() => import('./roblox-egg-hatch-odds-simulator')),
  'roblox-gamepass-roi-calculator-interactive': lazy(() => import('./roblox-gamepass-roi-calculator-interactive')),
  'roblox-gamepass-roi-calculator': lazy(() => import('./roblox-gamepass-roi-calculator')),
  'roblox-inventory-value-estimator-interactive': lazy(() => import('./roblox-inventory-value-estimator-interactive')),
  'roblox-inventory-value-estimator': lazy(() => import('./roblox-inventory-value-estimator')),
  'roblox-limited-item-resale-predictor-interactive': lazy(() => import('./roblox-limited-item-resale-predictor-interactive')),
  'roblox-limited-item-resale-predictor': lazy(() => import('./roblox-limited-item-resale-predictor')),
  'roblox-pet-dupe-value-calculator-interactive': lazy(() => import('./roblox-pet-dupe-value-calculator-interactive')),
  'roblox-pet-dupe-value-calculator': lazy(() => import('./roblox-pet-dupe-value-calculator')),
  'roblox-pet-simulator-99-pet-value-calculator-interactive': lazy(() => import('./roblox-pet-simulator-99-pet-value-calculator-interactive')),
  'roblox-pet-simulator-99-pet-value-calculator': lazy(() => import('./roblox-pet-simulator-99-pet-value-calculator')),
  'roblox-pet-simulator-x-diamond-calculator-interactive': lazy(() => import('./roblox-pet-simulator-x-diamond-calculator-interactive')),
  'roblox-pet-simulator-x-diamond-calculator': lazy(() => import('./roblox-pet-simulator-x-diamond-calculator')),
  'roblox-pet-simulator-x-golden-pet-value-calculator': lazy(() => import('./roblox-pet-simulator-x-golden-pet-value-calculator')),
  'roblox-pet-simulator-x-golden-pet-value-interactive': lazy(() => import('./roblox-pet-simulator-x-golden-pet-value-interactive')),
  'roblox-pet-simulator-x-hatch-probability-calculator-interactive': lazy(() => import('./roblox-pet-simulator-x-hatch-probability-calculator-interactive')),
  'roblox-pet-simulator-x-hatch-probability-calculator': lazy(() => import('./roblox-pet-simulator-x-hatch-probability-calculator')),
  'roblox-pet-simulator-x-mastery-calculator-interactive': lazy(() => import('./roblox-pet-simulator-x-mastery-calculator-interactive')),
  'roblox-pet-simulator-x-mastery-calculator': lazy(() => import('./roblox-pet-simulator-x-mastery-calculator')),
  'roblox-pet-simulator-x-pet-power-calculator-interactive': lazy(() => import('./roblox-pet-simulator-x-pet-power-calculator-interactive')),
  'roblox-pet-simulator-x-pet-power-calculator': lazy(() => import('./roblox-pet-simulator-x-pet-power-calculator')),
  'roblox-pet-simulator-x-rebirth-calculator-interactive': lazy(() => import('./roblox-pet-simulator-x-rebirth-calculator-interactive')),
  'roblox-pet-simulator-x-rebirth-calculator': lazy(() => import('./roblox-pet-simulator-x-rebirth-calculator')),
  'roblox-pet-simulator-x-trading-value-calculator-interactive': lazy(() => import('./roblox-pet-simulator-x-trading-value-calculator-interactive')),
  'roblox-pet-simulator-x-trading-value-calculator': lazy(() => import('./roblox-pet-simulator-x-trading-value-calculator')),
  'roblox-pet-value-calculator-interactive': lazy(() => import('./roblox-pet-value-calculator-interactive')),
  'roblox-pet-value-calculator': lazy(() => import('./roblox-pet-value-calculator')),
  'roblox-trade-tax-calculator-interactive': lazy(() => import('./roblox-trade-tax-calculator-interactive')),
  'roblox-trade-tax-calculator': lazy(() => import('./roblox-trade-tax-calculator')),
  'roblox-trading-profit-analyzer-interactive': lazy(() => import('./roblox-trading-profit-analyzer-interactive')),
  'roblox-trading-profit-analyzer': lazy(() => import('./roblox-trading-profit-analyzer')),
  'valorant-rank-progression-interactive': lazy(() => import('./valorant-rank-progression-interactive')),
  'valorant-rank-progression': lazy(() => import('./valorant-rank-progression')),
  'valorant-rr-predictor-interactive': lazy(() => import('./valorant-rr-predictor-interactive')),
  'valorant-rr-predictor': lazy(() => import('./valorant-rr-predictor')),
};

export default function CalculatorRegistry({ calculatorSlug }: { calculatorSlug: string }) {
  const Component = components[calculatorSlug];

  if (!Component) {
    console.warn(`Calculator not found in registry: ${calculatorSlug}`);
    return <div className="p-8 text-center text-muted-foreground">Calculator not found.</div>;
  }

  return <Component />;
}
