
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft } from 'lucide-react';
import dynamic from 'next/dynamic';

import { Button } from '@/components/ui/button';
import { categories } from '@/lib/categories';
import { calculators } from '@/lib/calculators';
import { Card, CardContent } from '@/components/ui/card';
import { CategoryIcon } from '@/components/category-icon';

const calculatorComponents: { [key: string]: React.ComponentType } = {
    'sip-calculator': dynamic(() => import('@/components/calculators/finance/sip-calculator')),
    'loan-emi-calculator': dynamic(() => import('@/components/calculators/finance/loan-emi-calculator')),
    'retirement-savings-calculator': dynamic(() => import('@/components/calculators/finance/retirement-savings-calculator')),
    'compound-interest-calculator': dynamic(() => import('@/components/calculators/finance/compound-interest-calculator')),
    '401k-contribution-calculator': dynamic(() => import('@/components/calculators/finance/401k-contribution-calculator')),
    'net-worth-calculator': dynamic(() => import('@/components/calculators/finance/net-worth-calculator')),
    'credit-card-payoff-calculator': dynamic(() => import('@/components/calculators/finance/credit-card-payoff-calculator')),
    'mortgage-payment-calculator': dynamic(() => import('@/components/calculators/finance/mortgage-payment-calculator')),
    'student-loan-repayment-calculator': dynamic(() => import('@/components/calculators/finance/student-loan-repayment-calculator')),
    'inflation-calculator': dynamic(() => import('@/components/calculators/finance/inflation-calculator')),
    'roth-ira-contribution-limit-calculator': dynamic(() => import('@/components/calculators/finance/roth-ira-contribution-limit-calculator')),
    'present-value-calculator': dynamic(() => import('@/components/calculators/finance/present-value-calculator')),
    'future-value-calculator': dynamic(() => import('@/components/calculators/finance/future-value-calculator')),
    'annuity-payment-calculator': dynamic(() => import('@/components/calculators/finance/annuity-payment-calculator')),
    'perpetuity-calculator': dynamic(() => import('@/components/calculators/finance/perpetuity-calculator')),
    'growing-annuity-calculator': dynamic(() => import('@/components/calculators/finance/growing-annuity-calculator')),
    'irr-calculator': dynamic(() => import('@/components/calculators/finance/irr-calculator')),
    'npv-calculator': dynamic(() => import('@/components/calculators/finance/npv-calculator')),
    'dcf-calculator': dynamic(() => import('@/components/calculators/finance/dcf-calculator')),
    'payback-period-calculator': dynamic(() => import('@/components/calculators/finance/payback-period-calculator')),
    'discount-rate-calculator': dynamic(() => import('@/components/calculators/finance/discount-rate-calculator')),
    'price-to-earnings-ratio-calculator': dynamic(() => import('@/components/calculators/finance/price-to-earnings-ratio-calculator')),
    'earnings-per-share-calculator': dynamic(() => import('@/components/calculators/finance/earnings-per-share-calculator')),
    'return-on-equity-calculator': dynamic(() => import('@/components/calculators/finance/return-on-equity-calculator')),
    'return-on-assets-calculator': dynamic(() => import('@/components/calculators/finance/return-on-assets-calculator')),
    'return-on-investment-calculator': dynamic(() => import('@/components/calculators/finance/return-on-investment-calculator')),
    'debt-to-equity-ratio-calculator': dynamic(() => import('@/components/calculators/finance/debt-to-equity-ratio-calculator')),
    'interest-coverage-ratio-calculator': dynamic(() => import('@/components/calculators/finance/interest-coverage-ratio-calculator')),
    'current-ratio-calculator': dynamic(() => import('@/components/calculators/finance/current-ratio-calculator')),
    'quick-ratio-calculator': dynamic(() => import('@/components/calculators/finance/quick-ratio-calculator')),
    'working-capital-calculator': dynamic(() => import('@/components/calculators/finance/working-capital-calculator')),
    'cash-conversion-cycle-calculator': dynamic(() => import('@/components/calculators/finance/cash-conversion-cycle-calculator')),
    'free-cash-flow-calculator': dynamic(() => import('@/components/calculators/finance/free-cash-flow-calculator')),
    'operating-margin-calculator': dynamic(() => import('@/components/calculators/finance/operating-margin-calculator')),
    'gross-margin-calculator': dynamic(() => import('@/components/calculators/finance/gross-margin-calculator')),
    'net-profit-margin-calculator': dynamic(() => import('@/components/calculators/finance/net-profit-margin-calculator')),
    'ebitda-ebit-calculator': dynamic(() => import('@/components/calculators/finance/ebitda-ebit-calculator')),
    'enterprise-value-calculator': dynamic(() => import('@/components/calculators/finance/enterprise-value-calculator')),
    'ev-ebit-ebitda-multiple-calculator': dynamic(() => import('@/components/calculators/finance/ev-ebit-ebitda-multiple-calculator')),
    'sharpe-ratio-calculator': dynamic(() => import('@/components/calculators/finance/sharpe-ratio-calculator')),
    'sortino-ratio-calculator': dynamic(() => import('@/components/calculators/finance/sortino-ratio-calculator')),
    'treynor-ratio-calculator': dynamic(() => import('@/components/calculators/finance/treynor-ratio-calculator')),
    'alpha-investment-calculator': dynamic(() => import('@/components/calculators/finance/alpha-investment-calculator')),
    'volatility-standard-deviation-calculator': dynamic(() => import('@/components/calculators/finance/volatility-standard-deviation-calculator')),
    'correlation-coefficient-calculator': dynamic(() => import('@/components/calculators/finance/correlation-coefficient-calculator')),
    'beta-asset-calculator': dynamic(() => import('@/components/calculators/finance/beta-asset-calculator')),
    'portfolio-variance-calculator': dynamic(() => import('@/components/calculators/finance/portfolio-variance-calculator')),
    'portfolio-expected-return-calculator': dynamic(() => import('@/components/calculators/finance/portfolio-expected-return-calculator')),
    'capm-calculator': dynamic(() => import('@/components/calculators/finance/capm-calculator')),
    'wacc-calculator': dynamic(() => import('@/components/calculators/finance/wacc-calculator')),
    'leverage-debt-ratio-calculator': dynamic(() => import('@/components/calculators/finance/leverage-debt-ratio-calculator')),
    'black-scholes-calculator': dynamic(() => import('@/components/calculators/finance/black-scholes-calculator')),
    'option-payoff-calculator': dynamic(() => import('@/components/calculators/finance/option-payoff-calculator')),
    'binomial-option-pricing-calculator': dynamic(() => import('@/components/calculators/finance/binomial-option-pricing-calculator')),
    'monte-carlo-portfolio-calculator': dynamic(() => import('@/components/calculators/finance/monte-carlo-portfolio-calculator')),
    'value-at-risk-calculator': dynamic(() => import('@/components/calculators/finance/value-at-risk-calculator')),
    'conditional-value-at-risk-calculator': dynamic(() => import('@/components/calculators/finance/conditional-value-at-risk-calculator')),
    'bond-yield-to-maturity-calculator': dynamic(() => import('@/components/calculators/finance/bond-yield-to-maturity-calculator')),
    'bond-price-calculator': dynamic(() => import('@/components/calculators/finance/bond-price-calculator')),
    'bond-duration-calculator': dynamic(() => import('@/components/calculators/finance/bond-duration-calculator')),
    'bond-convexity-calculator': dynamic(() => import('@/components/calculators/finance/bond-convexity-calculator')),
    'bond-yield-spread-calculator': dynamic(() => import('@/components/calculators/finance/bond-yield-spread-calculator')),
    'yield-to-call-calculator': dynamic(() => import('@/components/calculators/finance/yield-to-call-calculator')),
    'zero-coupon-bond-valuation-calculator': dynamic(() => import('@/components/calculators/finance/zero-coupon-bond-valuation-calculator')),
    'simple-inflation-adjusted-return-calculator': dynamic(() => import('@/components/calculators/finance/simple-inflation-adjusted-return-calculator')),
    'real-rate-of-return-calculator': dynamic(() => import('@/components/calculators/finance/real-rate-of-return-calculator')),
    'margin-of-safety-calculator': dynamic(() => import('@/components/calculators/finance/margin-of-safety-calculator')),
    'overhead-rate-allocation-calculator': dynamic(() => import('@/components/calculators/finance/overhead-rate-allocation-calculator')),
    'activity-based-costing-calculator': dynamic(() => import('@/components/calculators/finance/activity-based-costing-calculator')),
    'depreciation-straight-line-calculator': dynamic(() => import('@/components/calculators/finance/depreciation-straight-line-calculator')),
    'depreciation-double-declining-calculator': dynamic(() => import('@/components/calculators/finance/depreciation-double-declining-calculator')),
    'depreciation-sum-of-years-digits-calculator': dynamic(() => import('@/components/calculators/finance/depreciation-sum-of-years-digits-calculator')),
    'macrs-depreciation-calculator': dynamic(() => import('@/components/calculators/finance/macrs-depreciation-calculator')),
    'amortization-schedule-generator': dynamic(() => import('@/components/calculators/finance/amortization-schedule-generator')),
    'capex-payback-calculator': dynamic(() => import('@/components/calculators/finance/capex-payback-calculator')),
    'sensitivity-analysis-what-if-calculator': dynamic(() => import('@/components/calculators/finance/sensitivity-analysis-what-if-calculator')),
    'scenario-analysis-calculator': dynamic(() => import('@/components/calculators/finance/scenario-analysis-calculator')),
    'currency-exchange-calculator': dynamic(() => import('@/components/calculators/finance/currency-exchange-calculator')),
    'currency-volatility-calculator': dynamic(() => import('@/components/calculators/finance/currency-volatility-calculator')),
    'fixed-vs-floating-rate-calculator': dynamic(() => import('@/components/calculators/finance/fixed-vs-floating-rate-calculator')),
    'swap-spread-calculator': dynamic(() => import('@/components/calculators/finance/swap-spread-calculator')),
    'forward-rate-agreement-calculator': dynamic(() => import('@/components/calculators/finance/forward-rate-agreement-calculator')),
    'breakeven-inflation-rate-calculator': dynamic(() => import('@/components/calculators/finance/breakeven-inflation-rate-calculator')),
    'credit-default-swap-calculator': dynamic(() => import('@/components/calculators/finance/credit-default-swap-calculator')),
    'put-call-parity-calculator': dynamic(() => import('@/components/calculators/finance/put-call-parity-calculator')),
    'dscr-calculator': dynamic(() => import('@/components/calculators/business-startup/dscr-calculator')),
    'break-even-sales-dollar-calculator': dynamic(() => import('@/components/calculators/business-startup/break-even-sales-dollar-calculator')),
    'contribution-margin-calculator': dynamic(() => import('@/components/calculators/business-startup/contribution-margin-calculator')),
    'operating-leverage-calculator': dynamic(() => import('@/components/calculators/business-startup/operating-leverage-calculator')),
    'water-footprint-of-food-calculator': dynamic(() => import('@/components/calculators/health-fitness/water-footprint-of-food-calculator')),
    'bmi-calculator': dynamic(() => import('@/components/calculators/health-fitness/bmi-calculator')),
    'bmr-calculator': dynamic(() => import('@/components/calculators/health-fitness/bmr-calculator')),
    'target-heart-rate-calculator': dynamic(() => import('@/components/calculators/health-fitness/target-heart-rate-calculator')),
    'body-fat-percentage-calculator': dynamic(() => import('@/components/calculators/health-fitness/body-fat-percentage-calculator')),
    'lean-body-mass-calculator': dynamic(() => import('@/components/calculators/health-fitness/lean-body-mass-calculator')),
    'ideal-body-weight-calculator': dynamic(() => import('@/components/calculators/health-fitness/ideal-body-weight-calculator')),
    'waist-to-hip-ratio-calculator': dynamic(() => import('@/components/calculators/health-fitness/waist-to-hip-ratio-calculator')),
    'waist-to-height-ratio-calculator': dynamic(() => import('@/components/calculators/health-fitness/waist-to-height-ratio-calculator')),
    'body-adiposity-index-calculator': dynamic(() => import('@/components/calculators/health-fitness/body-adiposity-index-calculator')),
    'ponderal-index-calculator': dynamic(() => import('@/components/calculators/health-fitness/ponderal-index-calculator')),
    'relative-fat-mass-calculator': dynamic(() => import('@/components/calculators/health-fitness/relative-fat-mass-calculator')),
    'calorie-deficit-calculator': dynamic(() => import('@/components/calculators/health-fitness/calorie-deficit-calculator')),
    'calorie-surplus-calculator': dynamic(() => import('@/components/calculators/health-fitness/calorie-surplus-calculator')),
    'daily-calorie-needs-calculator': dynamic(() => import('@/components/calculators/health-fitness/daily-calorie-needs-calculator')),
    'macro-ratio-calculator': dynamic(() => import('@/components/calculators/health-fitness/macro-ratio-calculator')),
    'protein-intake-calculator': dynamic(() => import('@/components/calculators/health-fitness/protein-intake-calculator')),
    'fat-intake-calculator': dynamic(() => import('@/components/calculators/health-fitness/fat-intake-calculator')),
    'keto-macro-calculator': dynamic(() => import('@/components/calculators/health-fitness/keto-macro-calculator')),
    'intermittent-fasting-calculator': dynamic(() => import('@/components/calculators/health-fitness/intermittent-fasting-calculator')),
    'glycemic-load-calculator': dynamic(() => import('@/components/calculators/health-fitness/glycemic-load-calculator')),
    'meal-glycemic-load-calculator': dynamic(() => import('@/components/calculators/health-fitness/meal-glycemic-load-calculator')),
    'hydration-needs-calculator': dynamic(() => import('@/components/calculators/health-fitness/hydration-needs-calculator')),
    'paint-coverage-calculator': dynamic(() => import('@/components/calculators/home-improvement/paint-coverage-calculator')),
    'tile-flooring-calculator': dynamic(() => import('@/components/calculators/home-improvement/tile-flooring-calculator')),
    'wallpaper-roll-calculator': dynamic(() => import('@/components/calculators/home-improvement/wallpaper-roll-calculator')),
    'drywall-plasterboard-calculator': dynamic(() => import('@/components/calculators/home-improvement/drywall-plasterboard-calculator')),
    'insulation-r-value-calculator': dynamic(() => import('@/components/calculators/home-improvement/insulation-r-value-calculator')),
    'decking-materials-calculator': dynamic(() => import('@/components/calculators/home-improvement/decking-materials-calculator')),
    'roofing-shingle-calculator': dynamic(() => import('@/components/calculators/home-improvement/roofing-shingle-calculator')),
    'concrete-volume-calculator': dynamic(() => import('@/components/calculators/home-improvement/concrete-volume-calculator')),
    'lighting-layout-calculator': dynamic(() => import('@/components/calculators/home-improvement/lighting-layout-calculator')),
    'hvac-sizing-calculator': dynamic(() => import('@/components/calculators/home-improvement/hvac-sizing-calculator')),
    'staircase-rise-run-calculator': dynamic(() => import('@/components/calculators/home-improvement/staircase-rise-run-calculator')),
    'cost-estimator-renovation-calculator': dynamic(() => import('@/components/calculators/home-improvement/cost-estimator-renovation-calculator')),
    'water-usage-plumbing-flow-calculator': dynamic(() => import('@/components/calculators/home-improvement/water-usage-plumbing-flow-calculator')),
    'garden-landscape-soil-mulch-calculator': dynamic(() => import('@/components/calculators/home-improvement/garden-landscape-soil-mulch-calculator')),
    'beam-bending-calculator': dynamic(() => import('@/components/calculators/engineering/beam-bending-calculator')),
    'hydraulic-pipe-flow-calculator': dynamic(() => import('@/components/calculators/engineering/hydraulic-pipe-flow-calculator')),
    'heat-transfer-calculator': dynamic(() => import('@/components/calculators/engineering/heat-transfer-calculator')),
    'electrical-power-calculator': dynamic(() => import('@/components/calculators/engineering/electrical-power-calculator')),
    'compressive-stress-calculator': dynamic(() => import('@/components/calculators/engineering/compressive-stress-calculator')),
    'cantilever-beam-deflection-calculator': dynamic(() => import('@/components/calculators/engineering/cantilever-beam-deflection-calculator')),
    'natural-frequency-calculator': dynamic(() => import('@/components/calculators/engineering/natural-frequency-calculator')),
    'reynolds-number-calculator': dynamic(() => import('@/components/calculators/engineering/reynolds-number-calculator')),
    'thermal-expansion-calculator': dynamic(() => import('@/components/calculators/engineering/thermal-expansion-calculator')),
    'shear-stress-calculator': dynamic(() => import('@/components/calculators/engineering/shear-stress-calculator')),
    'iq-score-estimator': dynamic(() => import('@/components/calculators/cognitive-psychology/iq-score-estimator')),
    'memory-span-calculator': dynamic(() => import('@/components/calculators/cognitive-psychology/memory-span-calculator')),
    'cognitive-load-calculator': dynamic(() => import('@/components/calculators/cognitive-psychology/cognitive-load-calculator')),
    'personality-trait-calculator': dynamic(() => import('@/components/calculators/cognitive-psychology/personality-trait-calculator')),
    'stroop-effect-reaction-time-calculator': dynamic(() => import('@/components/calculators/cognitive-psychology/stroop-effect-reaction-time-calculator')),
    'mental-fatigue-index-calculator': dynamic(() => import('@/components/calculators/cognitive-psychology/mental-fatigue-index-calculator')),
    'sleep-debt-calculator': dynamic(() => import('@/components/calculators/cognitive-psychology/sleep-debt-calculator')),
    'stress-level-index-calculator': dynamic(() => import('@/components/calculators/cognitive-psychology/stress-level-index-calculator')),
    'ancestry-composition-estimator': dynamic(() => import('@/components/calculators/genetic-ancestry/ancestry-composition-estimator')),
    'genetic-trait-probability-calculator': dynamic(() => import('@/components/calculators/genetic-ancestry/genetic-trait-probability-calculator')),
    'pedigree-analysis-calculator': dynamic(() => import('@/components/calculators/genetic-ancestry/pedigree-analysis-calculator')),
    'genealogy-timeline-generator': dynamic(() => import('@/components/calculators/genetic-ancestry/genealogy-timeline-generator')),
    'carbon-footprint-reduction-calculator': dynamic(() => import('@/components/calculators/environment/carbon-footprint-reduction-calculator')),
    'water-usage-efficiency-calculator': dynamic(() => import('@/components/calculators/environment/water-usage-efficiency-calculator')),
    'recycling-impact-calculator': dynamic(() => import('@/components/calculators/environment/recycling-impact-calculator')),
    'sustainable-diet-impact-calculator': dynamic(() => import('@/components/calculators/environment/sustainable-diet-impact-calculator')),
    'backpacking-load-weight-calculator': dynamic(() => import('@/components/calculators/travel-adventure/backpacking-load-weight-calculator')),
    'hiking-elevation-gain-calculator': dynamic(() => import('@/components/calculators/travel-adventure/hiking-elevation-gain-calculator')),
    'travel-budget-estimator': dynamic(() => import('@/components/calculators/travel-adventure/travel-budget-estimator')),
    'adventure-activity-risk-calculator': dynamic(() => import('@/components/calculators/travel-adventure/adventure-activity-risk-calculator')),
    'battery-life-estimator': dynamic(() => import('@/components/calculators/technology/battery-life-estimator')),
    'power-supply-wattage-calculator': dynamic(() => import('@/components/calculators/technology/power-supply-wattage-calculator')),
    'overclocking-thermal-calculator': dynamic(() => import('@/components/calculators/technology/overclocking-thermal-calculator')),
    'network-bandwidth-calculator': dynamic(() => import('@/components/calculators/technology/network-bandwidth-calculator')),
    'ping-latency-distance-calculator': dynamic(() => import('@/components/calculators/technology/ping-latency-distance-calculator')),
    'ups-runtime-calculator': dynamic(() => import('@/components/calculators/technology/ups-runtime-calculator')),
    'internet-data-usage-estimator': dynamic(() => import('@/components/calculators/technology/internet-data-usage-estimator')),
    'disk-raid-capacity-calculator': dynamic(() => import('@/components/calculators/technology/disk-raid-capacity-calculator')),
    'api-rate-limit-planner': dynamic(() => import('@/components/calculators/technology/api-rate-limit-planner')),
    'regex-performance-checker': dynamic(() => import('@/components/calculators/technology/regex-performance-checker')),
    'image-compression-size-calculator': dynamic(() => import('@/components/calculators/technology/image-compression-size-calculator')),
    'password-entropy-calculator': dynamic(() => import('@/components/calculators/technology/password-entropy-calculator')),
    'hash-collision-probability-calculator': dynamic(() => import('@/components/calculators/technology/hash-collision-probability-calculator')),
    'cloud-cost-estimator': dynamic(() => import('@/components/calculators/technology/cloud-cost-estimator')),
    'subnet-mask-cidr-calculator': dynamic(() => import('@/components/calculators/technology/subnet-mask-cidr-calculator')),
    'download-time-calculator': dynamic(() => import('@/components/calculators/technology/download-time-calculator')),
    'latency-to-throughput-calculator': dynamic(() => import('@/components/calculators/technology/latency-to-throughput-calculator')),
    '3d-print-time-material-calculator': dynamic(() => import('@/components/calculators/technology/3d-print-time-material-calculator')),
    'solar-panel-output-calculator': dynamic(() => import('@/components/calculators/technology/solar-panel-output-calculator')),
    'dice-roll-probability': dynamic(() => import('@/components/calculators/fun-games/dice-roll-probability-calculator')),
    'board-game-scoring': dynamic(() => import('@/components/calculators/fun-games/board-game-scoring-calculator')),
    'rpg-character-stat': dynamic(() => import('@/components/calculators/fun-games/rpg-character-stat-calculator')),
    'esports-kd-ratio': dynamic(() => import('@/components/calculators/fun-games/esports-kd-ratio-calculator')),
    'video-game-xp-level-up': dynamic(() => import('@/components/calculators/fun-games/video-game-xp-level-up-calculator')),
    'movie-marathon-time': dynamic(() => import('@/components/calculators/fun-games/movie-marathon-time-calculator')),
    'book-series-reading-time': dynamic(() => import('@/components/calculators/fun-games/book-series-reading-time-calculator')),
    'song-playlist-duration': dynamic(() => import('@/components/calculators/fun-games/song-playlist-duration-calculator')),
    'pop-culture-age': dynamic(() => import('@/components/calculators/fun-games/pop-culture-age-calculator')),
    'emoji-compatibility': dynamic(() => import('@/components/calculators/fun-games/emoji-compatibility-calculator')),
    'random-nickname-generator': dynamic(() => import('@/components/calculators/fun-games/random-nickname-generator-calculator')),
    'friendship-anniversary': dynamic(() => import('@/components/calculators/fun-games/friendship-anniversary-calculator')),
    'bowling-score': dynamic(() => import('@/components/calculators/fun-games/bowling-score-calculator')),
    'golf-handicap': dynamic(() => import('@/components/calculators/fun-games/golf-handicap-calculator')),
    'fantasy-league-points': dynamic(() => import('@/components/calculators/fun-games/fantasy-league-points-calculator')),
    'party-budget-per-person': dynamic(() => import('@/components/calculators/fun-games/party-budget-per-person-calculator')),
    'bbq-food-drink-quantity': dynamic(() => import('@/components/calculators/fun-games/bbq-food-drink-quantity-calculator')),
    'karaoke-queue-time': dynamic(() => import('@/components/calculators/fun-games/karaoke-queue-time-calculator')),
    'recipe-ingredient-converter': dynamic(() => import('@/components/calculators/cooking-food/recipe-ingredient-converter')),
    'cooking-time-adjuster': dynamic(() => import('@/components/calculators/cooking-food/cooking-time-adjuster')),
    'brining-solution-calculator': dynamic(() => import('@/components/calculators/cooking-food/brining-solution-calculator')),
    'meat-thawing-time-calculator': dynamic(() => import('@/components/calculators/cooking-food/meat-thawing-time-calculator')),
    '50-30-20-budget-calculator': dynamic(() => import('@/components/calculators/personal-budgeting/50-30-20-budget-calculator')),
    'monthly-budget-surplus-deficit-calculator': dynamic(() => import('@/components/calculators/personal-budgeting/monthly-budget-surplus-deficit-calculator')),
    'dti-ratio-calculator': dynamic(() => import('@/components/calculators/personal-budgeting/dti-ratio-calculator')),
    'emergency-fund-goal-calculator': dynamic(() => import('@/components/calculators/personal-budgeting/emergency-fund-goal-calculator')),
    'savings-rate-calculator': dynamic(() => import('@/components/calculators/personal-budgeting/savings-rate-calculator')),
    'break-even-point-calculator': dynamic(() => import('@/components/calculators/business-startup/break-even-point-calculator')),
    'customer-acquisition-cost-calculator': dynamic(() => import('@/components/calculators/business-startup/customer-acquisition-cost-calculator')),
    'lifetime-value-calculator': dynamic(() => import('@/components/calculators/business-startup/lifetime-value-calculator')),
    'burn-rate-calculator': dynamic(() => import('@/components/calculators/business-startup/burn-rate-calculator')),
    'roi-calculator': dynamic(() => import('@/components/calculators/business-startup/roi-calculator')),
    'crypto-mining-profitability-calculator': dynamic(() => import('@/components/calculators/crypto-web3/crypto-mining-profitability-calculator')),
    'crypto-tax-liability-calculator': dynamic(() => import('@/components/calculators/crypto-web3/crypto-tax-liability-calculator')),
    'crypto-staking-reward-calculator': dynamic(() => import('@/components/calculators/crypto-web3/crypto-staking-reward-calculator')),
    'nft-minting-cost-calculator': dynamic(() => import('@/components/calculators/crypto-web3/nft-minting-cost-calculator')),
    'crypto-apy-calculator': dynamic(() => import('@/components/calculators/crypto-web3/crypto-apy-calculator')),
    'due-date-calculator': dynamic(() => import('@/components/calculators/parenting/due-date-calculator')),
    'baby-feeding-amount-calculator': dynamic(() => import('@/components/calculators/parenting/baby-feeding-amount-calculator')),
    'college-savings-goal-calculator': dynamic(() => import('@/components/calculators/parenting/college-savings-goal-calculator')),
    'childcare-cost-affordability-calculator': dynamic(() => import('@/components/calculators/parenting/childcare-cost-affordability-calculator')),
    'sports-training-bmi-calculator': dynamic(() => import('@/components/calculators/sports-training/bmi-calculator')),
    'sports-training-bmr-calculator': dynamic(() => import('@/components/calculators/sports-training/bmr-calculator')),
    'sports-training-target-heart-rate-calculator': dynamic(() => import('@/components/calculators/sports-training/target-heart-rate-calculator')),
    'vo2-max-estimation-calculator': dynamic(() => import('@/components/calculators/sports-training/vo2-max-estimation-calculator')),
    'one-rep-max-calculator': dynamic(() => import('@/components/calculators/sports-training/one-rep-max-calculator')),
    'date-difference-calculator': dynamic(() => import('@/components/calculators/time-date/date-difference-calculator')),
    'age-calculator': dynamic(() => import('@/components/calculators/time-date/age-calculator')),
    'world-time-zone-converter': dynamic(() => import('@/components/calculators/time-date/world-time-zone-converter')),
    'day-of-the-week-calculator': dynamic(() => import('@/components/calculators/time-date/day-of-the-week-calculator')),
    'working-days-business-days-calculator': dynamic(() => import('@/components/calculators/time-date/working-days-business-days-calculator')),
    // Biology
    'annealing-temperature-calculator': dynamic(() => import('@/components/calculators/biology/annealing-temperature-calculator')),
    'generation-time-calculator': dynamic(() => import('@/components/calculators/biology/generation-time-calculator')),
    'cell-dilution-calculator': dynamic(() => import('@/components/calculators/biology/cell-dilution-calculator')),
    'cell-doubling-time-calculator': dynamic(() => import('@/components/calculators/biology/cell-doubling-time-calculator')),
    'dna-concentration-calculator': dynamic(() => import('@/components/calculators/biology/dna-concentration-calculator')),
    'ligation-calculator': dynamic(() => import('@/components/calculators/biology/ligation-calculator')),
    'log-reduction-calculator': dynamic(() => import('@/components/calculators/biology/log-reduction-calculator')),
    'protein-concentration-calculator': dynamic(() => import('@/components/calculators/biology/protein-concentration-calculator')),
    'carbohydrate-intake-calculator': dynamic(() => import('@/components/calculators/health-fitness/carbohydrate-intake-calculator')),
    'electrolyte-replacement-calculator': dynamic(() => import('@/components/calculators/health-fitness/electrolyte-replacement-calculator')),
    'alcohol-calorie-impact-calculator': dynamic(() => import('@/components/calculators/health-fitness/alcohol-calorie-impact-calculator')),
    'sugar-intake-calculator': dynamic(() => import('@/components/calculators/health-fitness/sugar-intake-calculator')),
    'caffeine-intake-calculator': dynamic(() => import('@/components/calculators/health-fitness/caffeine-intake-calculator')),
    // Length Conversions
    'meters-to-feet-converter': dynamic(() => import('@/components/calculators/conversions/meters-to-feet-converter')),
    'feet-to-meters-converter': dynamic(() => import('@/components/calculators/conversions/feet-to-meters-converter')),
    'centimeters-to-inches-converter': dynamic(() => import('@/components/calculators/conversions/centimeters-to-inches-converter')),
    'inches-to-centimeters-converter': dynamic(() => import('@/components/calculators/conversions/inches-to-centimeters-converter')),
    'millimeters-to-inches-converter': dynamic(() => import('@/components/calculators/conversions/millimeters-to-inches-converter')),
    'inches-to-millimeters-converter': dynamic(() => import('@/components/calculators/conversions/inches-to-millimeters-converter')),
    'meters-to-yards-converter': dynamic(() => import('@/components/calculators/conversions/meters-to-yards-converter')),
    'yards-to-meters-converter': dynamic(() => import('@/components/calculators/conversions/yards-to-meters-converter')),
    'miles-to-kilometers-converter': dynamic(() => import('@/components/calculators/conversions/miles-to-kilometers-converter')),
    'kilometers-to-miles-converter': dynamic(() => import('@/components/calculators/conversions/kilometers-to-miles-converter')),
    'nautical-miles-to-kilometers-converter': dynamic(() => import('@/components/calculators/conversions/nautical-miles-to-kilometers-converter')),
    'kilometers-to-nautical-miles-converter': dynamic(() => import('@/components/calculators/conversions/kilometers-to-nautical-miles-converter')),
    'micrometers-to-millimeters-converter': dynamic(() => import('@/components/calculators/conversions/micrometers-to-millimeters-converter')),
    'nanometers-to-meters-converter': dynamic(() => import('@/components/calculators/conversions/nanometers-to-meters-converter')),
    'light-years-to-kilometers-converter': dynamic(() => import('@/components/calculators/conversions/light-years-to-kilometers-converter')),
    'parsecs-to-light-years-converter': dynamic(() => import('@/components/calculators/conversions/parsecs-to-light-years-converter')),
    'astronomical-units-to-kilometers-converter': dynamic(() => import('@/components/calculators/conversions/astronomical-units-to-kilometers-converter')),
    'fathoms-to-meters-converter': dynamic(() => import('@/components/calculators/conversions/fathoms-to-meters-converter')),
    'chains-to-meters-converter': dynamic(() => import('@/components/calculators/conversions/chains-to-meters-converter')),
    'rods-to-feet-converter': dynamic(() => import('@/components/calculators/conversions/rods-to-feet-converter')),
    // Area Conversions
    'square-meters-to-square-feet-converter': dynamic(() => import('@/components/calculators/conversions/square-meters-to-square-feet-converter')),
    'square-feet-to-square-meters-converter': dynamic(() => import('@/components/calculators/conversions/square-feet-to-square-meters-converter')),
    'square-kilometers-to-square-miles-converter': dynamic(() => import('@/components/calculators/conversions/square-kilometers-to-square-miles-converter')),
    'square-miles-to-square-kilometers-converter': dynamic(() => import('@/components/calculators/conversions/square-miles-to-square-kilometers-converter')),
    'acres-to-square-meters-converter': dynamic(() => import('@/components/calculators/conversions/acres-to-square-meters-converter')),
    'square-meters-to-acres-converter': dynamic(() => import('@/components/calculators/conversions/square-meters-to-acres-converter')),
    'hectares-to-acres-converter': dynamic(() => import('@/components/calculators/conversions/hectares-to-acres-converter')),
    'acres-to-hectares-converter': dynamic(() => import('@/components/calculators/conversions/acres-to-hectares-converter')),
    'square-yards-to-square-feet-converter': dynamic(() => import('@/components/calculators/conversions/square-yards-to-square-feet-converter')),
    'square-feet-to-square-yards-converter': dynamic(() => import('@/components/calculators/conversions/square-feet-to-square-yards-converter')),
    'square-inches-to-square-centimeters-converter': dynamic(() => import('@/components/calculators/conversions/square-inches-to-square-centimeters-converter')),
    'square-centimeters-to-square-inches-converter': dynamic(() => import('@/components/calculators/conversions/square-centimeters-to-square-inches-converter')),
    'square-miles-to-acres-converter': dynamic(() => import('@/components/calculators/conversions/square-miles-to-acres-converter')),
    'acres-to-square-miles-converter': dynamic(() => import('@/components/calculators/conversions/acres-to-square-miles-converter')),
    'square-meters-to-square-yards-converter': dynamic(() => import('@/components/calculators/conversions/square-meters-to-square-yards-converter')),
    'square-yards-to-square-meters-converter': dynamic(() => import('@/components/calculators/conversions/square-yards-to-square-meters-converter')),
    'square-centimeters-to-square-meters-converter': dynamic(() => import('@/components/calculators/conversions/square-centimeters-to-square-meters-converter')),
    'square-meters-to-square-centimeters-converter': dynamic(() => import('@/components/calculators/conversions/square-meters-to-square-centimeters-converter')),
    'hectares-to-square-kilometers-converter': dynamic(() => import('@/components/calculators/conversions/hectares-to-square-kilometers-converter')),
    'square-kilometers-to-hectares-converter': dynamic(() => import('@/components/calculators/conversions/square-kilometers-to-hectares-converter')),
  };
  
export default function CalculatorPage({ params }: { params: { slug: string; calcSlug: string } }) {
  const category = categories.find((c) => c.slug === params.slug);
  const calculator = calculators.find(
    (calc) => calc.category === params.slug && calc.slug === params.calcSlug
  );

  if (!category || !calculator) {
    notFound();
  }

  const CalculatorComponent = calculatorComponents[calculator.slug] ?? null;

  return (
    <div className="flex flex-col items-center min-h-screen bg-background p-4 sm:p-8">
      <div className="w-full max-w-4xl">
        <div className="mb-8">
          <Button asChild variant="ghost" className="mb-4">
            <Link href={`/category/${category.slug}`}>
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to {category.name}
            </Link>
          </Button>
          <div className="flex items-center gap-4">
            <CategoryIcon name={category.Icon} className="h-12 w-12 text-primary" strokeWidth={1.5} />
            <div>
              <h1 className="text-3xl md:text-4xl font-bold text-foreground">
                {calculator.name}
              </h1>
              <p className="text-muted-foreground mt-1">{calculator.description}</p>
            </div>
          </div>
        </div>
        <Card>
          <CardContent className='pt-6'>
            {CalculatorComponent ? <CalculatorComponent /> : <p>Calculator component not found.</p>}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
