'use client';

import React, { lazy, useState, useEffect } from 'react';

// Static map of calculators to avoid dynamic import context creation
const components: Record<string, React.LazyExoticComponent<React.ComponentType<any>>> = {
  'baseball-batting-average-calculator-interactive': lazy(() => import('./baseball-batting-average-calculator-interactive')),
  'baseball-batting-average-calculator': lazy(() => import('./baseball-batting-average-calculator')),
  'baseball-era-calculator-interactive': lazy(() => import('./baseball-era-calculator-interactive')),
  'baseball-era-calculator': lazy(() => import('./baseball-era-calculator')),
  'baseball-fielding-percentage-calculator-interactive': lazy(() => import('./baseball-fielding-percentage-calculator-interactive')),
  'baseball-fielding-percentage-calculator': lazy(() => import('./baseball-fielding-percentage-calculator')),
  'baseball-on-base-percentage-calculator-interactive': lazy(() => import('./baseball-on-base-percentage-calculator-interactive')),
  'baseball-on-base-percentage-calculator': lazy(() => import('./baseball-on-base-percentage-calculator')),
  'baseball-ops-calculator-interactive': lazy(() => import('./baseball-ops-calculator-interactive')),
  'baseball-ops-calculator': lazy(() => import('./baseball-ops-calculator')),
  'baseball-pitch-efficiency-calculator-interactive': lazy(() => import('./baseball-pitch-efficiency-calculator-interactive')),
  'baseball-pitch-efficiency-calculator': lazy(() => import('./baseball-pitch-efficiency-calculator')),
  'baseball-run-differential-calculator-interactive': lazy(() => import('./baseball-run-differential-calculator-interactive')),
  'baseball-run-differential-calculator': lazy(() => import('./baseball-run-differential-calculator')),
  'baseball-slugging-percentage-calculator-interactive': lazy(() => import('./baseball-slugging-percentage-calculator-interactive')),
  'baseball-slugging-percentage-calculator': lazy(() => import('./baseball-slugging-percentage-calculator')),
  'baseball-strikeout-to-walk-ratio-calculator-interactive': lazy(() => import('./baseball-strikeout-to-walk-ratio-calculator-interactive')),
  'baseball-strikeout-to-walk-ratio-calculator': lazy(() => import('./baseball-strikeout-to-walk-ratio-calculator')),
  'baseball-team-batting-average-calculator-interactive': lazy(() => import('./baseball-team-batting-average-calculator-interactive')),
  'baseball-team-batting-average-calculator': lazy(() => import('./baseball-team-batting-average-calculator')),
  'baseball-whip-calculator-interactive': lazy(() => import('./baseball-whip-calculator-interactive')),
  'baseball-whip-calculator': lazy(() => import('./baseball-whip-calculator')),
  'baseball-win-loss-percentage-calculator-interactive': lazy(() => import('./baseball-win-loss-percentage-calculator-interactive')),
  'baseball-win-loss-percentage-calculator': lazy(() => import('./baseball-win-loss-percentage-calculator')),
  'basketball-assist-to-turnover-ratio-calculator-interactive': lazy(() => import('./basketball-assist-to-turnover-ratio-calculator-interactive')),
  'basketball-assist-to-turnover-ratio-calculator': lazy(() => import('./basketball-assist-to-turnover-ratio-calculator')),
  'basketball-defensive-efficiency-calculator-interactive': lazy(() => import('./basketball-defensive-efficiency-calculator-interactive')),
  'basketball-defensive-efficiency-calculator': lazy(() => import('./basketball-defensive-efficiency-calculator')),
  'basketball-field-goal-percentage-calculator-interactive': lazy(() => import('./basketball-field-goal-percentage-calculator-interactive')),
  'basketball-field-goal-percentage-calculator': lazy(() => import('./basketball-field-goal-percentage-calculator')),
  'basketball-free-throw-percentage-calculator-interactive': lazy(() => import('./basketball-free-throw-percentage-calculator-interactive')),
  'basketball-free-throw-percentage-calculator': lazy(() => import('./basketball-free-throw-percentage-calculator')),
  'basketball-offensive-efficiency-calculator-interactive': lazy(() => import('./basketball-offensive-efficiency-calculator-interactive')),
  'basketball-offensive-efficiency-calculator': lazy(() => import('./basketball-offensive-efficiency-calculator')),
  'basketball-player-efficiency-rating-calculator-interactive': lazy(() => import('./basketball-player-efficiency-rating-calculator-interactive')),
  'basketball-player-efficiency-rating-calculator': lazy(() => import('./basketball-player-efficiency-rating-calculator')),
  'basketball-points-per-possession-calculator-interactive': lazy(() => import('./basketball-points-per-possession-calculator-interactive')),
  'basketball-points-per-possession-calculator': lazy(() => import('./basketball-points-per-possession-calculator')),
  'basketball-rebound-rate-calculator-interactive': lazy(() => import('./basketball-rebound-rate-calculator-interactive')),
  'basketball-rebound-rate-calculator': lazy(() => import('./basketball-rebound-rate-calculator')),
  'basketball-three-point-percentage-calculator-interactive': lazy(() => import('./basketball-three-point-percentage-calculator-interactive')),
  'basketball-three-point-percentage-calculator': lazy(() => import('./basketball-three-point-percentage-calculator')),
  'basketball-true-shooting-percentage-calculator-interactive': lazy(() => import('./basketball-true-shooting-percentage-calculator-interactive')),
  'basketball-true-shooting-percentage-calculator': lazy(() => import('./basketball-true-shooting-percentage-calculator')),
  'basketball-usage-rate-calculator-interactive': lazy(() => import('./basketball-usage-rate-calculator-interactive')),
  'basketball-usage-rate-calculator': lazy(() => import('./basketball-usage-rate-calculator')),
  'basketball-win-shares-calculator-interactive': lazy(() => import('./basketball-win-shares-calculator-interactive')),
  'basketball-win-shares-calculator': lazy(() => import('./basketball-win-shares-calculator')),
  'batting-average-calculator-interactive': lazy(() => import('./batting-average-calculator-interactive')),
  'batting-average-calculator': lazy(() => import('./batting-average-calculator')),
  'boundary-percentage-calculator-interactive': lazy(() => import('./boundary-percentage-calculator-interactive')),
  'boundary-percentage-calculator': lazy(() => import('./boundary-percentage-calculator')),
  'bowling-average-calculator-interactive': lazy(() => import('./bowling-average-calculator-interactive')),
  'bowling-average-calculator': lazy(() => import('./bowling-average-calculator')),
  'bowling-economy-rate-calculator-interactive': lazy(() => import('./bowling-economy-rate-calculator-interactive')),
  'bowling-economy-rate-calculator': lazy(() => import('./bowling-economy-rate-calculator')),
  'bowling-strike-rate-calculator-interactive': lazy(() => import('./bowling-strike-rate-calculator-interactive')),
  'bowling-strike-rate-calculator': lazy(() => import('./bowling-strike-rate-calculator')),
  'cricket-fantasy-points-calculator-interactive': lazy(() => import('./cricket-fantasy-points-calculator-interactive')),
  'cricket-fantasy-points-calculator': lazy(() => import('./cricket-fantasy-points-calculator')),
  'cricket-partnership-run-rate-calculator-interactive': lazy(() => import('./cricket-partnership-run-rate-calculator-interactive')),
  'cricket-partnership-run-rate-calculator': lazy(() => import('./cricket-partnership-run-rate-calculator')),
  'cricket-player-performance-index-calculator-interactive': lazy(() => import('./cricket-player-performance-index-calculator-interactive')),
  'cricket-player-performance-index-calculator': lazy(() => import('./cricket-player-performance-index-calculator')),
  'cricket-win-probability-calculator-interactive': lazy(() => import('./cricket-win-probability-calculator-interactive')),
  'cricket-win-probability-calculator': lazy(() => import('./cricket-win-probability-calculator')),
  'dot-ball-percentage-calculator-interactive': lazy(() => import('./dot-ball-percentage-calculator-interactive')),
  'dot-ball-percentage-calculator': lazy(() => import('./dot-ball-percentage-calculator')),
  'football-assists-per-90-calculator-interactive': lazy(() => import('./football-assists-per-90-calculator-interactive')),
  'football-assists-per-90-calculator': lazy(() => import('./football-assists-per-90-calculator')),
  'football-clean-sheet-percentage-calculator-interactive': lazy(() => import('./football-clean-sheet-percentage-calculator-interactive')),
  'football-clean-sheet-percentage-calculator': lazy(() => import('./football-clean-sheet-percentage-calculator')),
  'football-expected-assists-calculator-interactive': lazy(() => import('./football-expected-assists-calculator-interactive')),
  'football-expected-assists-calculator': lazy(() => import('./football-expected-assists-calculator')),
  'football-expected-goals-calculator-interactive': lazy(() => import('./football-expected-goals-calculator-interactive')),
  'football-expected-goals-calculator': lazy(() => import('./football-expected-goals-calculator')),
  'football-fantasy-points-calculator-interactive': lazy(() => import('./football-fantasy-points-calculator-interactive')),
  'football-fantasy-points-calculator': lazy(() => import('./football-fantasy-points-calculator')),
  'football-goal-conversion-rate-calculator-interactive': lazy(() => import('./football-goal-conversion-rate-calculator-interactive')),
  'football-goal-conversion-rate-calculator': lazy(() => import('./football-goal-conversion-rate-calculator')),
  'football-goals-per-90-minutes-calculator-interactive': lazy(() => import('./football-goals-per-90-minutes-calculator-interactive')),
  'football-goals-per-90-minutes-calculator': lazy(() => import('./football-goals-per-90-minutes-calculator')),
  'football-league-standing-probability-calculator-interactive': lazy(() => import('./football-league-standing-probability-calculator-interactive')),
  'football-league-standing-probability-calculator': lazy(() => import('./football-league-standing-probability-calculator')),
  'football-offside-frequency-calculator-interactive': lazy(() => import('./football-offside-frequency-calculator-interactive')),
  'football-offside-frequency-calculator': lazy(() => import('./football-offside-frequency-calculator')),
  'football-pass-accuracy-calculator-interactive': lazy(() => import('./football-pass-accuracy-calculator-interactive')),
  'football-pass-accuracy-calculator': lazy(() => import('./football-pass-accuracy-calculator')),
  'football-possession-percentage-calculator-interactive': lazy(() => import('./football-possession-percentage-calculator-interactive')),
  'football-possession-percentage-calculator': lazy(() => import('./football-possession-percentage-calculator')),
  'football-save-percentage-calculator-interactive': lazy(() => import('./football-save-percentage-calculator-interactive')),
  'football-save-percentage-calculator': lazy(() => import('./football-save-percentage-calculator')),
  'football-shot-accuracy-calculator-interactive': lazy(() => import('./football-shot-accuracy-calculator-interactive')),
  'football-shot-accuracy-calculator': lazy(() => import('./football-shot-accuracy-calculator')),
  'football-team-points-per-game-calculator-interactive': lazy(() => import('./football-team-points-per-game-calculator-interactive')),
  'football-team-points-per-game-calculator': lazy(() => import('./football-team-points-per-game-calculator')),
  'football-win-rate-calculator-interactive': lazy(() => import('./football-win-rate-calculator-interactive')),
  'football-win-rate-calculator': lazy(() => import('./football-win-rate-calculator')),
  'match-impact-score-calculator-interactive': lazy(() => import('./match-impact-score-calculator-interactive')),
  'match-impact-score-calculator': lazy(() => import('./match-impact-score-calculator')),
  'over-economy-tracker-interactive': lazy(() => import('./over-economy-tracker-interactive')),
  'over-economy-tracker': lazy(() => import('./over-economy-tracker')),
  'powerplay-run-rate-calculator-interactive': lazy(() => import('./powerplay-run-rate-calculator-interactive')),
  'powerplay-run-rate-calculator': lazy(() => import('./powerplay-run-rate-calculator')),
  'required-run-rate-calculator-interactive': lazy(() => import('./required-run-rate-calculator-interactive')),
  'required-run-rate-calculator': lazy(() => import('./required-run-rate-calculator')),
  'run-contribution-percentage-calculator-interactive': lazy(() => import('./run-contribution-percentage-calculator-interactive')),
  'run-contribution-percentage-calculator': lazy(() => import('./run-contribution-percentage-calculator')),
  'strike-rate-calculator-interactive': lazy(() => import('./strike-rate-calculator-interactive')),
  'strike-rate-calculator': lazy(() => import('./strike-rate-calculator')),
  'team-batting-average-calculator-interactive': lazy(() => import('./team-batting-average-calculator-interactive')),
  'team-batting-average-calculator': lazy(() => import('./team-batting-average-calculator')),
  'team-run-rate-calculator-interactive': lazy(() => import('./team-run-rate-calculator-interactive')),
  'team-run-rate-calculator': lazy(() => import('./team-run-rate-calculator')),
  'tennis-aces-per-match-calculator-interactive': lazy(() => import('./tennis-aces-per-match-calculator-interactive')),
  'tennis-aces-per-match-calculator': lazy(() => import('./tennis-aces-per-match-calculator')),
  'tennis-break-point-conversion-rate-calculator-interactive': lazy(() => import('./tennis-break-point-conversion-rate-calculator-interactive')),
  'tennis-break-point-conversion-rate-calculator': lazy(() => import('./tennis-break-point-conversion-rate-calculator')),
  'tennis-double-fault-percentage-calculator-interactive': lazy(() => import('./tennis-double-fault-percentage-calculator-interactive')),
  'tennis-double-fault-percentage-calculator': lazy(() => import('./tennis-double-fault-percentage-calculator')),
  'tennis-elo-rating-calculator-interactive': lazy(() => import('./tennis-elo-rating-calculator-interactive')),
  'tennis-elo-rating-calculator': lazy(() => import('./tennis-elo-rating-calculator')),
  'tennis-first-serve-percentage-calculator-interactive': lazy(() => import('./tennis-first-serve-percentage-calculator-interactive')),
  'tennis-first-serve-percentage-calculator': lazy(() => import('./tennis-first-serve-percentage-calculator')),
  'tennis-hold-percentage-calculator-interactive': lazy(() => import('./tennis-hold-percentage-calculator-interactive')),
  'tennis-hold-percentage-calculator': lazy(() => import('./tennis-hold-percentage-calculator')),
  'tennis-return-points-won-calculator-interactive': lazy(() => import('./tennis-return-points-won-calculator-interactive')),
  'tennis-return-points-won-calculator': lazy(() => import('./tennis-return-points-won-calculator')),
  'tennis-serve-accuracy-calculator-interactive': lazy(() => import('./tennis-serve-accuracy-calculator-interactive')),
  'tennis-serve-accuracy-calculator': lazy(() => import('./tennis-serve-accuracy-calculator')),
  'tennis-set-win-percentage-calculator-interactive': lazy(() => import('./tennis-set-win-percentage-calculator-interactive')),
  'tennis-set-win-percentage-calculator': lazy(() => import('./tennis-set-win-percentage-calculator')),
  'tennis-win-ratio-calculator-interactive': lazy(() => import('./tennis-win-ratio-calculator-interactive')),
  'tennis-win-ratio-calculator': lazy(() => import('./tennis-win-ratio-calculator')),
  'volleyball-attack-success-rate-calculator-interactive': lazy(() => import('./volleyball-attack-success-rate-calculator-interactive')),
  'volleyball-attack-success-rate-calculator': lazy(() => import('./volleyball-attack-success-rate-calculator')),
  'volleyball-serve-efficiency-calculator-interactive': lazy(() => import('./volleyball-serve-efficiency-calculator-interactive')),
  'volleyball-serve-efficiency-calculator': lazy(() => import('./volleyball-serve-efficiency-calculator')),
};

export default function CalculatorRegistry({ calculatorSlug }: { calculatorSlug: string }) {
  const Component = components[calculatorSlug];

  if (!Component) {
    console.warn(`Calculator not found in registry: ${calculatorSlug}`);
    return <div className="p-8 text-center text-muted-foreground">Calculator not found.</div>;
  }

  return <Component />;
}
