export interface Calculator {
  id: number;
  name: string;
  description: string;
  slug: string;
  category: string;
}

export const calculators: Calculator[] = [
  // Finance
  {
    id: 95,
    name: 'SIP/DCA Return Calculator',
    description: 'Project the future value of your Systematic Investment Plan (SIP) or Dollar-Cost Averaging (DCA) strategy. See how regular, disciplined investing can help you reach your financial goals.',
    slug: 'sip-calculator',
    category: 'finance',
  },
  {
    id: 96,
    name: 'Loan/EMI Calculator',
    description: 'Calculate your monthly payment (EMI) for any loan, including mortgages, auto loans, or personal loans. Understand your repayment schedule with a detailed amortization graph.',
    slug: 'loan-emi-calculator',
    category: 'finance',
  },
  {
    id: 97,
    name: 'Retirement Savings Calculator',
    description: 'Plan for your future by estimating your retirement corpus based on current savings, contributions, and expected returns. Find out if you are on track to meet your retirement goals.',
    slug: 'retirement-savings-calculator',
    category: 'finance',
  },
  {
    id: 98,
    name: 'Compound Interest Calculator',
    description: 'Calculate the future value of an investment using the power of compound interest. Visualize how your savings can grow over time with different compounding frequencies.',
    slug: 'compound-interest-calculator',
    category: 'finance'
  },
  {
    id: 99,
    name: '401(k) Contribution Calculator',
    description: 'Estimate your 401(k) growth by retirement, including your contributions, employer match, and investment returns. Visualize your path to a secure retirement.',
    slug: '401k-contribution-calculator',
    category: 'finance',
  },
  {
    id: 100,
    name: 'Net Worth Calculator',
    description: 'Get a clear picture of your financial health by calculating your net worth. Track your assets and liabilities to understand your overall wealth and financial progress.',
    slug: 'net-worth-calculator',
    category: 'finance',
  },
  {
    id: 101,
    name: 'Credit Card Payoff Calculator',
    description: 'Find out how long it will take to pay off your credit card balance based on your monthly payment. See the total interest you\'ll pay and get a plan to become debt-free.',
    slug: 'credit-card-payoff-calculator',
    category: 'finance',
  },
  {
    id: 102,
    name: 'Mortgage Payment Calculator',
    description: 'Estimate your monthly mortgage payment. See how principal, interest, and loan term affect your payment and view a detailed amortization schedule.',
    slug: 'mortgage-payment-calculator',
    category: 'finance',
  },
  {
    id: 103,
    name: 'Student Loan Repayment Calculator',
    description: 'Understand your student loan repayment options. Calculate your monthly payment and the total interest you\'ll pay over the life of the loan.',
    slug: 'student-loan-repayment-calculator',
    category: 'finance',
  },
  {
    id: 104,
    name: 'Inflation Calculator',
    description: 'See how the value of your money may decrease over time due to inflation. Understand the future purchasing power of your savings.',
    slug: 'inflation-calculator',
    category: 'finance',
  },
  {
    id: 105,
    name: 'Roth IRA Contribution Limit Calculator',
    description: 'Determine your maximum allowed contribution for the current tax year based on your income, filing status, and age.',
    slug: 'roth-ira-contribution-limit-calculator',
    category: 'finance',
  },
  {
    id: 159,
    name: 'Present Value (PV) Calculator',
    description: 'Calculate the current worth of a future sum of money. This is a fundamental concept in finance that allows you to evaluate whether an investment is worth making today by understanding what a future cash flow is worth in today\'s dollars.',
    slug: 'present-value-calculator',
    category: 'finance',
  },
  {
    id: 160,
    name: 'Future Value (FV) Calculator',
    description: 'Project the future worth of a current investment given a specific rate of return. This tool helps you visualize how your money can grow over time, demonstrating the power of compounding interest on your initial savings.',
    slug: 'future-value-calculator',
    category: 'finance',
  },
  {
    id: 161,
    name: 'Annuity Payment Calculator',
    description: 'Determine the fixed periodic payment required for a loan or to reach a specified future savings goal. This is useful for understanding mortgage payments, car loans, or planning contributions for a retirement fund.',
    slug: 'annuity-payment-calculator',
    category: 'finance',
  },
  {
    id: 162,
    name: 'Perpetuity Calculator',
    description: 'Calculate the present value of an infinite series of equal payments. While a theoretical concept, it is crucial in finance for valuing assets with indefinite cash flows, such as preferred stocks or certain types of real estate.',
    slug: 'perpetuity-calculator',
    category: 'finance',
  },
  {
    id: 163,
    name: 'Growing Annuity/Perpetuity Calculator',
    description: 'Value a stream of cash flows that is expected to grow at a constant rate, either for a finite number of periods (annuity) or indefinitely (perpetuity). This is useful for valuing dividend-paying stocks or rental income that is projected to increase over time.',
    slug: 'growing-annuity-calculator',
    category: 'finance',
  },
  {
    id: 165,
    name: 'Net Present Value (NPV) Calculator',
    description: 'Determine the difference between the present value of cash inflows and the present value of cash outflows over a period of time. A positive NPV indicates a profitable investment, making it a critical tool for capital budgeting.',
    slug: 'npv-calculator',
    category: 'finance',
  },
  {
    id: 166,
    name: 'Discount Rate Calculator',
    description: 'Estimate the required rate of return for an investment using the Capital Asset Pricing Model (CAPM). This helps in assessing the risk and potential return of an asset compared to the overall market.',
    slug: 'discount-rate-calculator',
    category: 'finance'
  },
  {
    id: 167,
    name: 'Discounted Cash Flow (DCF) Calculator',
    description: 'Estimate the intrinsic value of an investment or a company based on its expected future cash flows. DCF analysis helps you determine if an asset is undervalued or overvalued in the current market.',
    slug: 'dcf-calculator',
    category: 'finance',
  },
  {
    id: 168,
    name: 'Payback Period Calculator',
    description: 'Determine the length of time required for an investment to generate cash flows sufficient to recover its initial cost. This is a simple way to assess the risk and liquidity of a project.',
    slug: 'payback-period-calculator',
    category: 'finance',
  },
  {
    id: 169,
    name: 'Price-to-Earnings (P/E) Ratio Calculator',
    description: 'Calculate the P/E ratio to gauge a company\'s valuation, indicating how much investors are willing to pay per dollar of earnings. A key metric for value investing.',
    slug: 'price-to-earnings-ratio-calculator',
    category: 'finance'
  },
  {
    id: 170,
    name: 'Earnings per Share (EPS) Calculator',
    description: 'Determine a company\'s profitability on a per-share basis. EPS is a fundamental metric used in calculating the P/E ratio and assessing a company\'s financial health.',
    slug: 'earnings-per-share-calculator',
    category: 'finance'
  },
  {
    id: 171,
    name: 'Return on Equity (ROE) Calculator',
    description: 'Measure how effectively a company is using its shareholders\' equity to generate profits. A high ROE can indicate strong management efficiency and profitability.',
    slug: 'return-on-equity-calculator',
    category: 'finance'
  },
  {
    id: 172,
    name: 'Return on Assets (ROA) Calculator',
    description: 'Evaluate how efficiently a company is using its total assets to generate earnings. ROA provides insight into a company\'s operational performance and asset management.',
    slug: 'return-on-assets-calculator',
    category: 'finance'
  },
  {
    id: 173,
    name: 'Return on Investment (ROI) Calculator',
    description: 'Calculate the percentage return on an investment relative to its cost. ROI is a universal metric for evaluating the profitability of any investment.',
    slug: 'return-on-investment-calculator',
    category: 'finance'
  },
  {
    id: 174,
    name: 'Debt-to-Equity Ratio Calculator',
    description: 'Measures a company’s financial leverage by comparing its total liabilities to its shareholders\' equity. A higher ratio indicates more debt financing, which can mean higher risk but also potentially higher returns.',
    slug: 'debt-to-equity-ratio-calculator',
    category: 'finance'
  },
  {
    id: 175,
    name: 'Interest Coverage Ratio Calculator',
    description: 'Shows how easily a company can pay the interest on its outstanding debt. A higher ratio indicates a better ability to meet its interest obligations, signaling lower risk to creditors and investors.',
    slug: 'interest-coverage-ratio-calculator',
    category: 'finance'
  },
  {
    id: 176,
    name: 'Current Ratio Calculator',
    description: 'Evaluates a company’s short-term liquidity by comparing all of its current assets to its current liabilities. It indicates a company\'s ability to pay back its short-term obligations.',
    slug: 'current-ratio-calculator',
    category: 'finance'
  },
  {
    id: 177,
    name: 'Quick Ratio (Acid-Test) Calculator',
    description: 'Measures a company’s ability to meet its short-term obligations with its most liquid assets, excluding less liquid inventory. It provides a more conservative measure of liquidity than the current ratio.',
    slug: 'quick-ratio-calculator',
    category: 'finance'
  },
  {
    id: 178,
    name: 'Working Capital Calculator',
    description: 'Indicates the liquidity available to a business to meet its short-term obligations. Positive working capital means you have enough assets to cover liabilities, while negative working capital can be a sign of financial trouble.',
    slug: 'working-capital-calculator',
    category: 'finance'
  },
  {
    id: 179,
    name: 'Cash Conversion Cycle (CCC) Calculator',
    description: 'Measures the time it takes for a company to convert its investments in inventory and other resources into cash from sales, indicating working capital efficiency.',
    slug: 'cash-conversion-cycle-calculator',
    category: 'finance',
  },
  {
    id: 180,
    name: 'Free Cash Flow (FCF) Calculator',
    description: 'Calculates the cash a company generates after accounting for capital expenditures, showing the cash available for distribution to investors or to reinvest.',
    slug: 'free-cash-flow-calculator',
    category: 'finance',
  },
  {
    id: 181,
    name: 'Operating Margin Calculator',
    description: 'Determines the profitability of a company\'s core business operations before deducting interest and taxes, expressed as a percentage of revenue.',
    slug: 'operating-margin-calculator',
    category: 'finance',
  },
  {
    id: 182,
    name: 'Gross Margin Calculator',
    description: 'Calculates the percentage of revenue that exceeds the cost of goods sold (COGS), providing insight into a company\'s production efficiency.',
    slug: 'gross-margin-calculator',
    category: 'finance',
  },
  {
    id: 183,
    name: 'Net Profit Margin Calculator',
    description: 'Measures how much net income is generated as a percentage of revenue. It is the ratio of net profits to revenues for a company or business segment.',
    slug: 'net-profit-margin-calculator',
    category: 'finance',
  },
  {
    id: 184,
    name: 'EBITDA / EBIT Calculator',
    description: 'Measure a company’s earnings before interest, taxes, depreciation, and amortization (EBITDA) or before only interest and taxes (EBIT).',
    slug: 'ebitda-ebit-calculator',
    category: 'finance',
  },
  {
    id: 185,
    name: 'Enterprise Value (EV) Calculator',
    description: 'Represents the total value of a company, including debt and cash, often used in valuation.',
    slug: 'enterprise-value-calculator',
    category: 'finance',
  },
  {
    id: 186,
    name: 'EV / EBIT and EV / EBITDA Multiple Calculator',
    description: 'Key valuation multiples comparing Enterprise Value (EV) to EBIT or EBITDA.',
    slug: 'ev-ebit-ebitda-multiple-calculator',
    category: 'finance',
  },
  {
    id: 188,
    name: 'Sharpe Ratio Calculator',
    description: 'Evaluates risk-adjusted return of an investment.',
    slug: 'sharpe-ratio-calculator',
    category: 'finance',
  },
  {
    id: 189,
    name: 'Sortino Ratio Calculator',
    description: 'Similar to Sharpe ratio but penalizes only downside risk.',
    slug: 'sortino-ratio-calculator',
    category: 'finance',
  },
  {
    id: 190,
    name: 'Treynor Ratio Calculator',
    description: 'Measures risk-adjusted return based on systematic risk (beta).',
    slug: 'treynor-ratio-calculator',
    category: 'finance',
  },
  {
    id: 191,
    name: 'Alpha (Investment) Calculator',
    description: 'Indicates the excess return of an investment relative to its expected performance based on market risk.',
    slug: 'alpha-investment-calculator',
    category: 'finance',
  },
  {
    id: 192,
    name: 'Volatility / Standard Deviation Calculator',
    description: 'Measures the dispersion of returns around the mean.',
    slug: 'volatility-standard-deviation-calculator',
    category: 'finance',
  },
  {
    id: 193,
    name: 'Correlation Coefficient Calculator',
    description: 'Measures the strength and direction of relationship between two assets’ returns.',
    slug: 'correlation-coefficient-calculator',
    category: 'finance',
  },
  {
    id: 194,
    name: 'Beta (Asset) Calculator',
    description: 'Measures an asset’s volatility relative to the market (systematic risk).',
    slug: 'beta-asset-calculator',
    category: 'finance',
  },
  {
    id: 195,
    name: 'Portfolio Variance / Risk Calculator',
    description: 'Measures the overall risk (variance) of a multi-asset portfolio.',
    slug: 'portfolio-variance-calculator',
    category: 'finance',
  },
  {
    id: 196,
    name: 'Portfolio Expected Return Calculator',
    description: 'Estimates the weighted average expected return of a portfolio.',
    slug: 'portfolio-expected-return-calculator',
    category: 'finance',
  },
  {
    id: 197,
    name: 'Capital Asset Pricing Model (CAPM) Calculator',
    description: 'Calculates the expected return of an asset using market risk.',
    slug: 'capm-calculator',
    category: 'finance',
  },
  {
    id: 198,
    name: 'WACC Calculator',
    description: 'Computes a firm’s average cost of capital from equity and debt.',
    slug: 'wacc-calculator',
    category: 'finance',
  },
  {
    id: 199,
    name: 'Leverage / Debt Ratio Impact Calculator',
    description: 'Examines how changing debt levels affect a company’s return on equity or earnings per share.',
    slug: 'leverage-debt-ratio-calculator',
    category: 'finance',
  },
  {
    id: 200,
    name: 'Option Pricing – Black-Scholes Calculator',
    description: 'Determines the theoretical value of a European call or put option.',
    slug: 'black-scholes-calculator',
    category: 'finance',
  },
  {
    id: 202,
    name: 'Put / Call Option Payoff Calculator',
    description: 'Shows the profit or loss of a call or put at different underlying prices at expiration.',
    slug: 'option-payoff-calculator',
    category: 'finance',
  },
  {
    id: 203,
    name: 'Binomial Option Pricing Model Calculator',
    description: 'Prices options using a multi-period binomial tree.',
    slug: 'binomial-option-pricing-calculator',
    category: 'finance',
  },
  {
    id: 204,
    name: 'Monte Carlo Simulation for Portfolio Value Calculator',
    description: 'Uses random sampling to estimate the probability distribution of future portfolio values.',
    slug: 'monte-carlo-portfolio-calculator',
    category: 'finance',
  },
  {
    id: 205,
    name: 'Value at Risk (VaR) Calculator',
    description: 'Estimate the maximum potential loss a portfolio could experience over a specific time period.',
    slug: 'value-at-risk-calculator',
    category: 'finance',
  },
  {
    id: 206,
    name: 'Conditional VaR (CVaR) / Expected Shortfall Calculator',
    description: 'Measure the average loss that can be expected if the VaR threshold is breached.',
    slug: 'conditional-value-at-risk-calculator',
    category: 'finance',
  },
  {
    id: 207,
    name: 'Bond Yield to Maturity (YTM) Calculator',
    description: 'Calculate the total annualized rate of return an investor will earn if they hold a bond to maturity.',
    slug: 'bond-yield-to-maturity-calculator',
    category: 'finance',
  },
  {
    id: 208,
    name: 'Bond Price Calculator',
    description: 'Calculate the fair market price of a bond based on its characteristics and current market yield.',
    slug: 'bond-price-calculator',
    category: 'finance',
  },
  {
    id: 209,
    name: 'Bond Duration Calculator',
    description: 'Measure a bond\'s price sensitivity to changes in interest rates.',
    slug: 'bond-duration-calculator',
    category: 'finance',
  },
  {
    id: 210,
    name: 'Bond Convexity Calculator',
    description: 'Measure the curvature in the relationship between a bond\'s price and its yield for a more accurate risk estimate.',
    slug: 'bond-convexity-calculator',
    category: 'finance',
  },
  {
    id: 211,
    name: 'Bond Yield Spread Calculator',
    description: 'Measure the difference in yield between two bonds, often to quantify credit risk.',
    slug: 'bond-yield-spread-calculator',
    category: 'finance',
  },
  {
    id: 212,
    name: 'Yield to Call (YTC) / Yield to Worst (YTW) Calculator',
    description: 'Calculate the yield of a callable bond assuming it is redeemed early.',
    slug: 'yield-to-call-calculator',
    category: 'finance',
  },
  {
    id: 213,
    name: 'Zero-Coupon Bond Valuation Calculator',
    description: 'Determine the fair price of a bond that does not pay periodic interest.',
    slug: 'zero-coupon-bond-valuation-calculator',
    category: 'finance',
  },
  {
    id: 214,
    name: 'Simple Inflation-Adjusted Return Calculator',
    description: 'Quickly estimate an investment\'s return after accounting for inflation.',
    slug: 'simple-inflation-adjusted-return-calculator',
    category: 'finance',
  },
  {
    id: 215,
    name: 'Real Rate of Return Calculator',
    description: 'Precisely calculate an investment\'s return after accounting for inflation using the Fisher Equation.',
    slug: 'real-rate-of-return-calculator',
    category: 'finance',
  },
  {
    id: 220,
    name: 'Margin of Safety Calculator',
    description: 'Determine the cushion between a company\'s current sales and its break-even point.',
    slug: 'margin-of-safety-calculator',
    category: 'finance',
  },
  {
    id: 221,
    name: 'Overhead Rate Allocation Calculator',
    description: 'Establish a rate to apply indirect manufacturing costs to products.',
    slug: 'overhead-rate-allocation-calculator',
    category: 'finance',
  },
  {
    id: 222,
    name: 'Activity-Based Costing (ABC) Calculator',
    description: 'Allocate overhead costs more accurately based on specific activities.',
    slug: 'activity-based-costing-calculator',
    category: 'finance',
  },
  {
    id: 223,
    name: 'Depreciation (Straight-Line) Calculator',
    description: 'Calculate asset depreciation evenly over its useful life.',
    slug: 'depreciation-straight-line-calculator',
    category: 'finance',
  },
  {
    id: 224,
    name: 'Depreciation (Double Declining) Calculator',
    description: 'Calculate accelerated depreciation for an asset.',
    slug: 'depreciation-double-declining-calculator',
    category: 'finance',
  },
  {
    id: 225,
    name: 'Depreciation (Sum-of-Years) Calculator',
    description: 'Calculate accelerated depreciation using the Sum-of-the-Years-Digits method.',
    slug: 'depreciation-sum-of-years-digits-calculator',
    category: 'finance',
  },
  {
    id: 226,
    name: 'MACRS Depreciation Calculator',
    description: 'Calculate tax-deductible depreciation for US tax purposes.',
    slug: 'macrs-depreciation-calculator',
    category: 'finance',
  },
  {
    id: 227,
    name: 'Amortization Schedule Generator',
    description: 'Create a detailed payment schedule for any loan.',
    slug: 'amortization-schedule-generator',
    category: 'finance',
  },
  {
    id: 228,
    name: 'Capital Expenditure (CapEx) Payback Calculator',
    description: 'Calculate the time required to recover the initial cost of a project.',
    slug: 'capex-payback-calculator',
    category: 'finance',
  },
  {
    id: 229,
    name: 'Sensitivity Analysis / "What-If" Calculator',
    description: 'Analyze how changing one variable impacts a financial model\'s outcome.',
    slug: 'sensitivity-analysis-what-if-calculator',
    category: 'finance',
  },
  {
    id: 230,
    name: 'Scenario Analysis Calculator',
    description: 'Evaluate a project\'s financial outcome under different scenarios (pessimistic, optimistic, and base case).',
    slug: 'scenario-analysis-calculator',
    category: 'finance',
  },
  {
    id: 231,
    name: 'Currency Exchange Calculator',
    description: 'Convert a monetary amount from one currency to another based on a given exchange rate.',
    slug: 'currency-exchange-calculator',
    category: 'finance',
  },
  {
    id: 232,
    name: 'Currency Volatility Impact Calculator',
    description: 'Quantify the potential gain or loss on a foreign currency holding due to exchange rate fluctuations.',
    slug: 'currency-volatility-calculator',
    category: 'finance',
  },
  {
    id: 233,
    name: 'Fixed vs. Floating Rate Comparison Calculator',
    description: 'Compare the total interest cost of a loan under a fixed rate versus a projected floating rate.',
    slug: 'fixed-vs-floating-rate-calculator',
    category: 'finance',
  },
  {
    id: 235,
    name: 'Swap Spread Calculator',
    description: 'Calculate the difference between a swap rate and a benchmark government bond yield.',
    slug: 'swap-spread-calculator',
    category: 'finance',
  },
  {
    id: 236,
    name: 'Forward Rate Agreement (FRA) Calculator',
    description: 'Calculate the settlement payment for a Forward Rate Agreement.',
    slug: 'forward-rate-agreement-calculator',
    category: 'finance',
  },
  {
    id: 237,
    name: 'Breakeven Inflation Rate Calculator',
    description: 'Derive the market\'s inflation expectation from bond yields.',
    slug: 'breakeven-inflation-rate-calculator',
    category: 'finance',
  },
  {
    id: 238,
    name: 'Credit Default Swap (CDS) Premium Calculator',
    description: 'Conceptually illustrate how a CDS premium is determined.',
    slug: 'credit-default-swap-calculator',
    category: 'finance',
  },
  {
    id: 239,
    name: 'Synthetic Position / Arbitrage Calculator',
    description: 'Check for arbitrage opportunities using Put-Call Parity.',
    slug: 'put-call-parity-calculator',
    category: 'finance',
  },
  // Business & Startup
  {
    id: 216,
    name: 'Debt Service Coverage Ratio (DSCR) Calculator',
    description: 'Measure a firm\'s available cash flow to pay its current debt obligations.',
    slug: 'dscr-calculator',
    category: 'business-startup',
  },
  {
    id: 217,
    name: 'Break-Even Sales Dollar Amount Calculator',
    description: 'Calculate the sales revenue needed to cover all fixed and variable costs.',
    slug: 'break-even-sales-dollar-calculator',
    category: 'business-startup',
  },
  {
    id: 218,
    name: 'Contribution Margin per Unit Calculator',
    description: 'Determine the revenue from one unit sold that is left over after covering the variable costs associated with that unit.',
    slug: 'contribution-margin-calculator',
    category: 'business-startup',
  },
  {
    id: 219,
    name: 'Operating Leverage Calculator',
    description: 'Measure how a company\'s operating income changes in response to a change in sales.',
    slug: 'operating-leverage-calculator',
    category: 'business-startup',
  },
  {
    id: 126,
    name: 'Break-Even Point Calculator',
    description: 'Find the sales volume required to cover all fixed and variable costs.',
    slug: 'break-even-point-calculator',
    category: 'business-startup',
  },
  {
    id: 127,
    name: 'Customer Acquisition Cost (CAC) Calculator',
    description: 'Measure the cost of acquiring one paying customer.',
    slug: 'customer-acquisition-cost-calculator',
    category: 'business-startup',
  },
  {
    id: 128,
    name: 'Lifetime Value (LTV) Calculator',
    description: 'Estimate the total revenue a single customer generates for your business.',
    slug: 'lifetime-value-calculator',
    category: 'business-startup',
  },
  {
    id: 129,
    name: 'Burn Rate Calculator',
    description: 'Track how quickly a startup is using its available cash.',
    slug: 'burn-rate-calculator',
    category: 'business-startup',
  },
  {
    id: 130,
    name: 'ROI Calculator',
    description: 'Measure profitability of a business investment.',
    slug: 'roi-calculator',
    category: 'business-startup',
  },
  // Health & Fitness
  {
    id: 260,
    name: 'Daily Calorie Needs Calculator (TDEE)',
    description: 'Estimate the total calories you burn per day to maintain your current weight.',
    slug: 'daily-calorie-needs-calculator',
    category: 'health-fitness'
  },
  {
    id: 261,
    name: 'Macro Ratio Calculator',
    description: 'Divide your daily calories into grams of protein, carbs, and fat based on your goals.',
    slug: 'macro-ratio-calculator',
    category: 'health-fitness'
  },
  {
    id: 262,
    name: 'Protein Intake Calculator',
    description: 'Get a personalized daily protein recommendation based on your weight and fitness goals.',
    slug: 'protein-intake-calculator',
    category: 'health-fitness'
  },
  {
    id: 263,
    name: 'Carbohydrate Intake Calculator',
    description: 'Estimate your daily carbohydrate needs to fuel your activity level and replenish glycogen stores.',
    slug: 'carbohydrate-intake-calculator',
    category: 'health-fitness'
  },
  {
    id: 264,
    name: 'Fat Intake Calculator',
    description: 'Calculate your recommended daily fat intake as a percentage of total calories.',
    slug: 'fat-intake-calculator',
    category: 'health-fitness'
  },
  {
    id: 265,
    name: 'Keto Macro Calculator',
    description: 'Calculate specific macronutrient targets for a ketogenic diet.',
    slug: 'keto-macro-calculator',
    category: 'health-fitness'
  },
  {
    id: 266,
    name: 'Intermittent Fasting Calculator',
    description: 'Plan your daily eating and fasting windows for different IF protocols.',
    slug: 'intermittent-fasting-calculator',
    category: 'health-fitness'
  },
  {
    id: 267,
    name: 'Glycemic Load Calculator',
    description: 'Measure how much a specific serving of food will raise your blood glucose levels.',
    slug: 'glycemic-load-calculator',
    category: 'health-fitness'
  },
  {
    id: 268,
    name: 'Meal Glycemic Load Calculator',
    description: 'Calculate the total Glycemic Load (GL) of an entire meal.',
    slug: 'meal-glycemic-load-calculator',
    category: 'health-fitness'
  },
  {
    id: 269,
    name: 'Hydration Needs Calculator',
    description: 'Estimate your daily water intake required to stay adequately hydrated.',
    slug: 'hydration-needs-calculator',
    category: 'health-fitness'
  },
  {
    id: 107,
    name: 'Water Footprint of Food Calculator',
    description: 'Estimate the total volume of water required to produce different food items. Understand the hidden water usage in your diet.',
    slug: 'water-footprint-of-food-calculator',
    category: 'health-fitness'
  },
  {
    id: 108,
    name: 'Body Mass Index (BMI) Calculator',
    description: 'Quickly assess whether you are underweight, healthy, overweight, or obese using this standard health indicator.',
    slug: 'bmi-calculator',
    category: 'health-fitness'
  },
  {
    id: 109,
    name: 'Basal Metabolic Rate (BMR) Calculator',
    description: 'Estimate the number of calories your body burns at rest per day. A crucial metric for creating a weight management plan.',
    slug: 'bmr-calculator',
    category: 'health-fitness'
  },
  {
    id: 110,
    name: 'Target Heart Rate Calculator',
    description: 'Determine your optimal heart rate zone for moderate and vigorous exercise to maximize the effectiveness of your workouts.',
    slug: 'target-heart-rate-calculator',
    category: 'health-fitness'
  },
  {
    id: 250,
    name: 'Body Fat Percentage Calculator',
    description: 'Estimate your body fat percentage using the U.S. Navy method.',
    slug: 'body-fat-percentage-calculator',
    category: 'health-fitness'
  },
  {
    id: 251,
    name: 'Lean Body Mass Calculator',
    description: 'Calculate the weight of your body minus all fat mass.',
    slug: 'lean-body-mass-calculator',
    category: 'health-fitness'
  },
  {
    id: 252,
    name: 'Ideal Body Weight (IBW) Calculator',
    description: 'Estimate a healthy weight range based on your height and sex.',
    slug: 'ideal-body-weight-calculator',
    category: 'health-fitness'
  },
  {
    id: 253,
    name: 'Waist-to-Hip Ratio Calculator',
    description: 'Assess health risks associated with abdominal fat.',
    slug: 'waist-to-hip-ratio-calculator',
    category: 'health-fitness'
  },
  {
    id: 254,
    name: 'Waist-to-Height Ratio Calculator',
    description: 'A simple indicator of central obesity and health risk.',
    slug: 'waist-to-height-ratio-calculator',
    category: 'health-fitness'
  },
  {
    id: 255,
    name: 'Body Adiposity Index (BAI) Calculator',
    description: 'Estimate body fat using hip circumference and height.',
    slug: 'body-adiposity-index-calculator',
    category: 'health-fitness'
  },
  {
    id: 256,
    name: 'Ponderal Index Calculator',
    description: 'A measure of leanness, similar to BMI, for very tall or very short individuals.',
    slug: 'ponderal-index-calculator',
    category: 'health-fitness'
  },
  {
    id: 257,
    name: 'Relative Fat Mass (RFM) Calculator',
    description: 'Estimate body fat percentage using only height and waist circumference.',
    slug: 'relative-fat-mass-calculator',
    category: 'health-fitness'
  },
  {
    id: 258,
    name: 'Calorie Deficit Calculator',
    description: 'Calculate daily calorie intake for sustainable weight loss.',
    slug: 'calorie-deficit-calculator',
    category: 'health-fitness'
  },
  {
    id: 259,
    name: 'Calorie Surplus Calculator',
    description: 'Calculate daily calorie intake for muscle and weight gain.',
    slug: 'calorie-surplus-calculator',
    category: 'health-fitness'
  },
  {
    id: 270,
    name: 'Electrolyte Replacement Calculator',
    description: 'Estimate sodium and potassium lost through sweat during exercise.',
    slug: 'electrolyte-replacement-calculator',
    category: 'health-fitness',
  },
  {
    id: 272,
    name: 'Alcohol Calorie Impact Calculator',
    description: 'Calculate the total "empty" calories consumed from alcoholic beverages.',
    slug: 'alcohol-calorie-impact-calculator',
    category: 'health-fitness',
  },
  {
    id: 273,
    name: 'Sugar Intake Calculator',
    description: 'Track your daily consumption of added sugars against recommended limits.',
    slug: 'sugar-intake-calculator',
    category: 'health-fitness',
  },
  {
    id: 274,
    name: 'Caffeine Intake Calculator',
    description: 'Track daily caffeine consumption to stay within safe limits.',
    slug: 'caffeine-intake-calculator',
    category: 'health-fitness',
  },
  // Conversions
  { id: 300, name: 'Meters to Feet Converter', description: 'Convert meters to feet.', slug: 'meters-to-feet-converter', category: 'conversions' },
  { id: 301, name: 'Feet to Meters Converter', description: 'Convert feet to meters.', slug: 'feet-to-meters-converter', category: 'conversions' },
  { id: 302, name: 'Centimeters to Inches Converter', description: 'Convert centimeters to inches.', slug: 'centimeters-to-inches-converter', category: 'conversions' },
  { id: 303, name: 'Inches to Centimeters Converter', description: 'Convert inches to centimeters.', slug: 'inches-to-centimeters-converter', category: 'conversions' },
  { id: 304, name: 'Millimeters to Inches Converter', description: 'Convert millimeters to inches.', slug: 'millimeters-to-inches-converter', category: 'conversions' },
  { id: 305, name: 'Inches to Millimeters Converter', description: 'Convert inches to millimeters.', slug: 'inches-to-millimeters-converter', category: 'conversions' },
  { id: 306, name: 'Meters to Yards Converter', description: 'Convert meters to yards.', slug: 'meters-to-yards-converter', category: 'conversions' },
  { id: 307, name: 'Yards to Meters Converter', description: 'Convert yards to meters.', slug: 'yards-to-meters-converter', category: 'conversions' },
  { id: 308, name: 'Miles to Kilometers Converter', description: 'Convert miles to kilometers.', slug: 'miles-to-kilometers-converter', category: 'conversions' },
  { id: 309, name: 'Kilometers to Miles Converter', description: 'Convert kilometers to miles.', slug: 'kilometers-to-miles-converter', category: 'conversions' },
  { id: 310, name: 'Nautical Miles to Kilometers Converter', description: 'Convert nautical miles to kilometers.', slug: 'nautical-miles-to-kilometers-converter', category: 'conversions' },
  { id: 311, name: 'Kilometers to Nautical Miles Converter', description: 'Convert kilometers to nautical miles.', slug: 'kilometers-to-nautical-miles-converter', category: 'conversions' },
  { id: 312, name: 'Micrometers to Millimeters Converter', description: 'Convert micrometers to millimeters.', slug: 'micrometers-to-millimeters-converter', category: 'conversions' },
  { id: 313, name: 'Nanometers to Meters Converter', description: 'Convert nanometers to meters.', slug: 'nanometers-to-meters-converter', category: 'conversions' },
  { id: 314, name: 'Light Years to Kilometers Converter', description: 'Convert light years to kilometers.', slug: 'light-years-to-kilometers-converter', category: 'conversions' },
  { id: 315, name: 'Parsecs to Light Years Converter', description: 'Convert parsecs to light years.', slug: 'parsecs-to-light-years-converter', category: 'conversions' },
  { id: 316, name: 'Astronomical Units to Kilometers Converter', description: 'Convert AU to kilometers.', slug: 'astronomical-units-to-kilometers-converter', category: 'conversions' },
  { id: 317, name: 'Fathoms to Meters Converter', description: 'Convert fathoms to meters.', slug: 'fathoms-to-meters-converter', category: 'conversions' },
  { id: 318, name: 'Chains to Meters Converter', description: 'Convert chains to meters.', slug: 'chains-to-meters-converter', category: 'conversions' },
  { id: 319, name: 'Rods to Feet Converter', description: 'Convert rods/poles/perches to feet.', slug: 'rods-to-feet-converter', category: 'conversions' },
  { id: 320, name: 'Square Meters to Square Feet Converter', description: 'Convert square meters to square feet.', slug: 'square-meters-to-square-feet-converter', category: 'conversions' },
  { id: 321, name: 'Square Feet to Square Meters Converter', description: 'Convert square feet to square meters.', slug: 'square-feet-to-square-meters-converter', category: 'conversions' },
  { id: 322, name: 'Square Kilometers to Square Miles Converter', description: 'Convert square kilometers to square miles.', slug: 'square-kilometers-to-square-miles-converter', category: 'conversions' },
  { id: 323, name: 'Square Miles to Square Kilometers Converter', description: 'Convert square miles to square kilometers.', slug: 'square-miles-to-square-kilometers-converter', category: 'conversions' },
  { id: 324, name: 'Acres to Square Meters Converter', description: 'Convert acres to square meters.', slug: 'acres-to-square-meters-converter', category: 'conversions' },
  { id: 325, name: 'Square Meters to Acres Converter', description: 'Convert square meters to acres.', slug: 'square-meters-to-acres-converter', category: 'conversions' },
  { id: 326, name: 'Hectares to Acres Converter', description: 'Convert hectares to acres.', slug: 'hectares-to-acres-converter', category: 'conversions' },
  { id: 327, name: 'Acres to Hectares Converter', description: 'Convert acres to hectares.', slug: 'acres-to-hectares-converter', category: 'conversions' },
  { id: 328, name: 'Square Yards to Square Feet Converter', description: 'Convert square yards to square feet.', slug: 'square-yards-to-square-feet-converter', category: 'conversions' },
  { id: 329, name: 'Square Feet to Square Yards Converter', description: 'Convert square feet to square yards.', slug: 'square-feet-to-square-yards-converter', category: 'conversions' },
  { id: 330, name: 'Square Inches to Square Centimeters Converter', description: 'Convert square inches to square centimeters.', slug: 'square-inches-to-square-centimeters-converter', category: 'conversions' },
  { id: 331, name: 'Square Centimeters to Square Inches Converter', description: 'Convert square centimeters to square inches.', slug: 'square-centimeters-to-square-inches-converter', category: 'conversions' },
  { id: 332, name: 'Square Miles to Acres Converter', description: 'Convert square miles to acres.', slug: 'square-miles-to-acres-converter', category: 'conversions' },
  { id: 333, name: 'Acres to Square Miles Converter', description: 'Convert acres to square miles.', slug: 'acres-to-square-miles-converter', category: 'conversions' },
  { id: 334, name: 'Square Meters to Square Yards Converter', description: 'Convert square meters to square yards.', slug: 'square-meters-to-square-yards-converter', category: 'conversions' },
  { id: 335, name: 'Square Yards to Square Meters Converter', description: 'Convert square yards to square meters.', slug: 'square-yards-to-square-meters-converter', category: 'conversions' },
  { id: 336, name: 'Square Centimeters to Square Meters Converter', description: 'Convert square centimeters to square meters.', slug: 'square-centimeters-to-square-meters-converter', category: 'conversions' },
  { id: 337, name: 'Square Meters to Square Centimeters Converter', description: 'Convert square meters to square centimeters.', slug: 'square-meters-to-square-centimeters-converter', category: 'conversions' },
  { id: 338, name: 'Hectares to Square Kilometers Converter', description: 'Convert hectares to square kilometers.', slug: 'hectares-to-square-kilometers-converter', category: 'conversions' },
  { id: 339, name: 'Square Kilometers to Hectares Converter', description: 'Convert square kilometers to hectares.', slug: 'square-kilometers-to-hectares-converter', category: 'conversions' },
  { id: 340, name: 'Liters to Gallons Converter', description: 'Convert liters to US or Imperial gallons.', slug: 'liters-to-gallons-converter', category: 'conversions' },
  { id: 341, name: 'Gallons to Liters Converter', description: 'Convert US or Imperial gallons to liters.', slug: 'gallons-to-liters-converter', category: 'conversions' },
  { id: 342, name: 'Milliliters to Cups Converter', description: 'Convert milliliters to US or Imperial cups.', slug: 'milliliters-to-cups-converter', category: 'conversions' },
  { id: 343, name: 'Cups to Milliliters Converter', description: 'Convert US or Imperial cups to milliliters.', slug: 'cups-to-milliliters-converter', category: 'conversions' },
  { id: 344, name: 'Pints to Liters Converter', description: 'Convert US or Imperial pints to liters.', slug: 'pints-to-liters-converter', category: 'conversions' },
  { id: 345, name: 'Liters to Pints Converter', description: 'Convert liters to US or Imperial pints.', slug: 'liters-to-pints-converter', category: 'conversions' },
  { id: 346, name: 'Quarts to Liters Converter', description: 'Convert US or Imperial quarts to liters.', slug: 'quarts-to-liters-converter', category: 'conversions' },
  { id: 347, name: 'Liters to Quarts Converter', description: 'Convert liters to US or Imperial quarts.', slug: 'liters-to-quarts-converter', category: 'conversions' },
  { id: 348, name: 'Cubic Meters to Liters Converter', description: 'Convert cubic meters to liters.', slug: 'cubic-meters-to-liters-converter', category: 'conversions' },
  { id: 349, name: 'Liters to Cubic Meters Converter', description: 'Convert liters to cubic meters.', slug: 'liters-to-cubic-meters-converter', category: 'conversions' },
  { id: 350, name: 'Cubic Feet to Gallons Converter', description: 'Convert cubic feet to US or Imperial gallons.', slug: 'cubic-feet-to-gallons-converter', category: 'conversions' },
  { id: 351, name: 'Gallons to Cubic Feet Converter', description: 'Convert US or Imperial gallons to cubic feet.', slug: 'gallons-to-cubic-feet-converter', category: 'conversions' },
  { id: 352, name: 'Cubic Inches to Milliliters Converter', description: 'Convert cubic inches to milliliters.', slug: 'cubic-inches-to-milliliters-converter', category: 'conversions' },
  { id: 353, name: 'Milliliters to Cubic Inches Converter', description: 'Convert milliliters to cubic inches.', slug: 'milliliters-to-cubic-inches-converter', category: 'conversions' },
  { id: 354, name: 'Tablespoons to Milliliters Converter', description: 'Convert tablespoons to milliliters.', slug: 'tablespoons-to-milliliters-converter', category: 'conversions' },
  { id: 355, name: 'Milliliters to Tablespoons Converter', description: 'Convert milliliters to tablespoons.', slug: 'milliliters-to-tablespoons-converter', category: 'conversions' },
  { id: 356, name: 'Teaspoons to Milliliters Converter', description: 'Convert teaspoons to milliliters.', slug: 'teaspoons-to-milliliters-converter', category: 'conversions' },
  { id: 357, name: 'Milliliters to Teaspoons Converter', description: 'Convert milliliters to teaspoons.', slug: 'milliliters-to-teaspoons-converter', category: 'conversions' },
  { id: 358, name: 'Ounces (fl oz) to Milliliters Converter', description: 'Convert US or Imperial fluid ounces to milliliters.', slug: 'ounces-to-milliliters-converter', category: 'conversions' },
  { id: 359, name: 'Milliliters to Ounces (fl oz) Converter', description: 'Convert milliliters to US or Imperial fluid ounces.', slug: 'milliliters-to-ounces-converter', category: 'conversions' },
  { id: 360, name: 'Kilograms to Pounds Converter', description: 'Convert kilograms to pounds.', slug: 'kilograms-to-pounds-converter', category: 'conversions' },
  { id: 361, name: 'Pounds to Kilograms Converter', description: 'Convert pounds to kilograms.', slug: 'pounds-to-kilograms-converter', category: 'conversions' },
  { id: 362, name: 'Grams to Ounces Converter', description: 'Convert grams to ounces.', slug: 'grams-to-ounces-converter', category: 'conversions' },
  { id: 363, name: 'Ounces to Grams Converter', description: 'Convert ounces to grams.', slug: 'ounces-to-grams-converter', category: 'conversions' },
  { id: 364, name: 'Milligrams to Grams Converter', description: 'Convert milligrams to grams.', slug: 'milligrams-to-grams-converter', category: 'conversions' },
  { id: 365, name: 'Grams to Milligrams Converter', description: 'Convert grams to milligrams.', slug: 'grams-to-milligrams-converter', category: 'conversions' },
  { id: 366, name: 'Kilograms to Ounces Converter', description: 'Convert kilograms to ounces.', slug: 'kilograms-to-ounces-converter', category: 'conversions' },
  { id: 367, name: 'Ounces to Kilograms Converter', description: 'Convert ounces to kilograms.', slug: 'ounces-to-kilograms-converter', category: 'conversions' },
  { id: 368, name: 'Stones to Pounds Converter', description: 'Convert stones to pounds.', slug: 'stones-to-pounds-converter', category: 'conversions' },
  { id: 369, name: 'Pounds to Stones Converter', description: 'Convert pounds to stones.', slug: 'pounds-to-stones-converter', category: 'conversions' },
  { id: 370, name: 'Tons (Metric) to Pounds Converter', description: 'Convert metric tons to pounds.', slug: 'tons-metric-to-pounds-converter', category: 'conversions' },
  { id: 371, name: 'Pounds to Tons (Metric) Converter', description: 'Convert pounds to metric tons.', slug: 'pounds-to-tons-metric-converter', category: 'conversions' },
  { id: 372, name: 'Short Tons (US) to Metric Tons Converter', description: 'Convert US short tons to metric tons.', slug: 'short-tons-us-to-metric-tons-converter', category: 'conversions' },
  { id: 373, name: 'Metric Tons to Short Tons (US) Converter', description: 'Convert metric tons to US short tons.', slug: 'metric-tons-to-short-tons-us-converter', category: 'conversions' },
  { id: 374, name: 'Micrograms to Milligrams Converter', description: 'Convert micrograms to milligrams.', slug: 'micrograms-to-milligrams-converter', category: 'conversions' },
  { id: 375, name: 'Milligrams to Micrograms Converter', description: 'Convert milligrams to micrograms.', slug: 'milligrams-to-micrograms-converter', category: 'conversions' },
  { id: 376, name: 'Carats to Grams Converter', description: 'Convert carats to grams.', slug: 'carats-to-grams-converter', category: 'conversions' },
  { id: 377, name: 'Grams to Carats Converter', description: 'Convert grams to carats.', slug: 'grams-to-carats-converter', category: 'conversions' },
  { id: 378, name: 'Kilograms to Stones Converter', description: 'Convert kilograms to stones.', slug: 'kilograms-to-stones-converter', category: 'conversions' },
  { id: 379, name: 'Stones to Kilograms Converter', description: 'Convert stones to kilograms.', slug: 'stones-to-kilograms-converter', category: 'conversions' },
  { id: 380, name: 'Kilometers per Hour to Miles per Hour Converter', description: 'Convert km/h to mph.', slug: 'kilometers-per-hour-to-miles-per-hour-converter', category: 'conversions' },
  { id: 381, name: 'Miles per Hour to Kilometers per Hour Converter', description: 'Convert mph to km/h.', slug: 'miles-per-hour-to-kilometers-per-hour-converter', category: 'conversions' },
  { id: 382, name: 'Meters per Second to Kilometers per Hour Converter', description: 'Convert m/s to km/h.', slug: 'meters-per-second-to-kilometers-per-hour-converter', category: 'conversions' },
  { id: 383, name: 'Kilometers per Hour to Meters per Second Converter', description: 'Convert km/h to m/s.', slug: 'kilometers-per-hour-to-meters-per-second-converter', category: 'conversions' },
  { id: 384, name: 'Miles per Hour to Meters per Second Converter', description: 'Convert mph to m/s.', slug: 'miles-per-hour-to-meters-per-second-converter', category: 'conversions' },
  { id: 385, name: 'Meters per Second to Miles per Hour Converter', description: 'Convert m/s to mph.', slug: 'meters-per-second-to-miles-per-hour-converter', category: 'conversions' },
  { id: 386, name: 'Feet per Second to Meters per Second Converter', description: 'Convert ft/s to m/s.', slug: 'feet-per-second-to-meters-per-second-converter', category: 'conversions' },
  { id: 387, name: 'Meters per Second to Feet per Second Converter', description: 'Convert m/s to ft/s.', slug: 'meters-per-second-to-feet-per-second-converter', category: 'conversions' },
  { id: 388, name: 'Knots to Kilometers per Hour Converter', description: 'Convert knots to km/h.', slug: 'knots-to-kilometers-per-hour-converter', category: 'conversions' },
  { id: 389, name: 'Kilometers per Hour to Knots Converter', description: 'Convert km/h to knots.', slug: 'kilometers-per-hour-to-knots-converter', category: 'conversions' },
  { id: 390, name: 'Knots to Miles per Hour Converter', description: 'Convert knots to mph.', slug: 'knots-to-miles-per-hour-converter', category: 'conversions' },
  { id: 391, name: 'Miles per Hour to Knots Converter', description: 'Convert mph to knots.', slug: 'miles-per-hour-to-knots-converter', category: 'conversions' },
  { id: 392, name: 'Mach Number to Kilometers per Hour Converter', description: 'Convert Mach to km/h.', slug: 'mach-number-to-kilometers-per-hour-converter', category: 'conversions' },
  { id: 393, name: 'Kilometers per Hour to Mach Number Converter', description: 'Convert km/h to Mach.', slug: 'kilometers-per-hour-to-mach-number-converter', category: 'conversions' },
  { id: 394, name: 'Mach Number to Miles per Hour Converter', description: 'Convert Mach to mph.', slug: 'mach-number-to-miles-per-hour-converter', category: 'conversions' },
  { id: 395, name: 'Miles per Hour to Mach Number Converter', description: 'Convert mph to Mach.', slug: 'miles-per-hour-to-mach-number-converter', category: 'conversions' },
  { id: 396, name: 'Meters per Second to Knots Converter', description: 'Convert m/s to knots.', slug: 'meters-per-second-to-knots-converter', category: 'conversions' },
  { id: 397, name: 'Knots to Meters per Second Converter', description: 'Convert knots to m/s.', slug: 'knots-to-meters-per-second-converter', category: 'conversions' },
  { id: 398, name: 'Feet per Second to Miles per Hour Converter', description: 'Convert ft/s to mph.', slug: 'feet-per-second-to-miles-per-hour-converter', category: 'conversions' },
  { id: 399, name: 'Miles per Hour to Feet per Second Converter', description: 'Convert mph to ft/s.', slug: 'miles-per-hour-to-feet-per-second-converter', category: 'conversions' },
  { id: 400, name: 'Seconds to Minutes Converter', description: 'Convert seconds to minutes.', slug: 'seconds-to-minutes-converter', category: 'conversions' },
  { id: 401, name: 'Minutes to Seconds Converter', description: 'Convert minutes to seconds.', slug: 'minutes-to-seconds-converter', category: 'conversions' },
  { id: 402, name: 'Minutes to Hours Converter', description: 'Convert minutes to hours.', slug: 'minutes-to-hours-converter', category: 'conversions' },
  { id: 403, name: 'Hours to Minutes Converter', description: 'Convert hours to minutes.', slug: 'hours-to-minutes-converter', category: 'conversions' },
  { id: 404, name: 'Hours to Days Converter', description: 'Convert hours to days.', slug: 'hours-to-days-converter', category: 'conversions' },
  { id: 405, name: 'Days to Hours Converter', description: 'Convert days to hours.', slug: 'days-to-hours-converter', category: 'conversions' },
  { id: 406, name: 'Days to Weeks Converter', description: 'Convert days to weeks.', slug: 'days-to-weeks-converter', category: 'conversions' },
  { id: 407, name: 'Weeks to Days Converter', description: 'Convert weeks to days.', slug: 'weeks-to-days-converter', category: 'conversions' },
  { id: 408, name: 'Weeks to Months Converter', description: 'Convert weeks to months (approximate).', slug: 'weeks-to-months-converter', category: 'conversions' },
  { id: 409, name: 'Months to Weeks Converter', description: 'Convert months to weeks (approximate).', slug: 'months-to-weeks-converter', category: 'conversions' },
  { id: 410, name: 'Months to Years Converter', description: 'Convert months to years.', slug: 'months-to-years-converter', category: 'conversions' },
  { id: 411, name: 'Years to Months Converter', description: 'Convert years to months.', slug: 'years-to-months-converter', category: 'conversions' },
  { id: 412, name: 'Seconds to Hours Converter', description: 'Convert seconds to hours.', slug: 'seconds-to-hours-converter', category: 'conversions' },
  { id: 413, name: 'Hours to Seconds Converter', description: 'Convert hours to seconds.', slug: 'hours-to-seconds-converter', category: 'conversions' },
  { id: 414, name: 'Seconds to Days Converter', description: 'Convert seconds to days.', slug: 'seconds-to-days-converter', category: 'conversions' },
  { id: 415, name: 'Days to Seconds Converter', description: 'Convert days to seconds.', slug: 'days-to-seconds-converter', category: 'conversions' },
  { id: 416, name: 'Seconds to Weeks Converter', description: 'Convert seconds to weeks.', slug: 'seconds-to-weeks-converter', category: 'conversions' },
  { id: 417, name: 'Weeks to Seconds Converter', description: 'Convert weeks to seconds.', slug: 'weeks-to-seconds-converter', category: 'conversions' },
  { id: 418, name: 'Minutes to Days Converter', description: 'Convert minutes to days.', slug: 'minutes-to-days-converter', category: 'conversions' },
  { id: 419, name: 'Days to Minutes Converter', description: 'Convert days to minutes.', slug: 'days-to-minutes-converter', category: 'conversions' },
  { id: 420, name: 'Pascals to Atmospheres Converter', description: 'Convert Pascals (Pa) to standard atmospheres (atm).', slug: 'pascals-to-atmospheres-converter', category: 'conversions' },
  { id: 421, name: 'Atmospheres to Pascals Converter', description: 'Convert standard atmospheres (atm) to Pascals (Pa).', slug: 'atmospheres-to-pascals-converter', category: 'conversions' },
  { id: 422, name: 'Pascals to Bars Converter', description: 'Convert Pascals (Pa) to bars.', slug: 'pascals-to-bars-converter', category: 'conversions' },
  { id: 423, name: 'Bars to Pascals Converter', description: 'Convert bars to Pascals (Pa).', slug: 'bars-to-pascals-converter', category: 'conversions' },
  { id: 424, name: 'Pascals to Pounds per Square Inch Converter', description: 'Convert Pascals (Pa) to psi.', slug: 'pascals-to-psi-converter', category: 'conversions' },
  { id: 425, name: 'Pounds per Square Inch to Pascals Converter', description: 'Convert psi to Pascals (Pa).', slug: 'psi-to-pascals-converter', category: 'conversions' },
  { id: 426, name: 'Atmospheres to Bars Converter', description: 'Convert standard atmospheres (atm) to bars.', slug: 'atmospheres-to-bars-converter', category: 'conversions' },
  { id: 427, name: 'Bars to Atmospheres Converter', description: 'Convert bars to standard atmospheres (atm).', slug: 'bars-to-atmospheres-converter', category: 'conversions' },
  { id: 428, name: 'Atmospheres to Pounds per Square Inch Converter', description: 'Convert standard atmospheres (atm) to psi.', slug: 'atmospheres-to-psi-converter', category: 'conversions' },
  { id: 429, name: 'Pounds per Square Inch to Atmospheres Converter', description: 'Convert psi to standard atmospheres (atm).', slug: 'psi-to-atmospheres-converter', category: 'conversions' },
  { id: 430, name: 'Bars to Pounds per Square Inch Converter', description: 'Convert bars to psi.', slug: 'bars-to-psi-converter', category: 'conversions' },
  { id: 431, name: 'Pounds per Square Inch to Bars Converter', description: 'Convert psi to bars.', slug: 'psi-to-bars-converter', category: 'conversions' },
  { id: 432, name: 'Torr to Pascals Converter', description: 'Convert Torr (mmHg) to Pascals (Pa).', slug: 'torr-to-pascals-converter', category: 'conversions' },
  { id: 433, name: 'Pascals to Torr Converter', description: 'Convert Pascals (Pa) to Torr (mmHg).', slug: 'pascals-to-torr-converter', category: 'conversions' },
  { id: 434, name: 'Torr to Atmospheres Converter', description: 'Convert Torr (mmHg) to standard atmospheres (atm).', slug: 'torr-to-atmospheres-converter', category: 'conversions' },
  { id: 435, name: 'Atmospheres to Torr Converter', description: 'Convert standard atmospheres (atm) to Torr (mmHg).', slug: 'atmospheres-to-torr-converter', category: 'conversions' },
  { id: 436, name: 'Kilopascals to Pounds per Square Inch Converter', description: 'Convert kPa to psi.', slug: 'kpa-to-psi-converter', category: 'conversions' },
  { id: 437, name: 'Pounds per Square Inch to Kilopascals Converter', description: 'Convert psi to kPa.', slug: 'psi-to-kpa-converter', category: 'conversions' },
  { id: 438, name: 'Millimeters of Mercury to Bars Converter', description: 'Convert mmHg to bars.', slug: 'mmhg-to-bars-converter', category: 'conversions' },
  { id: 439, name: 'Bars to Millimeters of Mercury Converter', description: 'Convert bars to mmHg.', slug: 'bars-to-mmhg-converter', category: 'conversions' },
  { id: 440, name: 'Joules to Kilojoules Converter', description: 'Convert Joules (J) to Kilojoules (kJ).', slug: 'joules-to-kilojoules-converter', category: 'conversions' },
  { id: 441, name: 'Kilojoules to Joules Converter', description: 'Convert Kilojoules (kJ) to Joules (J).', slug: 'kilojoules-to-joules-converter', category: 'conversions' },
  { id: 442, name: 'Joules to Calories Converter', description: 'Convert Joules (J) to thermochemical calories (cal).', slug: 'joules-to-calories-converter', category: 'conversions' },
  { id: 443, name: 'Calories to Joules Converter', description: 'Convert thermochemical calories (cal) to Joules (J).', slug: 'calories-to-joules-converter', category: 'conversions' },
  { id: 444, name: 'Joules to Kilocalories Converter', description: 'Convert Joules (J) to Kilocalories (kcal).', slug: 'joules-to-kilocalories-converter', category: 'conversions' },
  { id: 445, name: 'Kilocalories to Joules Converter', description: 'Convert Kilocalories (kcal) to Joules (J).', slug: 'kilocalories-to-joules-converter', category: 'conversions' },
  { id: 446, name: 'Joules to Watt-hours Converter', description: 'Convert Joules (J) to Watt-hours (Wh).', slug: 'joules-to-watt-hours-converter', category: 'conversions' },
  { id: 447, name: 'Watt-hours to Joules Converter', description: 'Convert Watt-hours (Wh) to Joules (J).', slug: 'watt-hours-to-joules-converter', category: 'conversions' },
  { id: 448, name: 'Kilowatt-hours to Joules Converter', description: 'Convert Kilowatt-hours (kWh) to Joules (J).', slug: 'kwh-to-joules-converter', category: 'conversions' },
  { id: 449, name: 'Joules to Kilowatt-hours Converter', description: 'Convert Joules (J) to Kilowatt-hours (kWh).', slug: 'joules-to-kwh-converter', category: 'conversions' },
  { id: 450, name: 'Calories to Kilocalories Converter', description: 'Convert small calories (cal) to nutritional Calories (kcal).', slug: 'calories-to-kilocalories-converter', category: 'conversions' },
  { id: 451, name: 'Kilocalories to Calories Converter', description: 'Convert nutritional Calories (kcal) to small calories (cal).', slug: 'kilocalories-to-calories-converter', category: 'conversions' },
  { id: 452, name: 'British Thermal Units to Joules Converter', description: 'Convert BTU to Joules (J).', slug: 'btu-to-joules-converter', category: 'conversions' },
  { id: 453, name: 'Joules to British Thermal Units Converter', description: 'Convert Joules (J) to BTU.', slug: 'joules-to-btu-converter', category: 'conversions' },
  { id: 454, name: 'Kilowatt-hours to BTU Converter', description: 'Convert kWh to British Thermal Units (BTU).', slug: 'kwh-to-btu-converter', category: 'conversions' },
  { id: 455, name: 'BTU to Kilowatt-hours Converter', description: 'Convert British Thermal Units (BTU) to kWh.', slug: 'btu-to-kwh-converter', category: 'conversions' },
  { id: 456, name: 'Electronvolts to Joules Converter', description: 'Convert electronvolts (eV) to Joules (J).', slug: 'electronvolts-to-joules-converter', category: 'conversions' },
  { id: 457, name: 'Joules to Electronvolts Converter', description: 'Convert Joules (J) to electronvolts (eV).', slug: 'joules-to-electronvolts-converter', category: 'conversions' },
  { id: 458, name: 'Foot-Pounds to Joules Converter', description: 'Convert foot-pounds (ft·lb) to Joules (J).', slug: 'foot-pounds-to-joules-converter', category: 'conversions' },
  { id: 459, name: 'Joules to Foot-Pounds Converter', description: 'Convert Joules (J) to foot-pounds (ft·lb).', slug: 'joules-to-foot-pounds-converter', category: 'conversions' },
  { id: 460, name: 'Watts to Kilowatts Converter', description: 'Convert Watts (W) to Kilowatts (kW).', slug: 'watts-to-kilowatts-converter', category: 'conversions' },
  { id: 461, name: 'Kilowatts to Watts Converter', description: 'Convert Kilowatts (kW) to Watts (W).', slug: 'kilowatts-to-watts-converter', category: 'conversions' },
  { id: 462, name: 'Watts to Megawatts Converter', description: 'Convert Watts (W) to Megawatts (MW).', slug: 'watts-to-megawatts-converter', category: 'conversions' },
  { id: 463, name: 'Megawatts to Watts Converter', description: 'Convert Megawatts (MW) to Watts (W).', slug: 'megawatts-to-watts-converter', category: 'conversions' },
  { id: 464, name: 'Kilowatts to Megawatts Converter', description: 'Convert Kilowatts (kW) to Megawatts (MW).', slug: 'kilowatts-to-megawatts-converter', category: 'conversions' },
  { id: 465, name: 'Megawatts to Kilowatts Converter', description: 'Convert Megawatts (MW) to Kilowatts (kW).', slug: 'megawatts-to-kilowatts-converter', category: 'conversions' },
  { id: 466, name: 'Watts to Horsepower Converter', description: 'Convert Watts (W) to mechanical horsepower (hp).', slug: 'watts-to-horsepower-converter', category: 'conversions' },
  { id: 467, name: 'Horsepower to Watts Converter', description: 'Convert mechanical horsepower (hp) to Watts (W).', slug: 'horsepower-to-watts-converter', category: 'conversions' },
  { id: 468, name: 'Kilowatts to Horsepower Converter', description: 'Convert Kilowatts (kW) to mechanical horsepower (hp).', slug: 'kilowatts-to-horsepower-converter', category: 'conversions' },
  { id: 469, name: 'Horsepower to Kilowatts Converter', description: 'Convert mechanical horsepower (hp) to Kilowatts (kW).', slug: 'horsepower-to-kilowatts-converter', category: 'conversions' },
  { id: 470, name: 'Watts to dBm Converter', description: 'Convert power in Watts to decibel-milliwatts (dBm).', slug: 'watts-to-dbm-converter', category: 'conversions' },
  { id: 471, name: 'dBm to Watts Converter', description: 'Convert power in decibel-milliwatts (dBm) to Watts.', slug: 'dbm-to-watts-converter', category: 'conversions' },
  { id: 472, name: 'Watts to BTU per Hour Converter', description: 'Convert power in Watts to BTU/hr.', slug: 'watts-to-btu-per-hour-converter', category: 'conversions' },
  { id: 473, name: 'BTU per Hour to Watts Converter', description: 'Convert power in BTU/hr to Watts.', slug: 'btu-per-hour-to-watts-converter', category: 'conversions' },
  { id: 474, name: 'Kilowatts to BTU per Hour Converter', description: 'Convert power in Kilowatts to BTU/hr.', slug: 'kilowatts-to-btu-per-hour-converter', category: 'conversions' },
  { id: 475, name: 'BTU per Hour to Kilowatts Converter', description: 'Convert power in BTU/hr to Kilowatts.', slug: 'btu-per-hour-to-kilowatts-converter', category: 'conversions' },
  { id: 476, name: 'Ergs per Second to Watts Converter', description: 'Convert power in ergs per second to Watts.', slug: 'ergs-per-second-to-watts-converter', category: 'conversions' },
  { id: 477, name: 'Watts to Ergs per Second Converter', description: 'Convert power in Watts to ergs per second.', slug: 'watts-to-ergs-per-second-converter', category: 'conversions' },
  { id: 478, name: 'Foot-Pounds per Second to Watts Converter', description: 'Convert power in ft·lb/s to Watts.', slug: 'foot-pounds-per-second-to-watts-converter', category: 'conversions' },
  { id: 479, name: 'Watts to Foot-Pounds per Second Converter', description: 'Convert power in Watts to ft·lb/s.', slug: 'watts-to-foot-pounds-per-second-converter', category: 'conversions' },
  { id: 480, name: 'Shoe Size Converter', description: 'Convert shoe sizes between international systems (US, UK, EU, etc.).', slug: 'shoe-size-converter', category: 'conversions' },
  { id: 481, name: 'Cloth Size Converter', description: 'Convert clothing sizes between international standards (US, UK, EU, etc.).', slug: 'cloth-size-converter', category: 'conversions' },
  { id: 482, name: 'Hat Size Converter', description: 'Convert between different hat sizing systems.', slug: 'hat-size-converter', category: 'conversions' },
  { id: 483, name: 'Ring Size Converter', description: 'Find your equivalent ring size in different countries.', slug: 'ring-size-converter', category: 'conversions' },
  { id: 484, name: 'Belt Size Converter', description: 'Convert belt sizes between different measurement systems.', slug: 'belt-size-converter', category: 'conversions' },
  { id: 485, name: 'Foot Length to Centimeters Converter', description: 'Convert a foot measurement to centimeters.', slug: 'foot-length-to-cm-converter', category: 'conversions' },
  { id: 486, name: 'Glove Size Converter', description: 'Find your glove size based on hand measurements.', slug: 'glove-size-converter', category: 'conversions' },
  { id: 487, name: 'Body Measurement to Clothing Size Converter', description: 'Estimate your clothing size from body measurements.', slug: 'body-measurement-to-cloth-size-converter', category: 'conversions' },
  // Home Improvement
  {
    id: 1,
    name: 'Paint Coverage Calculator',
    description: 'Calculates amount of paint needed for a project.',
    slug: 'paint-coverage-calculator',
    category: 'home-improvement',
  },
  {
    id: 2,
    name: 'Tile & Flooring Calculator',
    description: 'Number of tiles or square metres/feet of flooring material needed, including a % for wastage.',
    slug: 'tile-flooring-calculator',
    category: 'home-improvement',
  },
  {
    id: 3,
    name: 'Wallpaper Roll Calculator',
    description: 'Rolls of wallpaper required based on wall area and pattern repeat.',
    slug: 'wallpaper-roll-calculator',
    category: 'home-improvement',
  },
  {
    id: 4,
    name: 'Drywall/Plasterboard Calculator',
    description: 'Number of drywall sheets and joint compound needed for a room.',
    slug: 'drywall-plasterboard-calculator',
    category: 'home-improvement',
  },
  {
    id: 5,
    name: 'Insulation R-Value Calculator',
    description: 'Recommended insulation thickness and material type for a target R-value.',
    slug: 'insulation-r-value-calculator',
    category: 'home-improvement',
  },
  {
    id: 6,
    name: 'Decking Materials Calculator',
    description: 'Boards, fasteners, and joists needed for a deck of specific size.',
    slug: 'decking-materials-calculator',
    category: 'home-improvement',
  },
  {
    id: 7,
    name: 'Roofing Shingle Calculator',
    description: 'Bundles of shingles and underlayment required for a roof area with pitch adjustment.',
    slug: 'roofing-shingle-calculator',
    category: 'home-improvement',
  },
  {
    id: 8,
    name: 'Concrete Volume Calculator',
    description: 'Cubic metres/feet of concrete required for a slab, footing, or driveway.',
    slug: 'concrete-volume-calculator',
    category: 'home-improvement',
  },
  {
    id: 10,
    name: 'Lighting Layout Calculator',
    description: 'Number and placement of light fixtures needed to achieve a target lux/foot-candle level.',
    slug: 'lighting-layout-calculator',
    category: 'home-improvement',
  },
  {
    id: 11,
    name: 'HVAC Sizing Calculator',
    description: 'Approximate BTU or tonnage of heating/cooling system needed for a room/house size.',
    slug: 'hvac-sizing-calculator',
    category: 'home-improvement',
  },
  {
    id: 12,
    name: 'Staircase Rise & Run Calculator',
    description: 'Number of steps, tread depth, and riser height for a given total height.',
    slug: 'staircase-rise-run-calculator',
    category: 'home-improvement',
  },
  {
    id: 13,
    name: 'Cost Estimator for Renovation',
    description: 'Rough cost breakdown based on square footage and type of work (kitchen, bathroom, etc.).',
    slug: 'cost-estimator-renovation-calculator',
    category: 'home-improvement',
  },
  {
    id: 14,
    name: 'Water Usage / Plumbing Flow Calculator',
    description: 'Expected water flow and pipe size requirements for new fixtures.',
    slug: 'water-usage-plumbing-flow-calculator',
    category: 'home-improvement',
  },
  {
    id: 15,
    name: 'Garden/Landscape Soil & Mulch Calculator',
    description: 'Volume of soil or mulch needed for beds or planters.',
    slug: 'garden-landscape-soil-mulch-calculator',
    category: 'home-improvement',
  },
  // Engineering
  {
    id: 16,
    name: 'Beam Bending Calculator',
    description: 'Calculate bending stress and deflection for beams under load.',
    slug: 'beam-bending-calculator',
    category: 'engineering',
  },
  {
    id: 17,
    name: 'Hydraulic Pipe Flow Calculator',
    description: 'Compute head loss due to friction in a pipe using the Darcy-Weisbach equation.',
    slug: 'hydraulic-pipe-flow-calculator',
    category: 'engineering',
  },
  {
    id: 18,
    name: 'Heat Transfer Calculator',
    description: 'Find steady-state heat transfer rate through a flat wall by conduction.',
    slug: 'heat-transfer-calculator',
    category: 'engineering',
  },
  {
    id: 19,
    name: 'Electrical Power Calculator (3-Phase)',
    description: 'Calculate total real power in a balanced 3-phase electrical system.',
    slug: 'electrical-power-calculator',
    category: 'engineering',
  },
  {
    id: 20,
    name: 'Compressive Stress Calculator',
    description: 'Calculate stress when a compressive load is applied to a material.',
    slug: 'compressive-stress-calculator',
    category: 'engineering',
  },
  {
    id: 21,
    name: 'Cantilever Beam Deflection Calculator',
    description: 'Determine the vertical deflection at the free end of a cantilever beam.',
    slug: 'cantilever-beam-deflection-calculator',
    category: 'engineering',
  },
  {
    id: 22,
    name: 'Natural Frequency Calculator',
    description: 'Calculate the natural frequency of a simple spring-mass system.',
    slug: 'natural-frequency-calculator',
    category: 'engineering',
  },
  {
    id: 23,
    name: 'Reynolds Number Calculator',
    description: 'Determine whether a fluid flow is laminar, transitional, or turbulent.',
    slug: 'reynolds-number-calculator',
    category: 'engineering',
  },
  {
    id: 24,
    name: 'Thermal Expansion Calculator',
    description: 'Compute the change in length of a material due to temperature change.',
    slug: 'thermal-expansion-calculator',
    category: 'engineering',
  },
  {
    id: 25,
    name: 'Shear Stress in a Shaft Calculator',
    description: 'Calculate maximum shear stress in a circular shaft subjected to torsion.',
    slug: 'shear-stress-calculator',
    category: 'engineering',
  },
   // Biology
  { id: 151, name: 'Annealing Temperature (Tm) Calculator', description: 'Estimate the optimal annealing temperature for PCR primers.', slug: 'annealing-temperature-calculator', category: 'biology' },
  { id: 152, name: 'Generation Time Calculator', description: 'Calculate the time required for a cell population to double.', slug: 'generation-time-calculator', category: 'biology' },
  { id: 153, name: 'Cell Dilution Calculator', description: 'Determine the volume needed to dilute a cell culture to a desired concentration.', slug: 'cell-dilution-calculator', category: 'biology' },
  { id: 154, name: 'Cell Doubling Time Calculator', description: 'Calculate the time it takes for a cell population to double in number.', slug: 'cell-doubling-time-calculator', category: 'biology' },
  { id: 155, name: 'DNA Concentration Calculator', description: 'Estimate DNA concentration from spectrophotometer (A260) readings.', slug: 'dna-concentration-calculator', category: 'biology' },
  { id: 156, name: 'Ligation Calculator', description: 'Calculate the required amount of insert for a vector ligation.', slug: 'ligation-calculator', category: 'biology' },
  { id: 157, name: 'Log Reduction Calculator', description: 'Determine the magnitude of microbial reduction after a disinfectant process.', slug: 'log-reduction-calculator', category: 'biology' },
  { id: 158, name: 'Protein Concentration (A280) Calculator', description: 'Estimate protein concentration using absorbance at 280nm.', slug: 'protein-concentration-calculator', category: 'biology' },
  // Cognitive & Psychology
  {
    id: 31,
    name: 'IQ Score Estimator',
    description: 'Estimate IQ based on standardized test scores.',
    slug: 'iq-score-estimator',
    category: 'cognitive-psychology',
  },
  {
    id: 32,
    name: 'Memory Span Calculator',
    description: 'Measure short-term memory capacity.',
    slug: 'memory-span-calculator',
    category: 'cognitive-psychology',
  },
  {
    id: 33,
    name: 'Cognitive Load Calculator',
    description: 'Estimate mental effort for a task.',
    slug: 'cognitive-load-calculator',
    category: 'cognitive-psychology',
  },
  {
    id: 34,
    name: 'Personality Trait Calculator (Big 5)',
    description: 'Estimate 5 personality traits based on a simple self-report scale.',
    slug: 'personality-trait-calculator',
    category: 'cognitive-psychology',
  },
  {
    id: 111,
    name: 'Stroop Effect Reaction-Time Calculator',
    description: 'Measure cognitive interference and selective attention by comparing reaction times.',
    slug: 'stroop-effect-reaction-time-calculator',
    category: 'cognitive-psychology',
  },
  {
    id: 112,
    name: 'Mental Fatigue Index Calculator',
    description: 'Estimate the rate of mental fatigue after performing a cognitive task.',
    slug: 'mental-fatigue-index-calculator',
    category: 'cognitive-psychology',
  },
  {
    id: 115,
    name: 'Sleep Debt Calculator',
    description: 'Determine your weekly sleep debt and its potential impact on cognitive performance.',
    slug: 'sleep-debt-calculator',
    category: 'cognitive-psychology',
  },
  {
    id: 116,
    name: 'Stress Level Index (PSS) Calculator',
    description: 'Score your perceived stress level over the past month using the Perceived Stress Scale.',
    slug: 'stress-level-index-calculator',
    category: 'cognitive-psychology',
  },
  // Genetic & Ancestry
  {
    id: 35,
    name: 'Ancestry Composition Estimator',
    description: 'A simplified tool to estimate ethnic background percentages for entertainment.',
    slug: 'ancestry-composition-estimator',
    category: 'genetic-ancestry',
  },
  {
    id: 36,
    name: 'Genetic Trait Probability Calculator',
    description: 'Predict likelihood of inheriting specific traits using Punnett squares.',
    slug: 'genetic-trait-probability-calculator',
    category: 'genetic-ancestry',
  },
  {
    id: 37,
    name: 'Pedigree Analysis Calculator',
    description: 'Assess simple genetic relationships and inheritance patterns within family trees.',
    slug: 'pedigree-analysis-calculator',
    category: 'genetic-ancestry',
  },
  {
    id: 38,
    name: 'Genealogy Timeline Generator',
    description: 'Visualize an estimated ancestral lineage and key dates over time.',
    slug: 'genealogy-timeline-generator',
    category: 'genetic-ancestry',
  },
  // Environment
  {
    id: 39,
    name: 'Carbon Footprint Calculator',
    description: 'Estimate your annual carbon footprint based on your lifestyle.',
    slug: 'carbon-footprint-reduction-calculator',
    category: 'environment',
  },
  {
    id: 40,
    name: 'Water Usage Efficiency Calculator',
    description: 'Estimates water consumption and potential savings in your household.',
    slug: 'water-usage-efficiency-calculator',
    category: 'environment',
  },
  {
    id: 41,
    name: 'Recycling Impact Calculator',
    description: 'Quantify the environmental benefits of your recycling efforts.',
    slug: 'recycling-impact-calculator',
    category: 'environment',
  },
  {
    id: 42,
    name: 'Sustainable Diet Impact Calculator',
    description: 'Analyzes the water footprint of different dietary choices.',
    slug: 'sustainable-diet-impact-calculator',
    category: 'environment',
  },
  // Travel & Adventure
  {
    id: 51,
    name: 'Backpacking Load Weight Calculator',
    description: 'Assesses optimal backpack weight for treks.',
    slug: 'backpacking-load-weight-calculator',
    category: 'travel-adventure',
  },
  {
    id: 52,
    name: 'Hiking Elevation Gain Calculator',
    description: 'Estimates elevation changes during hikes.',
    slug: 'hiking-elevation-gain-calculator',
    category: 'travel-adventure',
  },
  {
    id: 53,
    name: 'Travel Budget Estimator',
    description: 'Calculates expected expenses for trips.',
    slug: 'travel-budget-estimator',
    category: 'travel-adventure',
  },
  {
    id: 54,
    name: 'Adventure Activity Risk Calculator',
    description: 'Assesses risk levels of various adventure sports.',
    slug: 'adventure-activity-risk-calculator',
    category: 'travel-adventure',
  },
  // Technology
  {
    id: 55,
    name: 'Battery Life Estimator',
    description: 'Predict device runtime from mAh capacity and average power draw.',
    slug: 'battery-life-estimator',
    category: 'technology',
  },
  {
    id: 56,
    name: 'Power Supply Wattage Calculator',
    description: 'Suggest PSU size based on PC components.',
    slug: 'power-supply-wattage-calculator',
    category: 'technology',
  },
  {
    id: 57,
    name: 'Overclocking Thermal Calculator',
    description: 'Estimate CPU/GPU temps from voltage & frequency changes.',
    slug: 'overclocking-thermal-calculator',
    category: 'technology',
  },
  {
    id: 58,
    name: 'Network Bandwidth Calculator',
    description: 'Work out required bandwidth for a given number of users or video streams.',
    slug: 'network-bandwidth-calculator',
    category: 'technology',
  },
  {
    id: 59,
    name: 'Ping / Latency Distance Calculator',
    description: 'Approximate physical distance from ping time.',
    slug: 'ping-latency-distance-calculator',
    category: 'technology',
  },
  {
    id: 60,
    name: 'UPS Runtime Calculator',
    description: 'Estimate backup time for servers or home setups.',
    slug: 'ups-runtime-calculator',
    category: 'technology',
  },
  {
    id: 61,
    name: 'Internet Data Usage Estimator',
    description: 'Predict monthly usage from hours of streaming/gaming.',
    slug: 'internet-data-usage-estimator',
    category: 'technology',
  },
  {
    id: 62,
    name: 'Disk RAID Capacity Calculator',
    description: 'Calculate usable storage and redundancy for RAID levels.',
    slug: 'disk-raid-capacity-calculator',
    category: 'technology',
  },
  {
    id: 64,
    name: 'API Rate Limit Planner',
    description: 'Calculate calls per second/minute based on quota.',
    slug: 'api-rate-limit-planner',
    category: 'technology',
  },
  {
    id: 65,
    name: 'Regex Performance Checker',
    description: 'Estimate time complexity for given regex patterns.',
    slug: 'regex-performance-checker',
    category: 'technology',
  },
  {
    id: 66,
    name: 'Image Compression Size Calculator',
    description: 'Predict final file size for given compression ratio & resolution.',
    slug: 'image-compression-size-calculator',
    category: 'technology',
  },
  {
    id: 67,
    name: 'Password Entropy Calculator',
    description: 'Measure strength of a password by bits of entropy.',
    slug: 'password-entropy-calculator',
    category: 'technology',
  },
  {
    id: 68,
    name: 'Hash Collision Probability Calculator',
    description: 'Estimate chance of collisions for given hash length & number of items.',
    slug: 'hash-collision-probability-calculator',
    category: 'technology',
  },
  {
    id: 69,
    name: 'Cloud Cost Estimator',
    description: 'Rough monthly spend for compute/storage/bandwidth.',
    slug: 'cloud-cost-estimator',
    category: 'technology',
  },
  {
    id: 70,
    name: 'Subnet Mask / CIDR Calculator',
    description: 'Find IP ranges, hosts, and broadcast addresses.',
    slug: 'subnet-mask-cidr-calculator',
    category: 'technology',
  },
  {
    id: 71,
    name: 'Download Time Calculator',
    description: 'Time to download a file based on size and speed.',
    slug: 'download-time-calculator',
    category: 'technology',
  },
  {
    id: 72,
    name: 'Latency-to-Throughput Calculator',
    description: 'Compute max throughput for a given latency (TCP window).',
    slug: 'latency-to-throughput-calculator',
    category: 'technology',
  },
  {
    id: 73,
    name: '3D Print Time & Material Calculator',
    description: 'Estimate filament usage and print time.',
    slug: '3d-print-time-material-calculator',
    category: 'technology',
  },
  {
    id: 74,
    name: 'Solar Panel Output Calculator for Gadgets',
    description: 'Predict daily energy generation for portable solar setups.',
    slug: 'solar-panel-output-calculator',
    category: 'technology',
  },
  // Fun & Games
  {
    id: 75,
    name: 'Dice Roll Probability',
    description: 'Odds of rolling a certain number or combination.',
    slug: 'dice-roll-probability',
    category: 'fun-games',
  },
  {
    id: 76,
    name: 'Board Game Scoring',
    description: 'Track and tally scores for popular games (e.g., Settlers of Catan, Scrabble).',
    slug: 'board-game-scoring',
    category: 'fun-games',
  },
  {
    id: 77,
    name: 'RPG Character Stat',
    description: 'Auto-generate or balance D&D style character stats.',
    slug: 'rpg-character-stat',
    category: 'fun-games',
  },
  {
    id: 78,
    name: 'Esports K/D Ratio',
    description: 'Compute kill/death ratio and needed kills to hit a target K/D.',
    slug: 'esports-kd-ratio',
    category: 'fun-games',
  },
  {
    id: 79,
    name: 'Video Game XP Level-Up',
    description: 'Time or XP needed to reach the next level.',
    slug: 'video-game-xp-level-up',
    category: 'fun-games',
  },
  {
    id: 80,
    name: 'Movie Marathon Time',
    description: 'Total watch time for a list of movies or TV episodes.',
    slug: 'movie-marathon-time',
    category: 'fun-games',
  },
  {
    id: 81,
    name: 'Book Series Reading Time',
    description: 'How many hours to finish a series at your reading speed.',
    slug: 'book-series-reading-time',
    category: 'fun-games',
  },
  {
    id: 82,
    name: 'Song Playlist Duration',
    description: 'Add up total minutes for a playlist.',
    slug: 'song-playlist-duration',
    category: 'fun-games',
  },
  {
    id: 83,
    name: 'Pop Culture Age',
    description: 'How old a celebrity/character would be today.',
    slug: 'pop-culture-age',
    category: 'fun-games',
  },
  {
    id: 86,
    name: 'Emoji Compatibility',
    description: 'Enter two names, see a playful “compatibility score” with emojis.',
    slug: 'emoji-compatibility',
    category: 'fun-games',
  },
  {
    id: 87,
    name: 'Random Nickname Generator',
    description: 'Rate the “coolness” of a generated nickname.',
    slug: 'random-nickname-generator',
    category: 'fun-games',
  },
  {
    id: 88,
    name: 'Friendship Anniversary',
    description: 'Days since you first met.',
    slug: 'friendship-anniversary',
    category: 'fun-games',
  },
  {
    id: 89,
    name: 'Bowling Score',
    description: 'Tally frames and strikes automatically.',
    slug: 'bowling-score',
    category: 'fun-games',
  },
  {
    id: 90,
    name: 'Golf Handicap',
    description: 'Quick estimate of a player’s handicap.',
    slug: 'golf-handicap',
    category: 'fun-games',
  },
  {
    id: 91,
    name: 'Fantasy League Points',
    description: 'Predict weekly fantasy team points.',
    slug: 'fantasy-league-points',
    category: 'fun-games',
  },
  {
    id: 92,
    name: 'Party Budget Per Person',
    description: 'Split cost of food, drinks, decorations.',
    slug: 'party-budget-per-person',
    category: 'fun-games',
  },
  {
    id: 93,
    name: 'BBQ Food & Drink Quantity',
    description: 'Estimate servings needed for a given crowd.',
    slug: 'bbq-food-drink-quantity',
    category: 'fun-games',
  },
  {
    id: 94,
    name: 'Karaoke Queue Time',
    description: 'How long until it’s your turn based on song lengths.',
    slug: 'karaoke-queue-time',
    category: 'fun-games',
  },
  // Cooking & Food
  {
    id: 117,
    name: 'Recipe Ingredient Converter',
    description: 'Scale recipe ingredient quantities up or down for different serving sizes.',
    slug: 'recipe-ingredient-converter',
    category: 'cooking-food',
  },
  {
    id: 118,
    name: 'Cooking Time Adjuster',
    description: 'Estimate new cooking time when you change the oven temperature.',
    slug: 'cooking-time-adjuster',
    category: 'cooking-food',
  },
  {
    id: 120,
    name: 'Brining Solution Calculator',
    description: 'Calculate correct salt and sugar ratio for brines to ensure perfect flavor and texture.',
    slug: 'brining-solution-calculator',
    category: 'cooking-food',
  },
  {
    id: 121,
    name: 'Meat Thawing Time Calculator',
    description: 'Estimate safe refrigerator thawing time for frozen meat based on weight.',
    slug: 'meat-thawing-time-calculator',
    category: 'cooking-food',
  },
  // Personal Budgeting
  {
    id: 122,
    name: '50/30/20 Budget Calculator',
    description: 'Split income into needs, wants, and savings using the popular 50/30/20 rule.',
    slug: '50-30-20-budget-calculator',
    category: 'personal-budgeting',
  },
  {
    id: 123,
    name: 'Monthly Budget Surplus/Deficit Calculator',
    description: 'Determine if you are living within your means by comparing income and expenses.',
    slug: 'monthly-budget-surplus-deficit-calculator',
    category: 'personal-budgeting',
  },
  {
    id: 124,
    name: 'Debt-to-Income (DTI) Ratio Calculator',
    description: 'Measure how much of your income goes toward debt payments (important for loan approvals).',
    slug: 'dti-ratio-calculator',
    category: 'personal-budgeting',
  },
  {
    id: 106,
    name: 'Emergency Fund Goal Calculator',
    description: 'Calculate how much cash you should set aside for unexpected expenses.',
    slug: 'emergency-fund-goal-calculator',
    category: 'personal-budgeting',
  },
  {
    id: 125,
    name: 'Savings Rate Calculator',
    description: 'Track the percentage of income you are saving each month.',
    slug: 'savings-rate-calculator',
    category: 'personal-budgeting',
  },
  // Crypto & Web3
  {
    id: 131,
    name: 'Crypto Mining Profitability Calculator',
    description: 'Estimate daily/monthly profit from crypto mining.',
    slug: 'crypto-mining-profitability-calculator',
    category: 'crypto-web3',
  },
  {
    id: 132,
    name: 'Crypto Tax Liability Calculator',
    description: 'Estimate tax owed on crypto capital gains.',
    slug: 'crypto-tax-liability-calculator',
    category: 'crypto-web3',
  },
  {
    id: 133,
    name: 'Crypto Staking Reward Calculator',
    description: 'Calculate total coins earned from staking.',
    slug: 'crypto-staking-reward-calculator',
    category: 'crypto-web3',
  },
  {
    id: 134,
    name: 'NFT Minting Cost Calculator',
    description: 'Estimate total cost to mint an NFT in USD.',
    slug: 'nft-minting-cost-calculator',
    category: 'crypto-web3',
  },
  {
    id: 135,
    name: 'Crypto APY (Yield Farming) Calculator',
    description: 'Calculate final amount after yield farming.',
    slug: 'crypto-apy-calculator',
    category: 'crypto-web3',
  },
  // Parenting
  {
    id: 137,
    name: 'Pregnancy Due Date Calculator',
    description: 'Estimate your baby\'s due date based on your last menstrual period.',
    slug: 'due-date-calculator',
    category: 'parenting',
  },
  {
    id: 138,
    name: 'Baby Feeding Amount Calculator',
    description: 'Calculate the recommended daily milk/formula intake for your baby.',
    slug: 'baby-feeding-amount-calculator',
    category: 'parenting',
  },
  {
    id: 139,
    name: 'College Savings Goal Calculator',
    description: 'Estimate the monthly savings needed to meet future college tuition costs.',
    slug: 'college-savings-goal-calculator',
    category: 'parenting',
  },
  {
    id: 140,
    name: 'Childcare Cost Affordability Calculator',
    description: 'Assess what percentage of your income is spent on childcare.',
    slug: 'childcare-cost-affordability-calculator',
    category: 'parenting',
  },
  // Sports & Training
  {
    id: 141,
    name: 'BMI (Body Mass Index) Calculator',
    description: 'Assess your weight status category (underweight, normal, overweight, obese).',
    slug: 'sports-training-bmi-calculator',
    category: 'sports-training',
  },
  {
    id: 142,
    name: 'Basal Metabolic Rate (BMR) Calculator',
    description: 'Calculate your daily calorie needs for weight management.',
    slug: 'sports-training-bmr-calculator',
    category: 'sports-training',
  },
  {
    id: 143,
    name: 'Target Heart Rate Zone Calculator',
    description: 'Find your ideal heart rate range for fat burn or cardio fitness.',
    slug: 'sports-training-target-heart-rate-calculator',
    category: 'sports-training',
  },
  {
    id: 144,
    name: 'VO₂ Max Estimation Calculator',
    description: 'Estimate your maximal oxygen uptake from a 1.5-mile run time.',
    slug: 'vo2-max-estimation-calculator',
    category: 'sports-training',
  },
  {
    id: 145,
    name: 'One-Rep Max (1RM) Calculator',
    description: 'Estimate the maximum weight you can lift for one repetition.',
    slug: 'one-rep-max-calculator',
    category: 'sports-training',
  },
  // Time & Date
  {
    id: 146,
    name: 'Date Difference Calculator',
    description: 'Find the duration in days, weeks, and months between two dates.',
    slug: 'date-difference-calculator',
    category: 'time-date',
  },
  {
    id: 147,
    name: 'Age Calculator',
    description: 'Calculate a person\'s exact age in years, months, and days from their date of birth.',
    slug: 'age-calculator',
    category: 'time-date',
  },
  {
    id: 148,
    name: 'World Time Zone Converter',
    description: 'Convert the time and date from one city or timezone to another.',
    slug: 'world-time-zone-converter',
    category: 'time-date',
  },
  {
    id: 149,
    name: 'Day of the Week Calculator',
    description: 'Find out the day of the week for any given date in history or the future.',
    slug: 'day-of-the-week-calculator',
    category: 'time-date',
  },
  {
    id: 150,
    name: 'Working Days / Business Days Calculator',
    description: 'Calculate the number of business days between two dates, excluding weekends and public holidays.',
    slug: 'working-days-business-days-calculator',
    category: 'time-date',
  },
];